configure, myocamlbuild.ml.in, opam, opam.deps
This opam configuration is as simple as possible, without optional dependencies and 
trying to figure out what system packages do we have. Just for a start.
Also, I've also noticed, that sed trick in the configure script is not
crossplatfrom. It even doesn't work on Mac OS X. So, I've removed
it and commented tagging instructions in myocamlbuild. As a consequence
we will have warnings on OCaml 4.02.
=> Preliminary support for OPAM.

README.md, setup.py
Moving `setup.py` will allow one to install `python` bindings directly
from github.
Also, the README.md file is updated. I've removed unecessary
details (moving them to wiki), and added information on how to install,
everything using `pip` and `opam`.
=> bap is now a pip package.

lib/bap_disasm/bap_disasm_arm_mem_shift.ml
When working with bap instructions in Qira, I came across the following instruction that did not have BIL associated with it:
```
ldr	r2, [r3, r2]
```
The lifter was failing because it falsely assumed that offsets cannot be registers in loads. This PR fixes that bug.
=> Fixes issue in lifter where register offsets were not accounted for.

_oasis, lib/bap_image/bap_fileutils.ml, lib/bap_image/bap_fileutils.mli, lib/bap_image/bap_image.ml, lib/bap_image/bap_memory.ml, lib/bap_image/bap_memory.mli, lib/bap_image/image_elf.ml, src/readbin/cmdline.ml, src/readbin/options.ml, src/readbin/readbin.ml
bap-objdump: add argument for reading raw binary code
bap-fileutils: refactor file i/o utility code out from bap_memory and bap_image
bap-memory: add of_file constructor function
=> add argument to objdump for reading raw binary code, some refactoring/typo fixes

lib/bap_disasm/bap_signatures.ml, src/byteweight/byteweight.ml, src/readbin/ida.ml, src/readbin/ida.mli, src/readbin/readbin.ml, src/readbin/symbols.ml, src/readbin/symbols.mli
This PR contains fixes, that will allow to pass CI test for x86 and
x86_64 lifter.
It includes the ability to retrieve signatures for x86, that was
uploaded to github (For some reason, github doesn't allow us to release
files with other extensions, so this PR renames `sigs.db` to
`sigs.zip`). Also, there're some small fixes, like hardcoded 32 bits
address widths in readbin.
=> Preparation for x86 integration.

_oasis, lib/bap/bap_load_plugins.ml, lib/bap/bap_plugin.ml, lib/bap/bap_plugins.ml, lib/bap_image/image_elf.ml, src/readbin/cmdline.ml, src/readbin/options.ml, src/readbin/readbin.ml
This will resolve BinaryAnalysisPlatform/qira#69,
and partially fix #64, since loading plugins still won't work out of
box, until one defines the OCAMLPATH variable.
=> Make bap utilities standalone executables.

_oasis
Since they're already loaded and linked statically, the shouldn't be
dynlinked anymore. Nothing will break, but funny messages can be seen
in standard error.
=> Disables dynamic autoloading of internal plugins.

myocamlbuild.ml.in, opam, postinstall.ml.ab
This is PR fixes some issues with BAP infrastructure:
Added checking x bit for installed tools
=======================================
Unfortunately `FileUtil.cp` doesn't preserve permissions, and I'm not
sure that it is very easy to do in a cross-platform way.
tricked ocamlbuild to ignore unused tags
========================================
should work across different compiler versions.
added constraints to opam
=========================
we really can't compile without it, and without aspucd the solver can
give us very old version.
=> Housekeeping

opam
The difference is with version. It is set to master, so that we can
distinguish between bap installed from repository, and pinned one.
=> Synced opam file with repository version

bapbuild, src/byteweight/byteweight.ml
With this PR one can build plugin consisting of several
files (previously you will see a link-time errors).
Moreover, it will fix an issue with bap-byteweight that didn't
understand `--version` option.
=> Fix bapbuild plugin compilation

bapbuild
With this PR bapbuild will automatically load bap.plugins library, that
doesn't mean that you shouldn't call to `Plugins.load ()` anymore,
although, this behavior can be added.
=> Add bap.plugins support to bapbuild.

python/adt.py
Recurse into tuple args when printing. This looks better especially for empty tuples, which show up a lot as clauses in If statements.
For example, before this change: 
`If(EQ(AND(Int(0x8049a00, 0x20), Int(0xf, 0x20)), Int(0x0, 0x20)), "()", CpuExn(0xd))` 
and after: 
`If(EQ(AND(Int(0x8049a00, 0x20), Int(0xf, 0x20)), Int(0x0, 0x20)), (), CpuExn(0xd))`
=> slight change to ADT repr

lib/bap_disasm/bap_disasm_x86_utils.ml
Typo is giving FLAGS regs the wrong lengths. For example, when lifting the `\x9c` `pushf` instruction, the generated BIL shows a 32-bit store of a 33-bit value.
=> FLAGS registers fixes

lib/bap_types/bap_common.ml, lib/bap_types/bap_size.ml
Lifting i386 XMM & YMM instructions currently returns a "unsupported word size: 128" error, e.g. for `f3 0f 7f 04 38	movdqu %xmm0,(%eax,%edi,1)`. Adding these \`r128 and \`r256 cases makes lifting work again.
=> add `r128 and `r256 to support YMM lifting

_oasis, lib/bap_disasm/bap_disasm_block.ml, lib/bap_disasm/bap_disasm_block.mli, lib/bap_disasm/bap_disasm_rec.ml, lib/bap_disasm/bap_disasm_rec.mli, lib/bap_disasm/bap_disasm_symtab.ml, lib/bap_disasm/bap_disasm_symtab.mli, opam.deps, opam.opt.deps
This PR brings two new data structures:
- Symtab.Graph - a callgraph as a persistent OCamlGraph's graph
- Block.Graph - a control-flow graph as it is.
Two new functions are provided.
- Block.to_graph will build a graph given the entry block and
possible memory boundaries
- Symtab.to_graph will build a callgraph preserving information
about call places.
=> Interface to OCamlGraph

lib/bap_types/bap_common.ml, lib/bap_types/bap_size.ml
Reverts BinaryAnalysisPlatform/bap#126
The merge was premature, since this change breaks a lot of code.
=> Revert "add `r128 and `r256 to support YMM lifting"

lib/bap_disasm/bap_disasm_rec.ml, lib_test/bap_disasm/test_disasm.ml
When we fall to the one byte instruction, like `ret` for example, we
will miss it, since the algorithm will start to look at the next byte.
This PR fixes this issue. A test case is added.
=> Fix one-byte block issue in CFG reconstruction.

_oasis, lib/bap_disasm/bap_disasm.ml, lib/bap_disasm/bap_disasm_abi.ml, lib/bap_disasm/bap_disasm_abi_helpers.ml, lib/bap_disasm/bap_disasm_abi_helpers.mli, lib/bap_disasm/bap_disasm_arm_env.mli, lib/bap_disasm/bap_disasm_arm_lifter.ml, lib/bap_disasm/bap_disasm_std.ml, lib/bap_disasm/bap_disasm_stub_lifter.ml, lib/bap_disasm/bap_disasm_stub_lifter.mli, lib/bap_disasm/bap_disasm_types.ml, lib/bap_disasm/bap_disasm_x86_lifter.ml, lib/bap_disasm/bap_disasm_x86_lifter.mli, lib/bap_types/bap_helpers.mli, lib_test/bap_disasm/test_disasm.ml, src/readbin/helpers.ml, src/readbin/printing.ml, src/readbin/printing.mli, src/readbin/readbin.ml, src/server/adt.ml, src/server/adt.mli, src/server/rpc.mli, src/server/server.ml
This PR unifies all lifter targets under the common interface, named
Target. Also disasm library is cleaned and more unified. As a
consequence bap-server now also should give back a bil for x86 family.
Two new main data structures under the Target module:
- CPU defines CPU specific BIL expressions, allowing one to figure out
what variable is PC, and what is register or flag. It also abstracts
the process of resolving PC to addresses.
- ABI this one abstracts application binary interface, including calling
convention, stack frame and data representation, and maybe more
Given this new structures, I've added a new optimization to the BIL
printer that will resolve PC-relative addresses to its values.
With this the following:
```ocaml
begin(sub_ad5c_0x160) {
R3 := mem[PC + 0x65C:32, el]:u32 …
```
=> Introduce ABI and CPU.

src/server/adt.ml
This change will make temporary variables have their unique names in the BIL output from `bap-server`.
=> Makes bap-server emit full variable names

lib/bap/bap_program_visitor.ml, lib/bap/bap_program_visitor.mli, src/readbin/helpers.ml, src/readbin/helpers.mli, src/readbin/readbin.ml
This PR provides a new field in a project record: a function that will
transform instruction list to a BIL program. Initially this
transformation includes all optimizations that were requested from the
command line. Plugin, can rebind this optimization.
There is one issue, that should be qualified, the call
`project.bil_of_insns` is statically bound to the `project`, so there is
no open recursion here or any late binding. So all your changes to the
project will not affect this function, until the next plugin, where it
will be rebound to the new state of project.
I'm considering to switch project type to the object type.
=> Propagate BIL transformations though plugins.

_oasis, lib/bap_disasm/bap_disasm_abi.ml, lib/bap_disasm/bap_disasm_abi_helpers.ml, lib/bap_disasm/bap_disasm_abi_helpers.mli, lib/bap_disasm/bap_disasm_amd64_abi.ml, lib/bap_disasm/bap_disasm_amd64_abi.mli, lib/bap_disasm/bap_disasm_arm.mli, lib/bap_disasm/bap_disasm_arm_abi.ml, lib/bap_disasm/bap_disasm_arm_abi.mli, lib/bap_disasm/bap_disasm_arm_lifter.ml, lib/bap_disasm/bap_disasm_arm_lifter.mli, lib/bap_disasm/bap_disasm_block.ml, lib/bap_disasm/bap_disasm_ia32_abi.ml, lib/bap_disasm/bap_disasm_ia32_abi.mli, lib/bap_disasm/bap_disasm_std.ml, lib/bap_disasm/bap_disasm_stub_lifter.ml, lib/bap_disasm/bap_disasm_stub_lifter.mli, lib/bap_disasm/bap_disasm_x86_lifter.ml, lib/bap_disasm/bap_disasm_x86_lifter.mli, lib/bap_disasm/bap_program_visitor.ml, lib/bap_disasm/bap_program_visitor.mli, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli, src/readbin/helpers.ml
This PR adds preliminary support for ARM gnueabi. Currently only
parameters passed via registers are recognized. The `return_value` is
set to always return `Some r0`, as type inference is needed for a more
correct heuristics, since may functions finishes with
`jmp another_function`.
The abi interface is little bit refined. First of all the `return_value`
now returns an option type, to handle functions returning `void`. ABI
modules are moved into the corresponding targets. So to create an
instance of abi one should call to `Target.ABI.create` function. In
general one should use module `Target` as returned by
`target_of_arch` function to access cross-platform
abstractions. Platform specific abstractions are still available, under
corresponding modules, e.g., `ARM.CPU.r0` will refer to the …
=> Introduce arm-gnueabi and some fixes.

src/readbin/cmdline.ml
Previously the error message did not have a newline
when no options were provided, which was unaesthic and
offset the next command prompt.
=> Adds a newline to the bap-objdump error message.

_oasis, baptop, opam, opam.deps, src/bap_mc/bap_mc.ml
Also, this requires that you update your piqi to the latest version, built so that the interpreter can find the function it needs dynamically. A pull request was sent to the piqi repo maintainer in order that this be done, when it's finished do an opam upgrade piqi.
=> As per small commit messages edited bap-mc for disassembling on command line and revived piqi translation ability

lib/bap_disasm/bap_disasm_arm_abi.ml, lib/bap_disasm/bap_disasm_block.ml, lib/bap_disasm/bap_disasm_block.mli, lib/bap_disasm/bap_disasm_insn.ml, lib/bap_image/bap_memmap.mli, lib/bap_types/bap_exp.ml, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_visitor.ml, lib/bap_types/bap_visitor.mli, src/readbin/helpers.ml, src/readbin/readbin.ml
This is a snapshot of a work-in-progress, to provide recognition of
parameters, structures and locals to arm programs. I'm commiting this
since it is needed for the plugins. Other than fixes to arm gnueabi
implementation it also introduces `Block.dfs` function, that will
return a sequence of block successors or predecessors in a DFS
order (including the block itself). It also introduces several new
arithmetic optimizations, as well as some other optimizations, like
load/store for example.
=> Some new optimizations and fixed arm-gnueabi

src/readbin/cmdline.ml, src/readbin/ida.ml, src/readbin/idapy.ml, src/readbin/idapy.mli, src/readbin/options.ml, src/readbin/readbin.ml
This PR will add two new command line options, and (hopefully) fix
issues with locating IDA.
1. added -L option.
This option allows to specify search paths for BAP plugins. The
option can be specified several times. Moreover, one can specify
search path using `BAP_PLUGIN_PATH` environment variable, that
accepts a set of paths separated by `:`.
2. added --emit-ida-script option, that will dump an IDA script,
using new function `Idapy.annotate_ida`. This function allow plugins
to smoothly talk to IDA, by annotating code segments with python
commands.
3. fixed location issue. Only those entries of the locatedb are
considered that ends with the specified string.
=> Extended integration with IDA.

_oasis, lib/bap_disasm/bap_disasm_basic.ml, lib/bap_disasm/bap_disasm_basic.mli, lib/bap_disasm/bap_disasm_block.mli, lib/bap_disasm/bap_disasm_insn.ml, lib/bap_disasm/bap_disasm_insn.mli, lib/bap_types/bap_bil_adt.ml, lib/bap_types/bap_bil_adt.mli, lib/bap_types/bap_types.ml, src/bap_mc/bap_mc.ml, src/readbin/readbin.ml, src/server/adt.ml
Now bap-mc supports 7 formats for outputting BIL and three formats for
printing assembly. The command line interface is refactored.
=> bap-mc enhancing.

lib/bap_types/bap_arch.ml
This is a little bit a hack, since it breaks tradition. But now, when
one says ARM we understand it like ARMv7. I didn't like it...
=> ARM now defaults to ARMv7

lib/bap/bap.ml, lib/bap/bap_program_visitor.mli, lib/bap_disasm/bap_disasm_arm_bit.ml, lib/bap_disasm/bap_disasm_arm_branch.ml, lib/bap_disasm/bap_disasm_arm_flags.ml, lib/bap_disasm/bap_disasm_arm_lifter.ml, lib/bap_disasm/bap_disasm_arm_mem.ml, lib/bap_disasm/bap_disasm_arm_mem_shift.ml, lib/bap_disasm/bap_disasm_arm_mov.ml, lib/bap_disasm/bap_disasm_arm_mul.ml, lib/bap_disasm/bap_disasm_arm_shift.ml, lib/bap_disasm/bap_disasm_arm_utils.ml, lib/bap_disasm/bap_disasm_rec.ml, lib/bap_disasm/bap_disasm_x86.ml, lib/bap_disasm/bap_disasm_x86_lifter.ml, lib/bap_disasm/bap_disasm_x86_utils.ml, lib/bap_types/bap_helpers.mli, lib/bap_types/bap_regular.mli, lib/bap_types/bap_stmt.ml, lib/bap_types/bap_stmt.mli, lib/bap_types/bap_types.ml, lib/bap_types/bil_piqi.ml, lib/bap_types/conceval.ml, lib_test/bap_types/test_conceval.ml, src/bap_mc/bap_mc.ml, src/readbin/helpers.ml, src/readbin/printing.ml
Now `Bil` is for writing BIL programs. `Stmt` and `Expr`
modules are for using them as an OCaml values, i.e.,
they expose `Regular` interface.
`Bil` module also exposes `Printable`, `Sexpable` and `Binable`
interfaces.
=> Cleaned BIL module.

lib/bap/bap_program_visitor.ml, lib/bap/bap_program_visitor.mli, src/bap_mc/bap_mc.ml, src/readbin/cmdline.ml, src/readbin/readbin.ml
This PR makes available command line arguments in the plugin.
Only a restricted subset of command line language is allowed, as all
arguments must be non-positional with long name option (i.e., start with
`--`), and values (if any) must be provided with `=` sign,
e.g. `--callstrings-interesting=st.cpy`. Parameters must be prefixed
with the name of plugin to which they should be passed, e.g.,
```
bap-objdump /bin/ls -lstaticstore --staticstore-help
```
A set of parameters is passed to a plugin in a `argv` field of a project
record with removed prefixes, e.g., `--staticstore-help` is transformed
to `--help`;  `--staticstore-print` is transformed to `--print`; etc.
=> Add command line arguments for plugins

lib/bap_image/bap_image.ml, lib/bap_image/bap_image.mli, src/readbin/cmdline.ml
This will switch BAP to use LLVM as a default loader.
Also, this change the behavior of the `Image.create` function.
Previously, if backend wasn't specified it started the autoresolution
process. Now, it will default "llvm" also. But, if "auto" is provided
as a backend name, then the autoresolution will be started.
=> Switch to LLVM backend by default.

_oasis, bapbuild, lib/bap/bap_install_printers.ml, lib/bap/bap_program_visitor.ml, lib/bap/bap_program_visitor.mli, lib/bap_disasm/bap_disasm.ml, lib/bap_disasm/bap_disasm.mli, lib/bap_image/bap_image.ml, lib/bap_image/bap_image.mli, lib/bap_image/image_backend.ml, lib/bap_image/image_elf.ml, lib/bap_image/llvm_loader.ml, lib/bap_image/llvm_loader.mli, lib/bap_types/bap_stmt.ml, lib/bap_types/bap_tag.ml, lib/bap_types/bap_tag.mli, lib/bap_types/bap_types.ml, lib_test/bap_image/test_image.ml, src/readbin/cmdline.ml, src/readbin/idapy.ml, src/readbin/idapy.mli, src/readbin/readbin.ml
This PR moves from previous stringly typed `(string * string)` tags,
to a new typesafe extensible variant types, based on universal types,
aka existentials.
This allows plugin writers to speak with each other in a type-safe
manner, using BAP library as a mediator.
Also this PR fixes few small issues, like errors when installing
pretty-printers from core library, and the necessity to clean before
calling to `bapbuild`.
Also this PR fixes #60.
=> Type safe memory annotations.

lib/bap/bap_project.mli, opam, postinstall.ml.ab
Releasing revealed a bug in documentation, that wasn't caught by CI,
since we're not compiling documentation on Travis. I've fixed this
bug in opam file, that is in the official repository, and bumped changes
back here. Also, I fixed the source of the error.
Since, that time we no longer build documentation as a part of
installation, since it takes too much time, very faulty (this is not a
first time), and worthless (the output is of very low quality). When
codoc will mature, we will return to this issue.
=> Fix building documentation.

lib/bap_disasm/bap_disasm_block.mli, lib/bap_disasm/bap_disasm_block_intf.ml, lib/bap_disasm/bap_disasm_rec.ml
Now `succs` and `dests` functions returns successors in the order of
execution. As a result, dfs algorithm will visit blocks in the execution
order.
=> Ordered block destinations.

_oasis, bapbuild.ml
On a linking phase, we're excluding from the plugin all bap library
dependencies, but not the dependencies of the bap executable. As a
result we can link the same library twice, and if it has some kind
of state it can lead to undefined behavior, aka segmentation fault.
Since it is impossible to figure out what libraries are linked into
the bap binary in runtime, the only way it to hardcode this information
in the bapbuild itself. As a side effect, there is no need to define
`-pkg cmdliner,re.posix` to compile a plugin. In fact, all bap binary
dependencies are now automatically available.
=> Fix possible double linking in bapbuild.

lib/bap_disasm/bap_disasm_block.ml, lib/bap_disasm/bap_disasm_block.mli
There was a bug in `Block.dfs` that results in that
dsf sequence of blocks was consumed after first run.
In the nature of an apology for this I also provided
an extra optional parameter `order` that allows you
to specify whether you would like visit blocks in
pre-order or post-order.
Also I fixed #181.
=> Fix #181 and Block.dfs.

lib/bap_disasm/bap_disasm_x86_lifter.ml
Fixed bug with sum of bitvectors with different width. This bug occured during work with 64-bit PE files
=> fixed bug with sum of bitvectors with different width

LICENSE, Makefile, _oasis, bapdoc.ml, doc/COPYING, doc/style.css, opam
This will remove old documentation generator, and
integrate new `bapdoc` tool with the build system.
The target `doc` will now build documentation. Installation is left on
behalf of opam.
Also, small fixes to opam and a tentative addition of external
dependencies on mac os x.
=> Integrate bapdoc with build system.

lib/bap_types/bil_piqi.ml, lib/bap_types/exp.piqi, lib/bap_types/stmt.piqi, lib/bap_types/type.piqi, src/bap_mc/bap_mc.ml
For our specific use cases, we needed to be able to know the opcode length, stop disassembling after some number of instructions and lastly specify a memory offset in order that certain BIL semantics be generated correctly.
Additionally, we would like to be able to deserialize via any method supported, so I went about changing the BIL spec to rename only what had forced keyword conflicts, I then propagated those changes throughout related ml code, and it compiles
=> As per discussion, grammar names conflict with cpp vernacular keywords, and some options were needed in bap-mc

_oasis, src/readbin/bap-byteweight.ml, src/readbin/find_starts.ml, src/readbin/find_starts.mli, src/readbin/fsi_benchmark.ml, src/readbin/fsi_benchmark.mli, src/readbin/func_start.ml, src/readbin/func_start.mli, src/readbin/ground_truth.ml, src/readbin/ground_truth.mli, src/readbin/ida.ml, src/readbin/ida.mli, src/readbin/readbin.ml, src/readbin/symbols.ml, src/readbin/symbols.mli
This is the new implementation of the original `bap-compare`, which we rename it to `bap-fsi-benchmark`. The code is improved from the following points: 1. change io interfaces of symbols.ml to input and output channels. 2. more helper information. 3. redesign the command argument. 4. sync with latest bap (0.9.7). 5. process the abnormal command exit.
=> bap-fsi-benchmark implementation

src/readbin/bap-byteweight.ml, src/readbin/find_starts.ml
Remove redundant argument from bap-byteweight, and change a closure in `find_starts.ml`
=> Minor change for bap-byteweight and bap-fsi-benchmark

.merlin, _oasis, lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap/bap_project.mli, lib/bap_disasm/bap_disasm.ml, lib/bap_disasm/bap_disasm.mli, lib/bap_image/bap_image.ml, lib/bap_sema/bap_ir.ml, lib/bap_sema/bap_ir.mli, lib/bap_sema/bap_sema_lift.ml, lib/bap_types/bap_attributes.ml, lib/bap_types/bap_types.ml, lib/bap_types/bap_value.ml, lib/bap_types/bap_value.mli, lib/bap_types/bap_vector.ml, lib/bap_types/bap_vector.mli, lib_test/bap_project/test_project.ml, opam, opam.deps, src/bap_mc/bap_mc.ml, src/readbin/bap_main.ml
Values of type value are now serializable, pretty-printable and
comparable (in short they are now first class). That allows us
to add them as attributes to IR terms. Now we can attach to terms
arbitrary values.
=> Extend Value module and added attributes to terms.

README.md, bapdoc.ml, lib/bap/bap.mli, lib/bap_types/bap_value.ml, lib/bap_types/bap_value.mli
This PR extends documentation of IR.
It also fixes `bapdoc` compatibility issues, turns on code highlighting
and removes ubiquitous `Bap.Std.` in generated documentation.
And it also exposes type equality witness for the `'a tag`.
=> Update docs, fix bapdoc, add type equality witness

src/readbin/.merlin, src/readbin/bap_main.ml, src/readbin/byteweight_main.ml, src/readbin/cmdline.ml, src/readbin/find_starts.ml, src/readbin/find_starts.mli, src/readbin/fsi_benchmark_main.ml, src/readbin/func_start.ml, src/readbin/func_start.mli, src/readbin/ground_truth.ml, src/readbin/ground_truth.mli, src/readbin/ida.ml, src/readbin/ida.mli, src/readbin/options.ml, src/readbin/symbols.ml, src/readbin/symbols.mli
This pull request aims to resolve issue #132 by adding --dump-symbols option for bap_main, and changing the interfaces in Module `symbols`.
=> Adding --dump-symbols option for `bap`, and changing the interfaces in Module symbols

_oasis, lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap/bap_project.mli, src/readbin/bap_main.ml
This PR provides two new features (and revokes one).
1. Passes can now specify dependencies as list of names.
The dependencies will be run before the pass.
2. [run_passes] now will auto-load plugins. I.e., now it is sufficient
just to specify the sink pass, all dependencies will be properly
resolved and loaded.
3. Now it is not possible to register the same plugin (or different
plugins with the same name).
=> Introduce pass dependencies and autoloading.

lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap_disasm/bap_disasm.ml, lib/bap_image/bap_image.ml, lib/bap_image/bap_image.mli, lib/bap_image/bap_image_std.ml, lib/bap_image/bap_llvm_loader.ml, lib/bap_image/bap_native_loader.ml, lib/bap_image/image_backend.ml, lib_test/bap_image/test_image.ml, python/__init__.py, python/bap.py, src/readbin/bap_main.ml, src/readbin/byteweight_main.ml, src/server/manager.ml, src/server/manager.mli, src/server/rpc.ml, src/server/rpc.mli, src/server/server.ml
This PR forfeits our previous awkward naming scheme, where segments
were sections, sections were segments and regions were sections. No need
to understand the above anymore.
Now segments are segments.
Sections are sections.
Symbols are symbols.
For those who adopted the previous scheme, this renaming will do the
following:
```
s/section/segment
s/region/section
s/sym/symbol
```
=> Renaming things.

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_arm_abi.ml, lib/bap_disasm/bap_disasm_symtab.ml, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli, lib/bap_types/bap_types.ml, lib/bap_types/bap_visitor.ml, lib/bap_types/bap_visitor.mli
This PR adds some helpers, that previously can be found only in `Bil`
module to `Stmt` and `Exp` module. For example, there are now three
`fixpoint` operators: `Bil.fixpoint`, `Stmt.fixpoint` and
`Exp.fixpoint`. The same is with `fold`, `iter`, `find`, etc.
It also fixes the wrong naming, `find` is renamed to `exists` and
`find_map` to `find`.
Also some nasty bugs were fixed.
=> Extend and fix BIL helpers.

setup.ml.in
Also, extended the search procedure for mac os x, it will search not
only for macported version, but for all available.
=> llvm_version now defaults to 3.4

CHANGES.md, README.md, _oasis, lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap/bap_project.mli, lib/bap_disasm/bap_disasm_arm_lifter.ml, lib/bap_image/bap_image.ml, lib/bap_sema/bap_ir.ml, lib/bap_sema/bap_sema_lift.ml, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli, src/readbin/bap_main.ml, src/readbin/cmdline.ml
Errors from plugins are now expressed in a more clean way. One can use
functions, that return `Or_error.t` to get the default error handling,
or to catch them itself, to get a full control.
Fixed passing options to plugins. Now the system will load a transitive
closure of dependencies before the command line parsing stage, cleanup
the plugin options from the command line and pass it to the main
utility.
ARM lifter now handles new instruction `svc` it is mapped to a `CpuExn`
statement. Also, slightly changed the printing of the `CpuExn`. It is
now printed with `interrupt` instead of previous `int`. (Much easier to
grep and more readable).
Fixed bug in IR lifter, when fall-through jumps were lost for regular
basic block without jumps at all.
Fixed fixpoint function. For some reason the book …
=> Cleaner error handling and some bug fixes.

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_block.ml, lib/bap_sema/bap_ir.ml, lib/bap_sema/bap_ir.mli, lib/bap_sema/bap_sema_lift.ml, lib/bap_types/bap_exp.ml, lib/bap_types/bap_value.ml
This PR changes representation of a phi node. Previously it was a pair
of a variable and a set of definitions. Now it is a pair of a variable,
and a dictionary `tid => exp`, exactly as in LLVM.
This PR also fixes #238 and resolves #237.
And also prettifies pretty printer.
=> Redesign PHI-node representation.

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_arm_lifter.ml, lib/bap_disasm/bap_disasm_x86_lifter.ml, lib/bap_sema/bap_ir.ml, lib/bap_sema/bap_ir.mli, lib/bap_sema/bap_sema_lift.ml, lib/bap_types/bap_var.ml, lib/bap_types/bap_var.mli, lib/bap_types/bil_piqi.ml, lib/bap_types/type.piqi, src/readbin/bap_main.ml, src/readbin/cmdline.ml
This PR introduces a slight change in `var` representation.
Now variables can be versioned, i.e., a version number can be attached
to a variable to represent the same variable but in different time or
space. This is in particular useful for SSA form. See documentation in
Var module for more information.
Also small changes:
- Fix bug, that was introduced when I fixed #238. Due to the new bug,
some blocks in IR became unreachable.
- BIL lifters now use sameness to compare variables. I.e., `CPU.is_*`
works fine in SSA form.
- Added three new functions to Term module:
- `change` for upsert operation
- `find_exn` because sometimes it can be guaranteed
- `enum` as a synonym to `to_sequence`
- added new option `output` as a synonym to `phoenix`.
This will fix #241.
=> Change Var module implementation.

lib/bap_types/type.piqi, opam, opam.deps
Bitvectors were represented as binary data. Although it worked well
with piqi-to-piqi transformation this work fine, it actually rendered
json and xml formats unusable. This PR will change bitvector to a string
representation.
=> Resolve #254

_oasis, lib_test/bap_image/test_llvm_loader.ml, lwt/core_lwt_container.ml
112.35.00 version of core introduces some breaking changes,
like changing a monad interface, and removing some dependencies.
This PR resolves this issue in a such manner, that it should work
for both - old and newer versions of core.
=> Fix #260 and other compatibilty issues

_oasis, lib/bap/bap.mli, lib/bap_types/bap_bitvector.mli, lib/bap_types/bap_common.ml, lib/bap_types/bap_trie.ml, lib/bap_types/bap_trie.mli, lib/bap_types/bap_trie_intf.ml, lib/bap_types/bap_types.ml, lib_test/bap/run_tests.ml, lib_test/bap_types/test_trie.ml, lib_test/bap_types/test_trie.mli
- Data can be attached to the trie's root (i.e., to an empty key),
this will resolve #271.
- Test suite is added, some bugs were fixed.
- A `walk` algorithm is added, that will fold function over all substrings
of a key. (In fact all other search functions are implemented using
this walk function).
- A family of two new functors is added: Array.Prefix and Array.Suffix,
to create, correspondingly, prefix and suffix tries with array keys.
- Trie.String is now also a family - Trie.String.Prefix and
Trie.String.Suffix.
=> Fixes to trie data structure.

lib/bap_sema/bap_sema_ssa.ml, lib_test/bap_sema/test_ir.ml
A bug was introduced in a process of transforming ssa algorithm to a
graphlib. The renaming procedure was using a wrong block, so that
version numbers moved.
=> Fixed a bug in SSA algorithm implementation.

lib/bap_disasm/bap_disasm_insn.ml
This patch makes it possible to distinguish `nop`s (which provide an empty list for BIL semantics when implemented) and unimplemented instructions by making the unimplemented instructions produce a `Special`.
[Build](https://travis-ci.org/maurer/bap/builds/75508717)
=> Generate a BIL Special when semantics unknown

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_basic.ml, lib/bap_disasm/bap_disasm_basic.mli
There were actually two issues, that played along.
1. The backlog history was unbounded, and if the state is changed after
each byte, they may become very long. Now it is bounded and user
controlled.
2. The other issue is more problematic. It looks like OCaml GC has a
memory leak with lazy values stored inside an array. As for now, the
insns are no more lazy, until we found out a more suitable workaround or
until upstream is fixed.
=> Fix memory issues in disassembler

bapdoc.ml, lib/bap/bap.mli, lib/bap_image/bap_native_loader.ml, lib/bap_types/bap_arch.ml, lib/bap_types/bap_common.ml, lib_test/bap_project/test_project.ml, src/server/server.ml
This PR will fix #290:
```sh
$ echo "0x88,0xb0" | bap-mc --arch=thumb --show-insn
sub sp, #0x20
```
It may also break some code, as it removes wildcard `arm` and `thumb`
architectures, that were previously defaulted to the latest arch. Now
one should provide explicitly `armv7` or `thumbv7`.
`Arch.of_string` function will still understand `arm` and `thumb`
short-cuts defaulting them to `armv7` and `thumbv7` correspondingly.
Big-endian variants of arm and thumb are also fixed.
=> Add support for thumb, make arches more explicit.

lib/bap/bap.mli, lib/bap_image/bap_image.ml, lib/bap_image/bap_memory.ml, lib/bap_image/bap_memory.mli, lib/bap_types/bap_common.ml, lib/bap_types/bap_size.ml, lib/bap_types/type.piqi
See #126 and #130; this restores support for lifting a variety of memory-related SSE instructions (e.g. `f3 0f 7f 04 38 movdqu %xmm0,(%eax,%edi,1)`), while breaking less stuff than #126.
=> Add `r128 and `r256 sizes

lib/bap_disasm/bap_disasm_x86_lifter.ml
Small change earlier was accidentally creating Move(1-bit flag, 32-bit Unknown) BIL for `div` instructions (also maybe `bsf`).
=> fix div instruction

python/bap.py, src/server/server.ml
Server should still respond when client does not supply id. E.g. `curl --data "{\"init\": {\"version\": \"0.1\"}}" 127.0.0.1:8080` does not get a response.
Client should break on successful connection.
=> Small client/server fixes. 

lib/bap/bap.mli, lib/bap_types/bap_value.ml, lib/bap_types/bap_value.mli
This PR introduces a parallel matching for values of type [value].
So that if you have a value, and you want to pattern match it against
several tags, then now you can use the following syntax:
```ocaml
let lift v = Value.Match.(begin
switch v @@
case memory_load   (fun x -> `Load x)  @@
case memory_store  (fun x -> `Store x) @@
case register_read (fun x -> `Read x)  @@
default (fun () -> `Unknown)
end)
```
where `memory_load`, `memory_store` and `register_read` a values of type
`'a tag`. Of course, `'a` is totally polymorphic and is not unified
between branches (i.e., you can use `int tag`, `string tag` in the same
`switch` expression).
=> Parallel matching for values.

_oasis, lib/bap/bap.mli, lib/bap_disasm/bap_disasm_rec.ml, lib/bap_disasm/bap_disasm_shingled.ml, lib/bap_disasm/bap_disasm_shingled.mli, lib/bap_disasm/bap_disasm_shingled_lifter.ml, lib/bap_disasm/bap_disasm_std.ml, lib/bap_disasm/bap_insn_aliasing.ml, lib/bap_disasm/bap_transmat_normal.ml, lib/bap_disasm/bap_transmat_normal.mli, lib_test/bap_disasm/test_disasm.ml, lib_test/bap_disasm/test_training.ml
This commit adds a shingled disassembler and lifter
and makes it available under
Bap.Std.Disasm_expert.{Shingled, Shingled_lifter}.
It works in a Continuation Passing Style as much as
realistically possible, and utilizes a single pass
analysis to traverse possible code sequences down to
known data, wherein such can be sheered off. Additionally,
the skeleton implementation of a training corpus facility
to build a probabilistic finite state machine for future
higher accuracy selections of possible code sequences, and
heurism facilitation is provided. Lastly, a lifter module
grants users an easy ability to drive the shingled
disassembler as either a graph sheering capability or a
simple conservative pass. Execution speed is expected to
be all but linear save for the usage of memmap, which …
=> Add PFSM assisted shingled disassembler, lifter and unit tests

lib/bap_types/bap_graph.ml
`succs` and `preds` didn't take into account filtered edges.
=> Fixes issue with Filtered graph.

lib/bap/bap.mli, lib/bap_types/bap_attributes.ml, lib/bap_types/bap_biri.ml, src/readbin/text_tags.ml
This is a small technical update. Other than few bug fixes this and
there it brings a new feature: ansi color tags.
Ansi colors
===========
We now have two new tags: `foreground` and `background`. They can be
used to add attributes to IR terms. The pretty printing function of
this values will print corresponding color in ANSI escape codes. So,
the only thing that you need is to mark you term with some color, e.g.,
```ocaml
Term.set_attr t foreground `green
```
or
```ocaml
Term.set_attr t background `red
```
And then if you enable attribute printing, you will see colors, if your
terminal supports this. Just in case if you forgot how to enable
printing attributes a gentle reminder: use `--emit-attr` option, like
this,
```
bap --emit-attr=foreground
```
to get a colored foreground, or,
``` …
```
=> Add ansi color tagging, fix few bugs.

lib/bap_types/bap_value.ml
This PR allows to introduces new tags in plugins and pass values
of the specified tag between two different plugins.
Previously it wasn't possible, since a module that defines a tag
was evaluated per each plugin, and a failure exception was thrown
after the first evaluation, stating that the tag value is already
registered.
This PR fixes this in the following way. On a first registration
we store the provided module as well as freshly create tag value
in the info data structure. On consequent registration we look at
the type info table and if we find the same module as a user is
trying to register then we're returning a stored tag, otherwise
we bail out with an error. Of course, OCaml type system will not
allow us to extract a tag value from monomorphic table, so here
we use dark magic, …
=> Allow to introduce new tag values in plugins.

lib/bap/bap.mli, lib/bap/bap_load_plugins.ml, lib/bap/bap_plugin.ml, lib/bap/bap_plugin.mli, lib/bap/bap_plugins.ml, lib/bap/bap_plugins.mli, lib/bap/bap_project.ml, lib/bap/bap_project.mli, src/readbin/bap_main.ml, src/readbin/cmdline.ml, src/readbin/options.ml
This PR introduces some breaking changes, so read carefully.
The PR further decouples the notion of a plugin and a pass, as well as
separates a process of loading a plugin from its execution.
A plugin, as it was always been, is a dynamically linked library, that
can be loaded by a bap fronted to perform some side-effectfull
computation (usually to register itself in some plugin extension
point).
TL;DR
=====
1. use `-l<file-name>` to load a plugin
2. use `--<pass-name>` to run a pass.
Loading plugins from command line
=================================
Previously the `-l` option was used to load a plugin, that should be a
program pass (or analysis in other words) and then executes it. Now this
option only loads the plugin (that can be any plugin), but doesn't
execute it. To run a pass with …
=> Refine plugin system

lib/bap/bap.mli, lib/bap_disasm/llvm_disasm.cpp
Options can be passed to the backend using environment variable
`BAP_LLVM_OPTIONS`. To get the option list use: BAP_LLVM_OPTIONS="-help"
Currently there're only:
```
OPTIONS:
-help                            - Display available options (-help-hidden for more)
-mc-x86-disable-arith-relaxation - Disable relaxation of arithmetic instruction for X86
-version                         - Display the version of this program
-x86-asm-syntax                  - Choose style of code to emit from X86 backend:
=att                           -   Emit AT&T-style assembly
=intel                         -   Emit Intel-style assembly
```
With the most interesting option `-x86-asm-syntax`, that allows to
switch between `att` and `intel` syntax. (Actually this is the main
reason to add this mechanism, as it …
=> Allow to pass options to LLVM backend.

opam
We use `Bigstring.write_bin_prot`, which is not present in our previous
lower bound.
=> Bump core_kernel minver

.travis.yml
This caches the contents of the `~/.opam` folder which should speed up the build by skipping rebuild of dependencies when unnecessary. Compare:
[No Cache](https://travis-ci.org/BinaryAnalysisPlatform/bap/builds/103706830) / [Cache](https://travis-ci.org/maurer/bap/builds/103887970)
Oddly, no speedup is observed here, but I am tempted to chalk that up to the immense variability of the time used to download components. It might also be possible with better understanding of the test script you're using to cause the fetched software to be cached as well.
=> Enable caching of built deps

.merlin, _tags.in, lib/bap/bap.mli, lib/bap/bap_install_printers.ml, lib/bap/core_printers.ml, lib/bap_build/bap_build.ml, lib/bap_disasm/bap_disasm_std.ml, lib/bap_dwarf/dwarf_input.ml, lib/bap_image/bap_fileutils.ml, lib/bap_image/bap_memmap.ml, lib/bap_image/bap_memmap.mli, lib/bap_image/bap_table.ml, lib/bap_image/bap_table.mli, lib/bap_types/bap_attributes.ml, lib/bap_types/bap_vector.ml, lib/bap_types/bap_vector.mli, lib/graphlib/graphlib.mli, lib/graphlib/graphlib_graph.ml, lib/regular/regular.mli, lib/regular/regular_seq.ml, lib/regular/regular_seq.mli, lib_test/bap/run_tests.ml, lib_test/bap_dwarf/run_tests.ml, oasis/bap, oasis/common, oasis/src, opam/opam, tools/baptop, tools/postinstall.ml, tools/ppx-bap
This PR relies on a new and not yet released feature of OCaml compiler,
an ability to install polymorphic printers. Long story short, now when
you create a map, or set, etc, they will be printed, using installed
pretty printer instead of say that they are <poly>. I've installed
printers for all polymorphic types of bap and core_kernel.
also added ppx-bap tool and fixed few small issues
=> Added polymorphic printers

myocamlbuild.ml.in, opam/opam
1. Add a small hack, that will add `-predicates` flag to `ocamldep`.
Without the flag, `ocamldep` will try to fallback on `ppx`
executable, that might not be installed, if an old version of opam is
used.
2. Used `make uninstall` in oasis. It looks like that new opam is clever
enough to figure out that we need the source tree to remove it. In any
case it would be better to switch to opam-install for installation and
uninstallation.
=> make installation more robust

oasis/traces
Bap_trace_id module wasn't mentioned in oasis file, and this caused an undefined module error while linking with bap-traces library.
=> added lost module Bap_trace_id

lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap/bap_project.mli, plugins/dump_symbols/dump_symbols_main.ml, src/.merlin, src/bap_main.ml, src/bap_options.ml, src/bap_plugin_loader.ml, src/bap_plugin_loader.mli
Now it is possible to instruct BAP to run pass automatically,
without requiring a user to pass an explicit `--<pass>` on the
command-line. This is useful in at least two cases:
1. If the pass implemented there is no obvious reason not to run it,
so everyone will just pass the option to run it everytime they run
bap.
2. With autoload option it is possible to design more complex
command-line interfaces.
The order of executing of autorun passes is unspecified, unless there is
a dependency between them.
=> Add autoload option to pass

lib/bap_bundle/bap_bundle.ml
Inserting a file with a compound path didn't work.
=> Fix a bug in bap_bundle.

_tags.in, myocamlbuild.ml.in
This should help to link programs when old opam is used,
that doesn't install libexec part of the package, and
resolve #362.
=> Pass predicate(ppx_driver) to the link phase

lib/bap_plugins/bap_plugins.ml, lib/bap_plugins/bap_plugins.mli, src/bap_main.ml, src/bap_plugin_loader.ml
This PR will make a plugin loader more robust to a malicious user. It
will not fail if a plugin is not a plugin, or if it can't be load. It
will print a warning and continue. In a verbose mode it will print an
extended error message.
This will fix #351 and partially resolve #353.
=> robust plugin loader

lib/bap_image/bap_image.ml, plugins/llvm/llvm_binary.hpp
TL;DR
-----
No more IDA. Ok, at least on ARM. This is a hacky support for resolving
PLT entries, that works at least on ARM ELF, i.e., on our most favorite
targets. Support for other targets might be added later, but there are
problems.
Implementation details
----------------------
If an undefined symbol has a value, then use it as an address.
Since the value size is a not a size of a plt entry, but a size of the
real symbol, that would be loaded (at least for elf-arm), a hack is used
to hardcode the size to 8 bytes.
This will not work for x86-64, since the value is usually zeroed by the
elf64-x86-64 backend. In fact, only for elf64-x86-64 backend there are
36 different kinds of relocations, each giving their own meaning to the
entries in the symbol table. And each backend define its own …
=> resolve PLT entries

lib/bap_plugins/bap_plugins.ml
Read packages written in core now delayed until the first load.
Previously, it was initialized at the library link time, that was ok
when we compiled from a trunk, but after we split the libraries, it
stated to lead to segfaults, since only packages written in the bap-std
package were taken into account.
=> Delayed plugin initialization

.merlin, lib/bap_disasm/bap_disasm.ml, lib/graphlib/graphlib.mli, lib/graphlib/graphlib_graph.ml, lib/graphlib/graphlib_graph.mli, lib_test/bap/run_tests.ml, lib_test/bap_types/test_graph.ml, opam/opam
This will fix #372. The problem wasn't in the disassembler itself,
it was in a function that merges graphs from different segments. I
repeated an error, that I did at least three times so far -- merged
only edges and forgot about the nodes. Since `main` subroutine in the
example didn't have any incoming or outcoming edges, it wasn't added.
As a penance (and to prevent myself from repeating this error), I added
two new functions to `Graphlib` - `union` and `inter`, that performs
graph union and graph intersection operation.
Moreover, I've noticed, that tests were disabled, so last dozen or so
PR's were actually untested (just compiled). This PR also fixes this,
and adds tests for newly introduced operations.
=> Fix segment merging in the disassembler

plugins/propagate_taint/.merlin, plugins/propagate_taint/propagate_taint_main.ml
This PR adds an extensible DSL for specifying marking schemes into the
taint propagation framework. This DSL provides a mechanism to specify
what to mark, and with which attribute. This PR makes the framework more
usable on its own, and less dependent on Saluki. Here is an excerpt from
the man page:
Although the pass itself doesn't perform any analysis it can mark terms
with attributes. Terms are marked according to a marking scheme
specified with --mark-scheme=SCHEME or --mark-scheme-file=FILE. Each
entry of the FILE, or SCHEME argument must conform to the following
grammar:
SCM    ::= (PREDS MARKS)
PREDS  ::= PRED | (PRED1 .. PREDn)
MARKS  ::= MARK | (MARK1 .. MARKn)
MARK   ::= TAG  | (TAG VALUE)
PRED   ::= "visited" | "has-seed" | "has-tainted-regs"
| "has-tainted-ptrs" | "has-taint" …
=> A DSL for term marking

.merlin, plugins/api/api_main.ml
For discussion. Api currently adds the header file to the database (zip)
without checking that it parses correctly first. So if you give it a file that
doesn't parse, it will try to use this broken file every time. Since there is
no easy way to remove the header (that I found), I just add an extra option
which will let you use a header file without using the add feature.
Also adds camlzip to .merlin
=> Add "use file" option to api plugin

lib/arm/arm_lifter.ml, lib/bap/bap.mli, lib/bap_disasm/bap_disasm_insn.ml, lib/bap_disasm/bap_disasm_reconstructor.ml, lib/bap_sema/bap_sema_free_vars.ml, lib/bap_sema/bap_sema_lift.ml, lib/bap_sema/bap_sema_ssa.ml, lib/bap_types/bap_biri.ml, lib/bap_types/bap_biri.mli, lib/bap_types/bap_bitvector.mli, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli, lib/bap_types/bap_ir.ml, lib/bap_types/bap_ir.mli, lib/bap_types/bap_types.ml, lib/bap_types/bap_visitor.ml, lib/bap_types/bap_visitor.mli, lib/graphlib/graphlib_regular.ml, lib/microx/microx_concretizer.ml, plugins/phoenix/phoenix_helpers.ml, plugins/propagate_taint/propagate_taint_main.ml
This PR introduces some breaking changes described in the Breaking
Changes section. See also corresponding PR to the bap-plugins
repository, that updates to this change.
Summary
-------
This PR adds the following features:
1. Term.visitor class
2. Term.mapper class
3. Three higher-order morphisms:
- Term.switch
- Term.proj
- Term.cata
4. Splits Bil.visitor into:
- Exp.visitor
- Stmt.visitor
5. Splits Bil.mapper into:
- Exp.mapper
- Stmt.mapper
The `Term.visitor` class performs a deep visiting of the program in the
IR. It inherits `Exp.visitor`, so you can destruct your program to the
smallest possible atoms. The same is true for `Term.mapper`.
The `Term.switch` is used for pattern matching. `Term.proj` and
`Term.cata` are special cases of switch, that allow to omit some
branches.
All …
=> IR visitor, mapper and higher-order morphisms

lib/bap/bap.mli, lib/bap_types/bap_ir.ml, lib/bap_types/bap_ir.mli, lib/microx/microx_concretizer.ml, lib/microx/microx_concretizer.mli, lib/microx/microx_conqueror.ml, plugins/api/api/posix, plugins/api/api_main.ml, plugins/callsites/callsites_main.ml, plugins/propagate_taint/propagate_taint_main.ml, plugins/propagate_taint/propagator.ml, plugins/propagate_taint/propagator.mli, plugins/taint/taint_main.ml
This PR includes several improvements and bug fixes spread across
the code base, united by the main goal - improve taint propagation
framework. It is also found a necessary base for the upcoming movement
of Saluki to the new framework.
Main contribution
-----------------
It was observed, that a concretization to a single value will lead to
unwanted aliasing between arbitrary pointers. Consider the following
example:
```
000001dc: R0 := strcpy_dest
0000016d: R3 := mem[R11 - 0x34:32, el]:u32
```
Here `*strcpy_dest` and `*(R11-0x34)` a both unknown and will have the
same value. As a result `R0` and `R3` will point to the same memory
cell.
Note - this problem manifests itself with tainted pointers more often,
than with tainted immediates, mostly because for a tainted immediate
value we …
=> better taint propagation

lib/regular/regular.ml, lib/regular/regular.mli, lib/regular/regular_cache.ml, lib/regular/regular_cache.mli, lib/regular/regular_data_intf.ml, plugins/cache/cache_main.ml, plugins/ida/ida_main.ml, plugins/propagate_taint/propagate_taint_main.ml, src/bap_main.ml
This PR makes cache digests abstract. This will prevent users from
creating bad digests. As a compensation it provides an interface to
build digests. The interface uses variadic functions with `format`
parameters.
=> abstract cache digest

lib/bap/bap.mli, lib/bap_sema/bap_sema_taint.ml, lib/bap_types/bap_ir.ml, lib/bap_types/bap_ir.mli, oasis/propagate-taint, plugins/api/.merlin, plugins/api/api_main.ml, plugins/callsites/callsites_main.ml, plugins/propagate_taint/propagator.ml, plugins/taint/taint_main.ml, plugins/warn_unused/warn_unused_main.ml
This PR is a bunch of fixes and reification, that in sum
leads to a better (more accurate) taint propagation and
analysis.
Move some attribute to arg module
---------------------------------
Some GNU attributes, that are defined on a function level, are actually
should be assigned to attributes. This attributes, are often use some
number to point on a positional parameter, like `format(printf,1)` show
that first parameter is a printf format string. Now, we attach such
arguments not to the function, but to the argument of subroutine. The
following attributes are affected:
- alloc_size
- format
- nonnull (new)
- restrict (new - in fact it is type qualifier)
- warn_unused (previously known as warn_unused_result)
Also three new attributes are added:
- precondition
- invariant
- postcondition …
=> more accurate taint propagation

lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap/bap_project.mli, lib/bap_bml/bap_bml.ml, lib/bap_bml/bap_bml.mli, lib/bap_disasm/bap_disasm_basic.ml, lib/bap_sema/bap_sema_taint.ml, lib/bap_trace/bap_trace_events.ml, lib/bap_types/bap_attributes.ml, lib/bap_types/bap_common.ml, lib/bap_types/bap_ir.ml, lib/bap_types/bap_ir.mli, lib/graphlib/.merlin, plugins/map_terms/.merlin, plugins/map_terms/map_terms_main.ml, plugins/propagate_taint/propagate_taint_main.ml, plugins/warn_unused/warn_unused_main.ml
The marking infrastructure is moved away from the taint propagation
pass. Now we have a full fledged extensible term mapping DSL. But before
this few other changes (breaking changes are marked with `*`):
Don't warn about unvisited terms
--------------------------------
Resolves #398.
Removed term marking from propagate taint plugin*
------------------------------------------------
Now it is responsible only for propagating taint. It will mark
unconditionally terms with `visited`, `tainted-{reg,ptr}[s]`
attributes.
* This may break your scripts relying on `--propagate-taint-mark-*`
options that are no longer available. See below for a new `map-terms`
pass.
Renamed attribute names*
-----------------------
substituted underscore with a dash. We will stick to this convention,
starting from …
=> spill out marking from the propagate taint plugin

lib/bap/bap.mli
added lost `typeid` function from `Value` module
=> added lost typeid function

oasis/objdump, plugins/objdump/.merlin, plugins/objdump/objdump.ml
objdump output will be parsed to identify function starts.  The path to
objdump is specified either via a command line option, or the plugin
will search your path for `objdump` (default in general) or
(`x86_64-elf-objdump` | `i386-elf-objdump`) (default in macports)
=> Adds objdump parser as a symbolizer

.travis.yml, lib/bap/bap_project.ml, plugins/ida/ida_main.ml, plugins/llvm/llvm_binary.hpp, plugins/objdump/objdump_main.ml, src/bap_main.ml
There were few bugs in the LLVM, all in the upstream. This
PR fixes them on our side.
* Address of the segment was incorrect
* Address of symbol was incorrect
* Size of symbol was incorrect
The first issues was due to the use of the relative virtual address,
instead of virtual. They are fixed by adding the image base address.
The latter issue was quite funny. The algorithm that calculated address
in llvm was = "subtract symbol address from section size" (sic). As an
excuse the author wrote a comment "FIXME: Return the correct size."
Indeed, it was quite hard to get the correct size, as the correct
algorithm is quadratic.
But now we can discover symbols from PE32, even without usage of
external tools like IDA or objdump.
Two other bugs were:
1. objdump plugin didn't work for 32-bit …
=> Fix PE32 support and few bug fixes.

lib/bap_build/bap_build.ml
It was used to enable ppx_inline tests in plugins, but it conflicts
with other ppx extensions.
=> Disable usage of ppx-jane rewriter in bapbuild

_tags.in, configure, myocamlbuild.ml.in, oasis/common, oasis/common.files.ab.in, oasis/common.ocamlbuild.ml.in, oasis/common.setup.ml.in, oasis/common.tags.in, setup.ml.in, tools/cat.ml, tools/cat.mli, tools/collect.ml, tools/oasis_sections.ml
This PR allows plugins to specify their own
configuration parameters, ocamlbuild plugins, tags,
and interpolation files.
Details
-------
File `oasis/<plugin>.setup.ml.in` will be copied to a final `setup.ml`,
and can contain arbitrary ocaml code that will be executed at
configuration time. A handful shortcuts are provided, e.g.,
`add_variable` function will add a configuration variable.
File `oasis/<plugin>.files.ab.in` can contain a list of files, where
substitution will be performed. It can contain variables of the form
`$<var>` where `<var>` is one of the variables set in the configuration
time (see `setup.data` for a full list).
Files `oasis/<plugin>.tags.in` and `oasis/<plugin>.ocamlbuild.ml.in`
will end up in `_tags` and `myocamlbuild.ml` correspondingly.
Also, all `ml` files in the …
=> extended configuration options for plugins

.gitignore, lib/bap_ida/bap_ida.ml, lib/bap_ida/bap_ida.mli, lib/bap_ida/bap_ida_config.ml.ab, lib/bap_ida/bap_ida_scripts.mli, oasis/ida, oasis/ida.files.ab.in, oasis/ida.setup.ml.in, plugins/ida/ida_main.ml, src/find_starts.ml, src/find_starts.mli, src/func_start.ml
Now we resolve ida on configuration time. And it is impossible
to install bap_ida library, without ida being installed on the
system. A comprehensive support from the opam side is added as
a separate push to the opam-repository.
=> Move --ida-path option to the configure script

.gitignore, configure, lib/bap_ida/bap_ida.ml, oasis/objdump, oasis/objdump.files.ab.in, oasis/objdump.setup.ml.in, plugins/objdump/objdump_config.ml.ab, plugins/objdump/objdump_main.ml
Alike as IDA, objdump now expects a path to objdump to be passed
at configuration time. A corresponding `conf-binutils` package will
be added to opam and the dependency between them will be established.
As a consequence, `bap-objdump` package will not be installable, if
there is no objdump program, moreover, a corresponding external
dependency will be added and thus installed via depext.
=> detect binutils installation at configuration time

oasis/objdump
it was using IDA flag instead of objdump as a compilation condition.
=> Fix a typo in oasis/objdump

opam/opam
Since someone may use this file for obtaining bap, I've added an
integration with `conf-ida` and `conf-objdump` packages. These
packages are only available in our opam-repository, so don't forget to
add it. To get working ida or objdump plugins on your box, make sure
that these packages are installed. To get proper objdump on your linux
or mac box, invoke `opam depext conf-objdump`.
Note -- after this PR is merged, ida and objdump will become unavailable
if conf-ida and, correspondingly, conf-objdump are not installed.
=> added conf-{ida,objdump} dependency to opam/opam

lib/bap/bap_project.ml, lib/bap_ida/bap_ida.ml, lib/bap_ida/bap_ida.mli, plugins/ida/ida_main.ml
With the new loader it is possible to load all files, that are
supported by ida, including:
- kernel modules (closes #345)
- object files (closes #402)
Note - the default loader is still llvm, to switch to the ida loader,
pass --loader=ida to bap.
This PR also fixes a bug in the project construction function, we left
out the code segment in the final project.
Also, this PR adds support for writing ida scripts in IDC, and rewrites
symbols command in IDC.
=> add ida powered file loader

plugins/ida/ida_main.ml
an architecture was incorrectly recognized.
=> fix a bug in the ida loader

lib/bap/bap.mli, lib/bap_bml/bap_bml.ml, lib/bap_types/bap_attributes.ml, plugins/emit_ida_script/emit_ida_script_main.ml, plugins/map_terms/map_terms_main.ml
Make sure `emit-ida-script` plugin can use all colors that BAP supports
Add gray to the list of colors supported by BAP
=> Color updates

.gitignore, oasis/ida-plugin, oasis/ida-plugin.files.ab.in, oasis/ida-plugin.setup.ml.in, plugins/ida/python/bap_propagate_taint.py, plugins/ida/python/bap_propagate_taint.py.ab
This PR adds an IDA Python Plugin to be able to select any arbitrary line in Graph/Text view in IDA, and be able to taint that line and propagate taint information and see it visually.
- Shift-A : Equivalent to `--taint-reg` in BAP
- Ctrl-Shift-A : Equivalent to `--taint-ptr` in BAP
The plugin is loaded automatically into IDA for usage, after installation.
```
./configure --prefix=`opam config var prefix` --enable-ida-plugin
make && make reinstall
```
Then, just select some line by placing your cursor over it in IDA, and press Shift-A or Ctrl-Shift-A.
- "Nasty" Yellow : Taint source
- "Affected" Red : Lines that got tainted
- "Ignored" Gray : Lines that were not visited by propagate-taint
- "Normal" White : Lines that were visited, but didn't get tainted
=> IDA Python Plugin to propagate taint

plugins/ida/python/bap_propagate_taint.py.ab
Previously, the `bap_propagate_taint` plugin was actually just a script that ran on startup. It was not technically an "IDA Plugin".
This PR fixes the code to wrap it into a class derived from `idaapi.plugin_t`, along with some extra code to make sure that the plugin stays loaded from start of session to end of it.
=> Use correct methodology for bap_propagate_taint plugin

lib/bap_traces/bap_trace.ml
The Trace.filter_map was relying on a mapper function,
that were never applied. Should be fixed now, although
the design is still rather fragile.
=> fix filter_map function in trace

lib/arm/arm_lifter.ml, lib/arm/arm_types.ml, python/arm.py
I noticed issue #117 which said that the ARM lifter doesn't handle `mov pc, lr`, so I decided to look into the ARM lifter. Here's a PR that adds MOVPCLR to the lifter.
---
Since I've never written code for a lifter before, please let me know if I made any mistakes (or any style errors etc), and I will correct them.
---
Running the following code:
```bash
echo '0e f0 a0 e1' | bap-mc --arch=arm --show-insn=pretty --show-bil=pretty --show-bir=pretty
```
We get the output as
```
MOVPCLR(0xe,Nil)
{
jmp LR
}
00000004: 
00000005: return LR
```
=> Add MOVPCLR to the ARM Lifter

oasis/ida, oasis/ida-plugin, oasis/ida-plugin.setup.ml.in, opam/opam
This PR restructures IDA Plugins in BAP to move the rooter, symbolizer and reconstructor into `bap-ida`, and keep the rest of the plugins in `bap-ida-plugins` to remove the `bap-ida` dependency. A further PR that I'll be making in the [BAP opam repository](https://github.com/BinaryAnalysisPlatform/opam-repository) will fix up the build process in opam.
+ Users can now use BAP along with IDA Demo (after [installing IDA Python onto it](https://gist.github.com/jaybosamiya/951193ae774dfc127b513a93795a46c7))
+ `bap-ida` now means "all integrations for BAP with IDA (that need IDA Pro)"
+ `bap-ida-plugins` now means "BAP/IDA plugins which work with both IDA Pro and IDA Demo"
=> Restructure IDA Plugins

.travis.yml
In Travis builds, to prevent issues with opam messing up with the constraints (as we noticed recently), we can use the recommended external dependency solver `aspcud`. This PR adds it.
=> Add aspcud to Travis build

plugins/ida/python/bap_propagate_taint.py.ab, plugins/ida/python/propagate_taint_bap_hexrays.py
This PR adds docstrings (following PEP257) to both IDAPython plugins. It also ensures that they follow PEP8. Additionally, it makes some members of both classes private, since they are not expected to be called directly.
@maverickwoo thanks for letting me know about PEP257 :)
=> PEP Standardization and Documentation for IDAPython Plugins

lib/bap_ida/bap_ida.ml, oasis/ida, oasis/ida-plugin
Newer versions of IDA have deprecated `get_func_name` but older versions don't have `get_func_name2`. This PR allows for using the latest available one among the two.
This PR also fixes some `oasis` naming and description.
=> Take care of older versions of IDA

plugins/ida/python/bap_propagate_taint.py.ab, plugins/ida/python/bap_utils.py, plugins/ida/python/propagate_comments_bap_hexrays.py, plugins/ida/python/propagate_taint_bap_hexrays.py, plugins/ida/python/simpleline_modifier_hexrays.py
This PR does quite a few changes:
+ Add a `bap_utils` library for usage in IDAPython
+ This adds functions like `sexp2list`, `list2sexp`, `cfunc_from_ea` etc, which are extremely useful when writing plugins for IDA, especially for standardizing to using s-expressions.  
+ This also adds a `DoNothing` plugin which can be used to build further libraries, or for making abstract plugins (used later)
+ Add the `SimpleLine_Modifier_Hexrays` abstract base class plugin which is useful  for implementing HexRays (decompiler) plugins by abstracting away a large part of the implementation details
+ Refactor the `BAP_Taint_Pseudocode` plugin to use the abstract base class `SimpleLine_Modifier_Hexrays`.
+ Add a Hex-Rays plugin to propagate BAP comments from Text/Graph View to pseudocode view
+ Ensure …
=> Plugin for Hex-Rays Decompiler (BAP comments + abstract base plugin + refactor)

plugins/ida/python/bap_bir_attr.py, plugins/ida/python/bap_propagate_taint.py, plugins/ida/python/bap_utils.py.ab
This PR adds a plugin to IDA that
+ Allows execution of arbitrary (user-supplied) BAP commands/plugins
+ Pulls arbitrary (user-supplied) BIR attributes into IDA as comments
This PR leverages changes made in PR #449 to ensure that BAP gets the latest symbols as well, using `run_bap_with(argument_string)` :snake: 
+ Shift-S : Open up a window to accept arbitrary BAP commands, and select arbitrary BIR attributes to output to IDA comments
The plugin is loaded automatically into IDA for usage, after installation.
The following tests help demonstrate this plugin's use:
Args to pass to BAP: `--taint-reg={screen_ea} --taint --propagate-taint`
BIR Attributes (comma separated): `tainted-reg, tainted-regs`
Args to pass to BAP: `--saluki`
BIR Attributes (comma separated): `comments`
Note: This …
=> BAP_BIR_Attr IDA Python Plugin

lib/microx/microx_conqueror.ml, lib/microx/microx_conqueror.mli
The backtracking point was registered on the entry to a block,
as a result, when we were backtracking all updates to the context
made in the last block were ignored.
A better way would be to store the context just before the first
jump. To simplify the implementation we will store context actually on
every jump (since usually there one or two jumps on a block, this
wouldn't have a big impact). Also, for performance consideration, an
associative list was substituted with a real Tid.Map.
=> fix microx backtracking

.travis.yml
Similar to #333 by @maurer, this caches the contents of the `~/.opam` folder which should speed up the build by skipping rebuild of dependencies when unnecessary.
#333 was reverted in https://github.com/BinaryAnalysisPlatform/bap/commit/93ee72c0768a9a3692e48e599f1a72431d129e58 because, as @ivg said, sometimes bap would get cached as well. This PR takes care of that by removing bap before placing things into cache. This ensures that the dependencies are stored, but bap is not.
*Note:* It might take a while after this PR is merged for caching to start showing significant improvements (since the merge will cause the cache to be generated, and subsequent PRs/commits will use the cache whenever possible)
=> Enable caching of built dependencies

lib/bap/bap.mli, lib/bap/bap_self.ml, lib/bap/bap_self.mli
I just _had_ to make a reference to that iconic movie here. :zap: :metal: :zap:
This PR is one from a series of PRs that will transition our `Config` interface into being able to work in a much better way. The point is to simplify the interface that plugin developers use for command line parsing. Over time, we aim to consolidate all the information from different plugins and produce a much nicer and more coherent command line parsing structure (compared to the hacky method we had earlier with Cmdliner being used in all plugins).
This PR does the following:
+ Updates the type of `reader` to a record with a `get` function
+ Turns out, the implementation from #468 guaranteed a truly polymorphic `get` function, but the interface did not guarantee it at the time and thus OCaml made it weakly …
=> BAP to the Future | Config update

lib/bap/bap.ml, lib/bap/bap.mli, lib/bap/bap_log.ml, lib/bap/bap_log.mli, oasis/bap-std, src/bap_main.ml, src/bap_mc.ml
Otherwise a standalone program, that lives out of the source tree, will
not have an access to logging and will require a user to re-implement
it.
In order to enable logging in a standalone program use `Log.start`
function.
=> Moved the logger into the library.

lib/bap_plugins/bap_plugins.ml, myocamlbuild.ml.in, oasis/byteweight, oasis/byteweight-frontend, oasis/frontend, opam/opam, src/bap_byteweight_main.ml, src/bap_plugin_loader.ml
Previously it was disallowed, see the big fat warning in the
`oasis/fronted` (removed by this PR).
This PR will now track both internal and external libraries. We leverage
the predicate mechanism of ocamlfind, and for each internal library
`LIB` thatis linked with a host program, we record a predicated
`used_LIB`. Later, we can extract the names of linked libraries and
record them in the registry of linked libraries.
This PR also revives the byteweight frontend, that was broken due to a
dependency on the internal library byteweight (the problem manifested
itself only if it was installed from the source tree, it worked ok from
the opam-repository).
=> Allow a frontend to link with internal libraries.

src/bap_cmdline_terms.ml, src/bap_main.ml
1. rooter and symbolizer now defaults to internal.
2. symbols option wasn't used at all -- fixed.
=> fix symbols,rooter and symbolizer options

lib/bap/bap.mli, lib/bap/bap_self.ml, lib/bap/bap_self.mli, plugins/cache/cache_main.ml, plugins/callsites/callsites_main.ml, plugins/dump_symbols/dump_symbols_main.ml, plugins/emit_ida_script/emit_ida_script_main.ml, plugins/ida/ida_main.ml, plugins/objdump/objdump_main.ml, plugins/propagate_taint/propagate_taint_main.ml, plugins/read_symbols/read_symbols_main.ml, plugins/taint/taint_main.ml, plugins/trace/trace_main.ml, plugins/warn_unused/warn_unused_main.ml
This PR does the following
+ Updates multiple plugins to use the `Config` interface
+ `cache`
+ `callsites`
+ `dump_symbols`
+ `emit_ida_script`
+ `ida`
+ `objdump`
+ `propagate_taint`
+ `read_symbols`
+ `taint`
+ `trace`
+ `warn_unused`
+ Updates the `Config` interface to
+ Allow `param_all` for taking lists through repetition at command line
+ Adds the standard `some` converter
+ Makes `name` a non named-argument in `param`, `flag` to prevent dangling optional argument problem
+ Update `Config` implementation to
+ Account for above changes
+ Ensure that the filtered arguments are passed to a plugin (Note: In future PRs, as we slowly combine information from different plugin config, we will instead be calling `Term.eval` only once globally, rather than once every plugin.)
=> Update multiple plugins to use the Config interface instead of Cmdliner

lib/bap_plugins/bap_plugins.ml
So far the evaluation context was switched just after the plugin loaded
to the context of the host program, and only afterwards the events were
fired. As a result, the `Config.when_ready` evaluated its argument
function under the context of the host program, so the `register_pass`
function was registering passes with the name `bap` instead of the name
of a plugin.
This PR will fix this particular issue, and the callback will be
evaluated at the correct context. But, the issue will fire up again,
when we will switch to the one grammar/one parsing scheme. So we should
think a little bit more about how we can ensure, that events are called
under the proper context.
=> Change the evaluation context of plugins events

lib/bap_c/bap_c_abi.ml
Don't stage the function, as it may evaluate before target support
library is available.
=> fix api stack helper

src/bap_cmdline_terms.ml
We've tried several default values for the rooter:
1. internal
2. the first one
3. nothing
The had their caveats:
1. internal doesn't work at all for stripped binaries, so it
has a very negative user experience, basically bap doesn't
work out of box on anything other than toy examples, compiled
with -g.
2. the first one, is very non-deterministic, it can be `internal`,
so we have the same set of problems as in `1`. It can be any
other and the results are hard to predict.
3. nothing means bap will output nothing unless you specify a rooter,
definitely not an option.
This PR introduces the new default, if no rooter is specified, then
that means, that a user doesn't have any particular preferences, so
we will use all available information, i.e., we will take all registered
rooters and merge …
=> union all rooters if no one is preferred by a user

plugins/ida/bap_ida_service.ml, plugins/ida/ida_main.ml
This PR does the following
+ Improves warning messages shown to user
+ Prevent warning messages related to the `Service` on compilation
+ Prevent possible name clashing of the `ida` and `config` records
+ Remove unnecessary `open`s (artifact of previous implementation)
+ Prevent warning due to `Core_kernel.Std` shadowing `&&`
=> Few warning fixes etc

lib/bap/bap_project.ml
When a raw binary is passed, or when a light loader is used internal
rooter and symbolizer are unable to provide any information. This is an
expected behavior for them and should not be treated as an error.
=> internal symbolizer shouldn't fail

lib/bap/bap.mli, lib/bap/bap_self.ml, lib/bap/bap_self.mli, plugins/cache/cache_main.ml, plugins/dump_symbols/dump_symbols_main.ml, plugins/emit_ida_script/emit_ida_script_main.ml, plugins/propagate_taint/propagate_taint_main.ml, plugins/read_symbols/read_symbols_main.ml, plugins/taint/taint_main.ml, plugins/trace/trace_main.ml
Make the defaults a bit more easier to use. Now, defaults are optional for most converters (which actually hold the defaults now).
For example, one can just say `Config.(param string "x")` instead of the older `Config.(param string "x" ~default:"")`
Fixed up issues that might have come up in #493
=> Config defaults

lib/bap/bap_project.ml
As symbolizers will override each other with the latter having a
precedence on the former.
This fill fix #497.
=> do not create empty symbolizer

lib/bap/bap.mli, lib/bap/bap_self.ml, lib/bap/bap_self.mli
This PR introduces the `Config.doc_enum` function that will make it easier to write documentation for plugins that use enums.
Sample usage:
```
- : ?quoted:bool -> (string * 'a) list -> string = <fun>
- : string = either `a' or `b'
- : string = `a'
- : string = one of `a', `b' or `c'
```
=> Add doc_enum

src/bap_main.ml, src/bap_options.ml
There're several reasons:
1. symbolizer and rooter are orthogonal
2. there is no practical reason to restrict rooter, so the default
behavior is to say `--symbolizer=ida` without concertizing rooters,
i.e., to use all available information.
3. with symbols option it is not possible to implement the all default
option for the rooter, so it will fix #496.
4. the option is fragile and was broken most of its lifetime, mostly
because it breaks the SPOT rule.
=> remove symbols option from the frontend

configure, opam/opam, tools/oasis_sections.ml
This PR allows us to specifically disable certain plugins/features when we enable everything, for example, if we run `./configure --enable-everything --disable-ida`, then it will enable every plugin/feature except for `ida`
All of the issues that were there in the previous PR that tried to do this (i.e. #454) have been handled here. Expansions, quotes, empty strings, strings with spaces -- all are handled now.
All of the following have passed (i.e. work as expected).
+ [x] Without parameters
```
./configure
```
+ [X] With lots of paramenters (including `opam config var conf-binutils:targets` which has spaces)
```
./configure --prefix=`opam config var prefix` --with-cxx=`which clang++` --mandir=`opam config var man` --enable-everything --enable-tests --enable-ida --ida-path=`opam config …
```
=> Allow disabling certain plugins/features when enabling everything

lib/bap/bap.mli, lib/bap/bap_self.ml, lib/bap/bap_self.mli
This PR does the following to extend `Config`:
+ Allows plugins to specify that a `config` `param` is deprecated. The reason for adding this is so that if/when developers decide that a certain option is no longer going to be used, then they can mark it as deprecated for a few releases, along with instructions to the alternative that was added, and then once the users have updated their plugins, these options can be phased out smoothly.
+ This addition prints a helpful warning message anytime the user uses this parameter
+ Plugin developers can also customize the message to point towards a better/alternative usage if they want
+ Help page (i.e. the `--help` manpage) clearly shows the parameter as deprecated
+ Allow plugins to specify synonyms for parameters. This, while discouraged, is …
=> Extending Config

setup.ml.in
Adds support for `llvm-config-3.5+` flags (namely `--system-libs`)
=> llvm-config-3.8 --system-libs

plugins/llvm/llvm_binary.hpp
*** This pull request is independent of LLVM 3.8 support.
• In `plugins/llvm/llvm_binary.hpp`, there is a `Binary` smart pointer that is improperly handled due to the fact that the pointer to the binary has a shorter lifetime than the image.
• To resolve this issue, we can make the binary smart pointer a part of `image`.
=> fix possible use-after-free in llvm_binary plugin

plugins/api/api/c/posix, plugins/x86/x86_abi.ml
This PR resolves several x86 abi issues that were found by a new
testsuite:
1. Currently x86 abi don't know how to pass arrays of unknown sizes.
Different ABI allows to pass them via registers, if certain condition
holds and size is known, if the size is unknown, then they are
usually passed as a pointer. Since, currently the support for x86 ABI
is preliminary I fixed this locally in the `c/posix`.
2. Added ABI autodetection. This is a heuristics that may detect that a
binary has MS ABI. A better approach would be to store the
information about original file format. Knowing that the file is in
PE32 or PE32+ format is a much better heuristic to guess that it is
for Windows.
3. Added demangling for Win32 files.
As a result, now Saluki is able to work on MS binaries out of box, and
even …
=> Resolve x86-abi issues

.gitmodules, .travis.yml, Makefile, opam/opam
This PR will integrate the platform testsuite with Travis CI. Every time a new build is spawned,
the testuite will be checked out and run, after the unit testing. 
This will finally resolve #375
=> Integrate testsuite

tools/oasis_sections.ml
There're some flags that are triggered with enable/disable, that are not
oasis features, e.g., `--enable-tests`, `enable-docs`, etc. I've put
them as a special args, and protected from removing. Kind of crude, but
will work as a quick fix, until we will resolve this properly.
=> This is a quick fix for #521

src/bap_mc.ml, src/mc_options.ml
* Refactor bap-mc tool to conform to our coding and quality standards. 
* Fixerror printing, so that an erroneous instruction now is again properly
highlighted. 
* Renamed `max-insns` command line option to `--only-one`, as this reflects much better what the option is actually
doing. 
* Fixed version number.
* Extended testsuite.
=> Bap mc error reporting

plugins/llvm/llvm_disasm.cpp
The new lookup stategy follows closely llvm-mc implementation. It is
able to find all existing architectures, and systemz, that we weren't
able to use before.
=> Better target lookup in llvm backend

lib/bap_disasm/disasm.cpp, lib/bap_disasm/disasm.h, lib/bap_disasm/disasm.hpp, lib/bap_disasm/disasm_stubs.c, plugins/llvm/llvm_disasm.cpp
LLVM-MC disassembler treats instruction prefixes as separate instruction. In fact, situation is even worse, as several prefixes are sometimes merged into instruction and sometimes it can survive as a standalone. An examples for this is REX prefix. 
In any case, this behavior is very specific to LLVM-MC, and is not conforming to any standard. So a lifter, shouldn't depend or fix this behavior. Moreover, our current lifter, doesn't expect such behavior, and all instructions with prefixes other then REX are handled incorrectly. 
This PR will normalize LLVM behavior with respect to prefixes. They are now glued back to the instruction, and can't ever escape from the disassembler as a separate instruction. 
The testsuite is correspondingly updated.
=> Merge prefixes in llvm backend

src/bap_cmdline_terms.ml, src/bap_main.ml
This PR introduces `-p`, `--pass`, `--passes` as command line options for specifying passes. It does **not** remove `--PASS` though.
The reason that this is done as a quick temporary fix to the code (in a separate PR from #512) is so that the test suite can be updated to work with master (after this is merged) and the transition is smoothened, and we are more confident of the changes.
=> Introduce -p, --pass, --passes

opam/opam
Although the package is optional, we need to add it to opam/opam file,
since it includes a non-optional `make check` call. Another option would
be to make the `check` rule to check the presence of the dejagnu (that
it already does), and ignore the testsuite, if it is not present. But,
it looks like, that such option will only increase the entropy, so I
would better add the package as dependency.
This will resolve #537.
=> add dejagnu dependency

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_basic.mli
Previously a basic disassembler could be only accessed by `with_disasm`
function, that is safe but not very versatile. There is at least one use
case, where the CPS style is not enough, as we may need to have a pool
of disassemblers. For example in bap-server.
This PR adds this functions to the module interface, however they are
discouraged, and `with_disasm` function should be considered whenever
it is possible.
=> publish create/close functions for basic disasm

opam/opam
It looks like that ocurl.0.7.8 doesn't compile on Ubuntu Precise,
although it works fine at least on the Trusty.
=> constraint ocurl version to 0.7.7

setup.ml.in
Fix building with LLVM 3.8
Ensure a space between the outputs of `llvm-config --ldflags` and `llvm-config --system-libs`.
=> Add space before output from --system-libs

lib/bap_build/bap_build.ml, myocamlbuild.ml.in, oasis/common.ocamlbuild.ml.in, oasis/common.setup.ml.in, oasis/ida.setup.ml.in, oasis/llvm.ocamlbuild.ml.in, oasis/llvm.setup.ml.in, oasis/llvm.tags.in, oasis/objdump.setup.ml.in, oasis/piqi.ocamlbuild.ml.in, oasis/piqi.setup.ml.in, setup.ml.in
This PR makes our build system less hackish and, hopefully, more robust. To summarize:
* remove hardcoded llvm flags from the c++ rules (prevented building bap without llvm)
* give each module its own configuration (removes abstraction leaks between modules)
* use tags in the new rules (allows further extension)
* don't panic when llvm-config is not found (indeed why should we)
=> Dehackify cxx and llvm building

lib/bap_traces/bap_trace_events.ml, lib/bap_traces/bap_trace_events.mli
this PR adds pretty printers for next events in `bap-traces`: `timestamp`, `pc_update` and `context_switch`.
=> added pretty printers for some events in bap-traces

.travis.yml, Makefile
This PR introduce two environment variables, `BAP_RUN_TEST` and `BAP_RUN_CHECK`. So users have more control over install process, and all tests and check could be done only with setting this variables to `true`.
=> added two env variables

CHANGES.md, plugins/llvm/llvm_binary.hpp, plugins/llvm/llvm_binary_34.hpp, plugins/llvm/llvm_binary_38.hpp, plugins/llvm/llvm_binary_stubs.c
fix https://github.com/BinaryAnalysisPlatform/bap/issues/571
Although segfault could happen with every type of files, when `llvm` just can't guess a magic, as it is for example given in the issue.
=> fixed segfault with corrupted files

plugins/x86/x86_utils.ml
this expression `Bil.(cast low t (e lsl (n * (int_exp t et))))`
means to take `low t` bits from an `e lsl (n * (int_exp t et))`,
where the expression from the right of `lsl` actually
evaluates to a start bit, where to start extaction. so doing a
left shift and taking low bits is wrong approach
those changes influences on instructions: `PSHUFB` and `PSHUFD`
=> fix an extract function for x86 pshufd/pshufb insns

CHANGES.md, tools/bapbundle.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/381
allows to install/remove bap plugins without specifying extensions, e.g.
`bapbundle install mycode` instead of `bapbundle install mycode.plugin`. 
The latter version is still available. The same is for `update` and `show` commands.
=> use bapbundle with plugins without specifying extension

CHANGES.md, src/bap_main.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/591
`bap` exits abnormally on unknown pass or option, or if file doesn't exist
=> fixed a bap exit status for unknown files, options and passes

CHANGES.md, lib/bap_disasm/bap_disasm_prim.ml, lib/bap_types/bap_exp.ml, lib/bap_types/bap_helpers.ml, lib/regular/regular.mli, lib/regular/regular_bytes.ml, lib/regular/regular_bytes.mli, plugins/llvm/llvm_disasm.cpp, plugins/llvm/llvm_main.ml, plugins/phoenix/phoenix_printing.ml, plugins/print/print_main.ml
fixed https://github.com/BinaryAnalysisPlatform/bap/issues/572
next warnings were silenced with `ocaml.warning` attribute:
```
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
Warning 3: deprecated: Format.pp_close_tbox
Warning 3: deprecated: Format.pp_open_tbox
Warning 3: deprecated: Format.pp_print_tab
Warning 3: deprecated: Format.pp_set_tab
```
next warnings were fixed by code edition
`Warning 57: Ambiguous or-pattern variables under guard`
next warnings weren't fixed and still appears during compilation:
```
Warning 58: no cmx file was found in path for module Clexer, and its interface was not compiled with -opaque
Warning 58: no cmx file was found in path for module Cparser, and its interface was not compiled with -opaque
Warning 58: no cmx file was found in …
```
=> fixed some compilation warnings

CHANGES.md, plugins/api/api_main.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/589
Api plugin stops with `exit 1` and emitting error message.
=> api plugin stops processing in case of failure

CHANGES.md, lib/bap/bap_project.ml, src/bap_main.ml
Allow users to see a backtrace when an exception is thrown
from a pass.
The backtraces are printed for any exceptions, including Failure and
Invalid_arg (i.e., special handlers for these exceptions are disabled).
Resolve #598.
The problem
===========
The pass runner is capturing exceptions that are thrown by a pass, and
rethows it wrapped into the `Pass.Failed` exception. Since the newly
thrown exception is physically (and structurally) different from the
caught exception the backtraces is erased and is not propagated any
further. As a result, the printed backtrace shows only the path from the
pass runner to the entry point of the frontend. That is always the same
and does't really bear any information.
Obstacles
=========
Since the BAP API is fronzen, we can't change the `Pass.error` …
=> propagate backtraces from passes

plugins/phoenix/phoenix_printing.ml, plugins/print/print_main.ml
silence warnings, that were improperly silenced before, because of wrong
`[@ocaml.warning]` position
=> fix silenced warnings

plugins/emit_ida_script/emit_ida_script_main.ml, plugins/ida/bap_ida_service.ml, plugins/ida/ida_main.ml
This PR makes BAP compatible with the new bap-ida-python package.
It also introduces few improvements, like a proper handling of the
special characters in the generated output, and ignoring attributes
that do not have an address.
=> update to the new IDA integration interface

docker/Dockerfile
fix https://github.com/BinaryAnalysisPlatform/bap/issues/607
Forced Docker to build last `bap` version, from `master` branch.
=> force Docker to build master branch

vagrant/jessie64/Vagrantfile
As a followup to the #614 I've added a Vagrant file that provisions
jessie with BAP. There are few issues:
- jessie has an old opam that doesn't support plugin autoinstallation
(`opam install depext` solves this issue);
- jessie has llvm-3.4 and our magic for picking the right version didn't
work as expected due to the old opam, so one need to explicitly
install the required version, e.g.,
`opam depext conf-llvm.3.4 --install`
- bap silently uses clang for compiling C++ parts, that is not available
by default on jessie, so an explicit  `sudo apt-get install clang` is
needed (see #617)
Basically, the following script should work on a fresh jessie box:
```shell
sudo apt-get update
sudo apt-get --yes install clang
sudo apt-get --yes install opam
opam init --auto-setup --comp=4.02.3 --yes …
```
=> support for Debian 8

lib/bap_llvm/bap_llvm_loader.ml
The name value was captured from the Self() module, that should not be
used in libraries. The PR solves the issue by setting an explicit name
"llvm" for the loader.
=> fix llvm-loader naming issue

oasis/api, oasis/beagle, oasis/byteweight, oasis/cache, oasis/callsites, oasis/demangle, oasis/dump-symbols, oasis/ida, oasis/ida-plugin, oasis/llvm, oasis/map-terms, oasis/objdump, oasis/phoenix, oasis/print, oasis/propagate-taint, oasis/symbol-reader, oasis/taint, oasis/trace, oasis/warn-unused, oasis/x86, opam/opam
removed a dependency from `cmdliner` in plugins, since they actually depends from `bap-std`, but not directly from `cmdliner`
=> removed a dependency from cmdliner in plugins

plugins/x86/x86_tools_mem.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/640
fix https://github.com/BinaryAnalysisPlatform/bap/issues/642
Lifter should not perform any checks over operands, just use them as they are.
Fix prevent project fails with bytes sequences like `8b 04 25 00 00 00 00`, where source memory operand is defined by zero segment, base and index values.
=> removed displacement checking in modern x86-lifter

lib/bap_llvm/llvm_binary_34.hpp
fix https://github.com/BinaryAnalysisPlatform/bap/issues/645
`llvm 3.4` doesn't support dynamic symbols for macho files, as it could be seen from code snippet below. 
```
symbol_iterator MachOObjectFile::begin_dynamic_symbols() const {
// TODO: implement
report_fatal_error("Dynamic symbols unimplemented in MachOObjectFile");
}
symbol_iterator MachOObjectFile::end_dynamic_symbols() const {
// TODO: implement
report_fatal_error("Dynamic symbols unimplemented in MachOObjectFile");
}
```
=> fixed macho dynamic symbols error when compiling with llvm 3.4

plugins/ida/ida_main.ml
removed a version parameter, that is considered as senseless, also constrained a `ida-paths` to allow user to specify only one additional path instead if providing a list of them.
=> fix ida cmdline parameters

tools/build_plugins.sh
`mktemp --directory` is not portable to OSX. Use instead
`mktemp -d`
=> Use portable `mktemp` opts during install (#658)

lib/bap_llvm/llvm_binary.hpp, lib/bap_llvm/llvm_binary_38.hpp
fix https://github.com/BinaryAnalysisPlatform/bap/issues/656
This PR fixes bugs that crashed bap with *.o elf files.
There are two bugs in two llvm-versions:
1) iteration over elf header in case of segments absence fails with segfault in 
`llvm 3 .4 `.
2) iteration over  dynamic symbols in `llvm-3.8` fails with segfault in some cases. So  we just added one more check.
=> fixes bap segfaults with *.o files

.gitignore, oasis/common, plugins/objdump/objdump_main.ml
Fixed cases cases when section names could be treated as
symbol names, and consequently we had symbols like `.text`.
=> fixed symbols names in objdump symbolizer

.gitignore, lib/bap_demangle/bap_demangle.ml, oasis/cxxfilt.setup.ml.in, plugins/cxxfilt/cxxfilt_config.ml, plugins/demangle/demangle_main.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/669
this PR fixes a couple of bugs related to demangling:
1) internal demangler doesn't fail if name can't be demangled
2) fixed cmdline demangler choice
=> Fix demangle

lib/monads/monads_monad.ml
Fix what looks like a typo to me.  mutli-->multi.
=> Fixing type for multi

lib/bap/bap.mli, lib/bap_byteweight/bap_byteweight.ml, lib/bap_image/bap_memory.ml, lib/bap_image/bap_memory.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_types/bap_bitvector.ml, lib/bap_types/bap_bitvector.mli
The proposed representation uses the Z.t as a container for both: the
payload, and the metadata.
We reserve 15 bits for the metadata. The first bit represents whether a
bitvector should be treated as signed or unsigned. The rest 14 bits
contain the size of a bitvector. With such representation we can encode
only bitvectors of size 2^14 or less. This is, however, enough in
practice. If more would be needed we may switch to a more complex
prefixed encoding akin to UTF.
```
+-----------+------+---+
|  payload  | size | s |
+-----------+------+---+
size+15  15 14       0
```
Given this representation all bitvectors that are smaller than
0x1_000_000_000_000 are represented as an OCaml int, and are thus
unboxed, so creating new bitvector, and performing bitvector
arithmetic no longer performs …
=> Thin bitvector

lib/bap_build/bap_build.ml, tools/bapbundle.ml, tools/build_plugins.sh
fix https://github.com/BinaryAnalysisPlatform/bap/issues/678
Now files in bap plugin bundles, that were previously named `foo.cmxs` will be named as `bap_plugin_foo.cmxs` 
Also `bapbundle` starts to dashify bundle's name:
```
bapbundle update -name new_name foo.plugin
bapbundle show -m foo.plugin 
((name new-name)
(version 1.0.0)
....
```
=> renamed plugins files

lib/bap/bap_self.ml, oasis/primus-lisp, oasis/run
so now `bap` works with both cmdliner.0.9.8 and cmdliner.1.0.0
partial fix for https://github.com/BinaryAnalysisPlatform/bap/issues/636
=> compiling with cmdliner.1.0.0

lib/bap/bap_project.ml, lib/bap_disasm/bap_disasm_brancher.ml, lib/bap_disasm/bap_disasm_brancher.mli
fix for https://github.com/BinaryAnalysisPlatform/bap/issues/633
The problem was in signal propagation. When we merge different
rooters: ida rooter, internal and byteweight rooter, we get an empty
list of roots because an internal one waits for image, but doesn't
have it, and result stream doesn't fullfill with results from any of
rooters
=> fixed problem with loaders, registered in Project

lib/bap_ida/bap_ida.ml, oasis/elf, plugins/map_terms/map_terms_main.ml, plugins/trace/trace_main.ml, plugins/warn_unused/warn_unused_main.ml, src/bap_main.ml, src/bap_mc.ml
This PR adds compatibility for `cmdliner 1.0` . 
Previous `cmdliner 0.9.8` still could be used as `bap` dependency. 
Also this PR fixes some minor bugs and warnings.
=> update cmdliner + minor

lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_disasm.cpp, lib/bap_llvm/llvm_elf_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp, lib/bap_llvm/llvm_primitives.cpp, lib/bap_llvm/llvm_primitives.hpp
this PR fixes two bugs:
- fixes recently added bug with sectoins name for `llvm 3.8`
- adds lost `#include` file for l`lvm 4.0`
=> fix few bugs in bap-llvm

plugins/x86/x86_lifter.ml
First of all, the original BIL code confused source and destination operands.                                                                                                                                                                                                           
E.g., `xadd [eax], ebx` stores the result in the `ebx` register, although it                                                                                                                                                                                                             
is correct to store it in the memory cell `[eax]`. …
=> fixed xadd insn

plugins/x86/x86_lifter.ml, plugins/x86/x86_utils.ml
According to the manual, `ror/rol` instructions has
the following calculation of the number of bit positions:
```
tempCOUNT ← (COUNT & COUNTMASK) MOD SIZE
```
We didn't  take a `mod size` in x86 lifter, while we should.
Also, BIL contains weird assignments like `OF := OF`,
when the flag is unchanged, so we will get rid of them.
(fix for https://github.com/BinaryAnalysisPlatform/bap/issues/706)
Finally, rotate instructions look like the following:
```
bap-mc "c000ff" --show-bil  --show-asm --arch=X86
rolb $0xff, (%eax) 
{
orig_count1 := 7
mem := mem
with [EAX] <- mem[EAX] << orig_count1 | mem[EAX] >> 8 - orig_count1
if (orig_count1 = 0) {
CF := low:1[mem[EAX]]
}
else {
if (orig_count1 = 1) {
OF := CF ^ high:1[mem[EAX]]
}
else {
OF := unknown[OF undefined after rotate of more then 1 bit]:u1 …
```
=> Fixing rotate instructions

plugins/x86/x86_lifter.ml
Consider next `subb %al, %al` that looks like following:
```
1  v1 := low:8[EAX]
2  EAX := extract:31:8[EAX].0
3  OF := high:1[(v1 ^ low:8[EAX]) & (v1 ^ low:8[EAX])]
4  ...
```
Operands and destination are the same. And after second line it's incorrect to use `eax` register as operand, since its value was changed.
So what we do need here is to use temporary variables for operands:
```
1  v1 := low:8[EAX]
2  v2 := low:8[EAX]
3  EAX := extract:31:8[EAX].0
4  OF := high:1[(v2 ^ v1) & (v2 ^ low:8[EAX])]
5  ...
```
=> fix sub flags calculation

lib/x86_cpu/x86_cpu.ml, lib/x86_cpu/x86_cpu.mli, lib/x86_cpu/x86_env.ml, lib/x86_cpu/x86_env.mli, lib_test/x86/test_pshufb.ml, plugins/x86/x86_lifter.ml, plugins/x86/x86_utils.ml
The PR makes YMM registers available for IA32 and AMD64 users. The PR also fixes a few 
inconsistencies in the interface exposed internally in plugin modules (e.g., the x86_lifter):
the number of YMM registers now varies based on the architecture and the `nums`
array was removed and replaced by references to the AMD64 `r` array. The `r` array definition was
changed to empty for IA32 internals (it can still throw runtime errors and needs to be removed in
the future, but this version is better than the previous approach).
=> Making YMM registers available for IA32 and AMD64 users.

plugins/x86/x86_mov_offset.ml, plugins/x86/x86_tools_mem.ml, plugins/x86/x86_tools_types.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/752 for builds with llvm 3.8+ . 
Segment prefixes are handled as they should be:
1) without prefix
```
$ echo '0xa1,0x14,0x00,0x00,0x00' | bap-mc --arch=x86 --show-bil --show-insn --show-insn=asm --x86-lifter=modern
MOV32ao32(0x14,Nil)
movl 0x14, %eax
{
EAX := mem[0x14, el]:u32
}
```
2) with prefix
```
$ echo '0x65,0xa1,0x14,0x00,0x00,0x00' | bap-mc --arch=x86 --show-bil --show-insn --show-insn=asm --x86-lifter=modern
MOV32ao32(0x14,GS)
movl %gs:0x14, %eax
{
EAX := mem[GS_BASE + 0x14, el]:u32
}
```
=> fixed mov with offset insn

lib/bap_sema/bap_sema_lift.ml
Previously, only local indirect jumps were considered,
so tail call performed by branch instruction wouldn't
be resolved. This PR solves this issue
=>  added goto resoliving for non local indirect jumps

lib/bap_llvm/llvm_primitives.hpp, plugins/primus_lisp/lisp/pointers.lisp, plugins/x86/x86_mov_offset.ml
minor bug fixed:
1) in primus lisp - read-word didn't read a requested count of words
2) in x86-lifter - forgotten llvm version constraint for `movoffset` instruction
after added llvm 5.0 support
3) in bap_llvm library fixed a bug that crushes bap build with llvm 3.4
=> Minor bug fixes

lib/bap/bap_project.ml, src/bap_cmdline_terms.ml, src/bap_fmt_spec.mli, src/bap_main.ml, src/bap_source_type.ml, src/bap_source_type.mli
Cmdline option source-type had no effect. This PR solves this issue.
So there are not any errors when loading a project from `.marshal` file
or when using a raw code with bap.
fix https://github.com/BinaryAnalysisPlatform/bap/issues/694
=> Fix source-type cmdline option

lib/bap_disasm/bap_disasm_reconstructor.ml
In the reconstructor block destinations are computed directly from the BIL representation, that is not correct, as BIL doesn't take into account the relocations. And if the relocatable brancher is used, then the CFG contains correct edges, but this information is ignored when we build a set of call destinations in the reconstructor.  This PR addresses this problem by searching a destination directly in CFG.
=> fixes the search of destinations in the reconstructor

README.md
Redirect API documentation link from v1.0.0 documentation to master documentation. This way, the linked documentation both is up to date and will stay up to date.
=> Redirect API documentation link

lib/bap_image/bap_memory.ml
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/711
Just print address with a pretty printer from `Addr` module.
How it looks like:
```
~/factory/bap/testsuite$ bap obj/arm-linux-gnueabi-obj -dasm | head
Disassembly of section .text
c0000080: <sub_c0000080>
c0000080:
c0000080: fe ff ff eb                             bl #-0x8
c0000084:
c0000084: 08 00 0b e5                             str r0, [r11, #-0x8]
c0000088: 14 10 1b e5                             ldr r1, [r11, #-0x14]
c000008c: 10 00 1b e5                             ldr r0, [r11, #-0x10]
```
```
~/factory/bap-testsuite$ bap bin/x86_64-linux-gnu-echo -dasm | head
Disassembly of section 02
00000000004005d0: <.__gmon_start__>
00000000004005d0:
4005d0: ff 25 72 0a 20 00                         jmpq *0x200a72(%rip) …
```
=> Fixes memory printer

.run_travis_tests.sh, .travis.yml, .travis_install.sh, Makefile, opam/opam
Starting from this PR our CI will get profit from `travis` stages feature. 
So what do we have:
- three parallel builds, that just compile and install `bap` for each supported compiler. One of the builds also warms up a cache for next stages;
- parallel stages for unit tests and `testsuite` checks.
=> moves to travis stages

plugins/x86/x86_backend.ml, plugins/x86/x86_utils.ml
There are quite a few `_exn` functions in the modern x86 that make
some assumptions about the structure of data, that shouldn't be done,
as we shall not make any hard assumptions about the output of the
disassembler or the binary input itself.
This commit fixes an issue that arises when bap is applied to binaries
that are compiled for the latest version of Mac OS X that leads to an
abnormal termination with an unhandled exception. The failure is
indeed provoked by the llvm backend that loses the segment prefix,
though under no circumstances shall we do any preconditioning on the
LLVM output. I've grepped the code to find other possible issues and
found quite a lot uses of the `_exn` that are not justified or at
least questionable.
So far, I've added a try/catch clause around the lifter, …
=> prevents x86 lifter from botching bap

oasis/powerpc, oasis/taint, plugins/primus_propagate_taint/primus_propagate_taint_main.ml, plugins/trivial_condition_form/trivial_condition_form_main.ml
Now we have two approaches to taint analysis:
- The new Taint Analysis Framework
- The legacy Taint Propagation Framework
While the former is more precise and versatile then the latter we
still have a bunch of legacy software that we want to support, e.g.,
Saluki and our IDA Pro integration still relies on the old
framework. We may update the downstream tools to use the new
Taint Analysis Framework, but right now we don't have enough recourses
to perform such task. And I doubt that in case of Saluki this will make
any sense.
The `primus-propagate-taint` plugin provides a compatibility layer that
allows legacy tools to benefit from Primus without event knowing
anything about it. There are some trade-offs starting from the
semantics of the propagation and ending with the desire to minimize …
=> Provide taint frameworks compatibility layer

README.md, docker/debian/dev/Dockerfile, docker/debian/testing/Dockerfile, docker/debian/v1.4/Dockerfile, docker/trusty/testing/Dockerfile, docker/trusty/v1.4/Dockerfile, docker/xenial/testing/Dockerfile, docker/xenial/v1.4/Dockerfile, tools/binary-release.sh, tools/deb-build.sh, tools/opam-release.sh, vagrant/trusty64/Vagrantfile, vagrant/xenial64/Vagrantfile
This PR adds 7 docker files and 3 vagrant files that are using in our
CI system to test bap installability.
Also this PR updates our `opam-release.sh` script, that is now capable
of performing the whole update procedure of the OPAM repo in fully
automated way (you need to create only PR manually)
=> updates CI tools

.run_travis_tests.sh, oasis/common
to prevent the confusion with the already released version
=> bumps the bap version to 1.5.0-dev

lib/bap_types/bap_ir_callgraph.ml
An empty call graph was produced in a degenerative case, when there
are no calls at all, i.e., when there are no edges in the callgraph.
Now it will produce a graph that will have only nodes, in that case.
=> produces correct callgraphs if there are no calls in a program

plugins/objdump/.merlin, plugins/objdump/objdump_main.ml
it's not necessary and breaks buils in the newer jbuilder compiled
`re` library, as it no longer installs cmi files to the same folder.
also fixes the .merlin file by adding the build files location
=> removes the bogus `open Re_perl` statement

lib/bap/bap.mli, lib/bap_types/bap_bitvector.ml, lib/bap_types/bap_bitvector.mli, lib_test/bap_types/test_bitvector.ml
Adds the functions `gcd`, `lcm`, and `gcdext` to the bitvector interface. `gcd` computes the greatest common denominator of the inputs, `lcm` computes the least common multiple, and `gcdext` also computes coefficients `s` and `t` such that if `gcdext x y = (d, s, t)` then `d = s*x + t*y`.
Also adds functions `gcd_exn`, `lcm_exn`, and `gcdext_exn` that raise exceptions on improper inputs rather than returning an error.
=> Expose gcd, lcm, and gcdext functions on BAP bitvectors

lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_elf_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp, lib/bap_llvm/llvm_primitives.cpp, lib/bap_llvm/llvm_primitives.hpp
There was a kind of bug in llvm backend: relative address for any binary entry was defined as non-negative value. Probably, it wasn't a very bad choice, since we don't want to
deal with negative addresses. But from another point of view, we always convert relative address to absolute and negative address should not happen. And we actually inject wrong
information in ogre when storing non-negative numbers: converting them to absolute addresses assigns a real value to every entry, dependless if it had a meaningful address or not at all.
=> fixes relative addresses in llvm backend

lib/bap_image/bap_image.ml, plugins/print/print_main.ml
This PR restores a section view
When we switched to `ogre`, we started to tag segments memory regions both
as segments and sections. That's why we have an output like `Disassembly of section 02` when using `bap` with `-dasm` option.
fix https://github.com/BinaryAnalysisPlatform/bap/issues/780
Also, this PR makes printing a bit more pretty, and examples bellow show it.
How it was before:
```
0000000004006ed: <print_endline>
00000000004006ed:
4006ed: 55                                        pushq %rbp
4006ee: 48 89 e5                                  movq %rsp, %rbp
4006f1: 48 83 ec 20                               subq $0x20, %rsp
4006f5: 48 89 7d e8                               movq %rdi, -0x18(%rbp)
4006f9: 48 8b 45 e8                               movq -0x18(%rbp), %rax
4006fd: 48 89 …
```
=> restores the section view

lib/bap_llvm/llvm_binary_38_40.hpp, lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_disasm.cpp, lib/bap_llvm/llvm_elf_loader.hpp, lib/bap_llvm/llvm_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp, lib/bap_llvm/llvm_primitives.cpp, lib/bap_llvm/llvm_primitives.hpp, plugins/x86/x86_mov_offset.ml
=> adds llvm 6.0 support

plugins/api/api_main.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/776
So everybody is welcome to set `api` path like `$ bap bin/exe --api-path=. `
=> fixes paths comprehension in api plugin

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_env.ml, lib/bap_primus/bap_primus_env.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_interpreter.mli, lib/bap_primus/bap_primus_linker.ml, lib/bap_primus/bap_primus_linker.mli, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_lisp.mli, lib/bap_primus/bap_primus_lisp_def.ml, lib/bap_primus/bap_primus_lisp_def.mli, lib/bap_primus/bap_primus_lisp_parse.ml, lib/bap_primus/bap_primus_lisp_program.ml, lib/bap_primus/bap_primus_lisp_program.mli, plugins/primus_lisp/lisp/ascii.lisp, plugins/primus_lisp/lisp/init.lisp, plugins/primus_lisp/lisp/memory.lisp, plugins/primus_lisp/lisp/pointers.lisp, plugins/primus_lisp/lisp/primus.lisp, plugins/primus_lisp/lisp/simple-memory-allocator.lisp, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_lisp/primus_lisp_primitives.ml, plugins/primus_lisp/primus_lisp_primitives.mli, plugins/primus_loader/primus_loader_basic.ml, plugins/primus_taint/primus_taint_main.ml, plugins/primus_test/lisp/check-value.lisp, plugins/run/run_main.ml
This PR provides various enhancements to the Primus Lisp subsystem that aim to make it faster and easier to use. 
This PR provides a very crude and fast coded autodoc generator, that dumps docstrings in the dot format (that I manually translate to html using emacs), example could be [found here][1]. This is very preliminary, and only the API index is generated (no module/aka features documentation). Anyway, I believe it is much better than nothing. 
Basically, the whole interface is just two functions: `eval_fun` and `eval_method`. Now it is possible to run Lisp programs without actually having the IR.
This is a new feature in Primus Lisp. Now a module can specify parameters using the `defparameter` form. Parameters are like any other global variables, except that they could be …
=> Primus Lisp enhancements

plugins/x86/x86_lifter.ml
forgotten parentheses in shift instructions
compare with bap.1.2.0:
```
match st with
| LSHIFT -> Bil.(Cast (LOW, !!bool_t, Var origDEST lsr (size - Var origCOUNT)))
| RSHIFT | ARSHIFT ->
Bil.(Cast (HIGH, !!bool_t, Var origDEST lsl (size - Var origCOUNT)))
| _ -> failwith "impossible"
```
=> fixed minor bugs

lib/graphlib/graphlib_graph.ml
otherwise it was always equal to `1`. Thanks @DIJamner for the report.
=> increments the step number on each iteration

lib/bap/bap_project.ml
Sections were printed twice in disassembly output when using bap with pure binary code. This PR
removes this behavior:
```
$ bap some_exe -dasm --source-type x86-code --read-symbols-from start
Disassembly of section bap.user
0: <_start>
0:
0: 66 31 c0                                       xorw %ax, %ax
3: 66 40                                          incw %ax
5: 66 89 c1                                       movw %ax, %cx
```
=> removes duplicated sections in disassemble output

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_memory.ml, lib/bap_primus/bap_primus_memory.mli
Historically, our implementation of the memory storage was a mapping from bitvectors to bitvectors, thus any store operation was forgetful as the identity of a value was discarded (where a value in Primus is a tuple of data and a unique identifier). For a long time we were considering this as a feature, articulating that `x` and `load a (store a x)` are two different values, even though, they are usually structuraly equal. However, it was also observed, that in many cases during the analysis we would like to preserve this identities, thus we were forced to maintain our own mappings between words and value identities in this or that way.
The proposed solution should satisfy both camps, those who believe that `x` and `load a (store a x)` are in general different, and those who say, that in …
=> changes the Primus memory representation to preserve value identity

lib/bap/bap_project.ml, lib/bap_future/bap_future.ml, lib/bap_future/bap_future.mli, src/bap_main.ml
This PR moves some preliminary parts of project creation to the module `Project` itself.
Also, PR adds `concat` and `concat_merge` to `Bap_future` library.
Previously, we were creating project somehow like following:
```
let input = Project.Input.file "exe";;
let Ok proj = Project.create ?rooter:(Rooter.Factory.find "internal") input;;
```
With this PR a process of project creation looks much more simple:
```
let input = Project.Input.file "/bin/ls" ;;
let pr = Project.create input ;;
```
=> rectifies project construction

lib/bap_disasm/bap_disasm_reconstructor.ml
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/801
This PR fixes a problem with a disassembling of pure code: as there are not any functions in there, bap just doesn't output anything.
What we actually do here is not about only those files, but about reconstruction at all: we consider all blocks in the reconstructor that don't have input edges as functions starts. And it makes sense, e.g. in case of libraries: there is not any precondition that every function will be called by some other function from this library.
=> fixes calls search in the reconstructor

plugins/print/print_main.ml
this PR adds ogre dump format:
```
$ bap /bin/echo --dump=ogre
(declare arch (name str))
(declare base-address (addr int))
...
(arch x86_64)
(base-address 4194304)
...
```
=> adds ogre dump format

lib/bap_llvm/llvm_macho_loader.hpp
Previously, only little endian binaries were expected in our macho loader, so this caused unexpected behavior with big endian binaries. This PR fix it, as well adds some more guards for reliability.
Also, this PR fixes problem with an entry point for old macho binaries: they just don't contain so-called `LC_MAIN` command, and entry point as part of the binary structure is absent.
But we can workaround this problem by emitting entry point as an address of a first executable section.
=> improves macho loader

plugins/ida/bap_ida_service.ml, plugins/ida/ida_main.ml
To run IDA we cd to a newly created temporary folder. If IDA fails,
then we end up there. This not only breaks the rest of BAP, but
produces extremely confusing error messages, such as `bap ./exe` will
produce `Sys error: ./exe no such file or directory`.
=> hardens IDA plugin

lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_machine.ml, plugins/primus_greedy/primus_greedy_main.ml, plugins/primus_lisp/lisp/init.lisp, plugins/primus_lisp/lisp/memory.lisp, plugins/primus_lisp/lisp/pointers.lisp, plugins/primus_lisp/lisp/simple-memory-allocator.lisp, plugins/primus_lisp/lisp/string.lisp, plugins/primus_promiscuous/primus_promiscuous_main.ml, plugins/primus_test/lisp/memcheck-malloc.lisp, plugins/primus_test/lisp/memcheck.lisp
I'm sorry for pushing this as a single branch, but it is better to push this to upstream, otherwise I will begin to stockpile this fixes. I will try to prettify my bad behavior with a pretty table of contents below
Bug fixes
=======
- [do not evaluate atomic memory variable](df26135) to prevent type errors;
- [fixes term tear down procedure](114245b) it is still broken, but less than it was;
- [disable call bypassing](a763457) when a call is taken, otherwise we are returning to the same place twice;
- [ignore return statments](0a224d7) the interpreter should just stop at the end of the function and let the caller to continue. Otherwise, we will resume at the caller twice - first when the caller returns and the second time when machine stops. I will later provide some checks for control …
=> fixes a few bugs in Primus

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_memory.ml, plugins/primus_lisp/primus_lisp_primitives.ml
It was possible to store a word of arbitrary width in our byte
storage. It is fixed now, and I've also updated documentation and
added few sanity checks.
=> fixes an incorrect store operation introduced by #806

src/.merlin, src/bap_cmdline_terms.ml, src/bap_cmdline_terms.mli, src/bap_main.ml, src/bap_recipe.ml, src/bap_recipe.mli
In case if you happen to know already what recipes in bap are, then
the main chainges are summarized below:
- the recipe is no longer requred to be a zip file, plain files, or
directories are now accepted
- the recipes interface is now documented and a couple of issues were
fixed during the process
- filenames are no longer substituted, however there is now a builtin
parameter `$prefix` that is substituted with the path to the recipe
root folder.
For the rest, I'm copypasting excerpts from the bap man page, that
describe the recipe system in detail as well as few motivational
examples
```
RECIPE DESCRIPTION
A recipe is either a single file or a directory (optionally zipped)
that contains a parametrized specification of command line parameters
and support files if necessary.
The purpose of …
```
=> enhances and documents recipes

plugins/powerpc/powerpc.mli, plugins/powerpc/powerpc_branch.ml, plugins/powerpc/powerpc_dsl.ml, plugins/powerpc/powerpc_dsl.mli, plugins/powerpc/powerpc_load.ml, plugins/powerpc/powerpc_logical.ml, plugins/powerpc/powerpc_model.ml, plugins/powerpc/powerpc_model.mli, plugins/powerpc/powerpc_rotate.ml
There are some efforts on PowerPC lifter.
A brief list of changes:
1) fixed a bug in branch instructions with an alignment of addresses from `lr`, `ctr` and `tar` registers.  
2) added a `val ones : bitwidth -> exp `  funciton, that could come in handy for masks;
3) updated `PowerPC` model: we still had `lr` and `ctr` registers of 64 bits length even for 32 bits arch;
4) refactored a couple of instructions: `cmpb` and `popcntw`, just because it was easy to write much readable implementation;
5) reduced a using of `doubleword`. It's a kind of artifact that we have from a time when all registers in our model were 64 bits length, and therefore we didn't pay much attention to
variables length we created. And now, when we have different models with a respect to address size, a using of …
=> rectifies powerpc lifter

lib/bap_types/bap_ir.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/808
We track every addition of a subroutine to a program by storing names and tids in a table. Every addition replaces previous entries with the same name. When someone requests a result, it's easy to tell if a subroutine name needs in demangling: if a `tid` in the table for this name is differ from a subroutine's one, then other subroutine started to use this name, and we need to demangle current name. The same is true for subroutine aliases.
=> adds mangling of duplicated subroutines

lib/bap/bap.mli, lib/bap_types/bap_interval_tree.ml, lib/bap_types/bap_interval_tree.mli
Add an interface and `Make_binable` functor for binable interval trees. This allows interval trees to be serialized and used as universal values (e.g. in term attributes).
=> Add an interface for binnable interval trees

plugins/callsites/callsites_main.ml
Disclaimer
----------
I was really reluctant since the very beginning to introduce this
dependency, since we shouldn't depend on implementations but on
abstractions, but so far it looks like the easy solution, that, I
hope, won't last too long.
The Problem
-----------
`bap ./exe --taint-reg=malloc_result` may or may not work, depending
on the order of pass invocations. The root of the problem is that the
taint plugin depends on the callsites plugin, that requires the
argument information to be present in the subroutine
definitions. Since, the `abi` pass is an autorun pass it is aplied
before all other passes, including the `callsites` pass. However,
since for the better user experience, (haha) we decided to mark
the `taint` pass as an autorun pass, it is also run in the autorun
phase …
=> intoduces a dependency between callsites and abi passes

lib/graphlib/graphlib.mli, lib/graphlib/graphlib_graph.ml, lib/graphlib/graphlib_intf.ml
Change the naming convention from `init` to `default` for default values in `Solution.t`s and expose this via a `Solution.default` getter function. Implement a `Solution.derive` function that allows for creating new `Solution.t`s from old ones.
=> Rename Solution init value to default. Add Solution.derive

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_interpreter.mli, plugins/primus_lisp/primus_lisp_main.ml
The `jumping` observation allows for observing the taken conditionals
as well as the jump destination. This extra observation allows
observing all conditions that were evaluated up until the taken branch
(including the false ones). Conditions in branches _after_ the taken
branch will not be observed.
=> Add an `eval_cond` observation to allow observing non-taken conditionals

plugins/primus_taint/primus_taint_main.ml
Fixes the function names in two documentation strings that incorrectly refer to another function.
=> Fix function names in docstrings

lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_machine.ml, lib/bap_strings/bap_strings_unscrambler.mli, lib/graphlib/graphlib.mli, plugins/api/api/c/posix.h, plugins/primus_greedy/primus_greedy_main.ml, plugins/primus_mark_visited/primus_mark_visited_main.ml, plugins/primus_test/lisp/memcheck.lisp, plugins/primus_test/lisp/warn-unused.lisp, plugins/primus_test/primus_test_main.ml, plugins/run/run_main.ml
This PR brings several very significant bug fixes to Primus. Most importantly it fixes machine killing function, so that we can now kill finished machines, that significantly reduces the memory footprint.
=> Several primus fixes

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_interpreter.mli, lib/bap_primus/bap_primus_linker.ml, lib/bap_primus/bap_primus_linker.mli, lib/bap_primus/bap_primus_memory.ml, lib/bap_primus/bap_primus_memory.mli, plugins/primus_promiscuous/primus_promiscuous_main.ml
Division by zero as well as faulty memory operations may terminate the
Primus Machine. Previously we were just terminating it with a specific
exception. However, this exceptions should actually be represented by
an CPU/ABI-specific interrupt or trap. The proposed implementation
provides a mechanism that allows:
- trap the exception and translate it to a machine specific
interrupt;
- ignore or fix it;
- catch it on a low-level.
The mechanism is based on the same idea as in the Linker that used the
primus_unresolved_handler to trap unresolved names. For each trap we
provide a corresponding observation, that could be used to install the
trap. The trap itself, is a special name, that could be linked (either
on a permanent basis, or from the observation). If the trap hanlder is
assigned, then …
=> adds traps for memory and division operations

lib/bap_sema/bap_sema_lift.ml
This is necessary for correctly handling control flow in BIL
containing the above patterns. One example explaining why this
is necessary is the following:
```
if false {
CPUExn 10
}
x := 5
```
The above would be translated to:
```
goto %takeoff
landing:
goto %next
takeoff:
when false cpuexn N return %landing
next:
x := 5
```
Note that the `takeoff` basic block is missing the
possible control flow transition to the `next` block.
By removing these special cases jmps and cpuexn are handled as
normal statements within an `if` block.
=> Remove special handling of jumps/cpuexns during linearization.

lib/bap_types/bap_helpers.ml
Fixes issues [#846](https://github.com/BinaryAnalysisPlatform/bap/issues/846) and [#843](https://github.com/BinaryAnalysisPlatform/bap/issues/843) by using the right comparison and adding a necessary case to a simplified type inference function.
=> Fix mem types

.travis-ocaml.sh, .travis-opam.sh, .travis.yml, .travis_install.sh
After last changes in `ocaml-ci-scripts`, a default version of `opam` became `2.0`, that breaks our builds. The simplest fix would be just to set an environment variable OPAM_VERSION=1.2.2`, but it doesn't help. The reason is in the order of setting env variables and installation of packages in the deep of those scripts.
And we don't want to wait neither for fix nor for next breaking changes from their side, so we will use just a couple of their old scripts that works fine for us.
=> updates travis env

lib/bap/bap.mli, lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_interpreter.mli, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli
The semantics of ite evaluation in Primus follow the latest updates
in the BIL specification:
https://github.com/BinaryAnalysisPlatform/bil/pull/9
The extra option in the BIL normalization function enables the
user to preserve ite if that is desirable.
=> ite-handling in Primus and allowing the user to disable ite-hoisting.

plugins/ida/bap_ida_service.ml
fix https://github.com/BinaryAnalysisPlatform/bap/issues/720
Just remove dump files from `/tmp/ida` before any `ida` launch
=> cleans /tmp/ida every time ida is called

lib/bap/bap_self.ml
also warns if a deprecated parameter is used as a flag
fix https://github.com/BinaryAnalysisPlatform/bap/issues/764
=> Fix deprecated args

lib/bap_disasm/bap_disasm_brancher.ml, lib/bap_disasm/bap_disasm_reconstructor.ml, lib/bap_disasm/bap_disasm_symtab.ml
This PR rectifies reconstructor, symtab and brancher with a respect to performance, without addition of a new behavior or breaking of an existing one.
Changes:
Rewrote it and reduced the number of iterations over nodes/edges of cfg.
The main point is how we build the `filtered` cfg. Previously, we did like the following: take all nodes, add them ony-by-one to an empty cfg. So it was an iteration over all nodes of cfg. Then iterate over all edges, and add each of them if their's destination block is not root. 
Also, we did one more iteration over all nodes in `find_calls` function.
So what I'm proposing here is just to iterate once over the whole cfg to find all roots. and then build the `filtered` cfg by iterating over the roots and removing their input edges.
There was a bit inefficient …
=> optimizes reconstructor, symtab, and brancher performance

lib/bap_disasm/bap_disasm_rec.ml, lib/bap_disasm/bap_disasm_reconstructor.ml
The root of the problem was the rooter, which was producing roots that were pointing in the middle of an instruction. Since the disassembler was cutting a block on the start of each root this led to an incorrect CFG with non-connected components. 
It's fine for a rooter to produce such garbage, however, the disassembler shall not take rooter's output as granted. The new implementation keeps track of the set of addresses that start valid instructions and once this set is fully discovered removes those roots that do not belong to this set.
=> fixes the bug that was producing unreachable blocks

lib/x86_cpu/x86_env.mli
just moved `[@@deprecated]` after `X86_env.nums`.
Previously we had in compile time the next warning
```
Warning 3: deprecated: CPU.r
[since 2018-01] user `r` instead
```
i.e. a new definition was deprecated, not a previous one.
=> deprecates X86_env.nums in correct place

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_reconstructor.ml
Actually, this PR just restores the previous behavior, that was lost due to lack of tests and comments.
So this PR:
1) extends a list of roots with addresses of such CFG nodes, that don't have any input edges. The effect is noticeable in a case of pure code input, since the list of roots is empty in such case, and therefore the reconstructor will create just an empty `symtab`.
2) adds comments in the code to avoid losing such behavior in the future.
3) updated documentation for reconstructor in `bap.mli`, since it looks quite outdated
=> fixes calls search in reconstructor

plugins/cache/cache_main.ml, plugins/ida/bap_ida_service.ml
Previously we used `sexp` for storing index, but it turned out that it is very slow. And in this PR we save index with `bin_io`, that solves the problem.
Also, this PR fixes the issue with closing of lock files.
=> saves cache index in bin_prot

opam/opam
prevent CI from downloading signatures in build time
fix https://github.com/BinaryAnalysisPlatform/bap/issues/835
=> added bap-signatures to dependencies

lib/bap_elf/bap_elf.mli, lib/bap_elf/elf_types.ml, oasis/common.tags.in, oasis/elf
in order to use `bitstring.ppx`, we should not use `ppx_driver` and `ppx_custom` predicates according to bitstring META file. And ppx_jane can't be used too. That's why we just omit `bap_elf` directory in our tags file.
It turned out that we can't build `bap-elf` on every compilator we support. The constraint is `>= 4.04.1`. And we need to add it to `opam` file of `bap-elf` library
=> enables bap-elf

src/bap_cmdline_terms.ml
Since we don't merge brancher sources, we need to set a default one, which will be used in case if many branchers available.
=> makes the main `bap` brancher a default one

lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp
Looks like that we didn't build bap with `llvm-3.4` for a while, so there were a couple of minor bugs there. This PR fixes them.
=> few fixes in llvm backend 

plugins/primus_test/lisp/memcheck.lisp
Obviously a wrong arguments' count.
=> Fix a typo in Primus memcheck test

.travis-ocaml.sh, opam/opam
Starting from 17th of September, `master` branch of opam repository is for 2.0 version only, so hardcode it explicitly and use the previous opam version is wrong. So we just let to redirect us to branch with `1.2` packages
=> fixes builds on travis

plugins/x86/x86_tools_mem.ml
We have the next nasty compilation warning:
```
File "plugins/x86/x86_tools_mem.ml", line 58, characters 6-322:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
((`YMM0|`YMM3|`XMM10|`XMM1|`YMM4|`XMM15|`XMM6|`YMM1|`YMM11|`XMM12|`YMM15|
`XMM13|`YMM10|`YMM9|`YMM13|`XMM3|`XMM9|`XMM11|`YMM5|`XMM2|`YMM7|`YMM14|
`YMM8|`YMM2|`XMM0|`XMM5|`XMM7|`XMM4|`XMM8|`XMM14|`YMM12|`YMM6),
_)
```
So what we need is just to update an error clause of pattern matching with SSE registers, as they 
don't participate in effective address computation, according to 
`Intel® 64 and IA-32 architectures software developer’s manual, volume 1,
Section 3.7.5 (Specifying an Offset)`
> 
> The offset part of a memory address can be specified directly as a static value …
=> removed an unexhaustive pattern matching warning

plugins/cache/cache_main.ml
`bap` fails in case entry in cache index doesn't exist. This PR fixes it.
=> handles correctly format change in the cache module

lib/bap/bap.mli, lib/bap_bml/bap_bml.ml, lib/bap_llvm/bap_llvm_loader.ml, lib/bap_primus/bap_primus.mli, lib/microx/microx_concretizer.ml, lib/microx/microx_concretizer.mli, lib/microx/microx_conqueror.ml, lib/microx/microx_conqueror.mli, lib_test/bap_image/test_image.ml, lib_test/bap_types/test_bili.ml, lib_test/bap_types/test_optimizations.ml, lib_test/powerpc/powerpc_tests_helpers.ml, lib_test/powerpc/powerpc_tests_helpers.mli, lib_test/x86/test_pcmp.ml, lib_test/x86/test_pshufb.ml, plugins/beagle/beagle_main.ml, plugins/primus_loader/primus_loader_basic.ml, plugins/primus_propagate_taint/primus_propagate_taint_main.ml, plugins/propagate_taint/propagate_taint_main.ml, plugins/propagate_taint/propagator.ml, plugins/propagate_taint/propagator.mli, plugins/taint/taint_main.ml, plugins/warn_unused/warn_unused_main.ml
This PR silences warnings from bap code during compilation of bap itself. Also, it turned out that few modules in `bap.mli` were deprecated in a way that doesn't emit warnings at all.
Just for the record, the next sample doesn't deprecate `module A`, because according to the documentation for attributes of level 3:
> They are not attached to any specific node in the syntax tree
```
module A = struct
[@@@deprecated "[since ...]"]
...
end
```
And the next works as expected, although in this case, we have to do the depreciation at the end of the module, which makes it less readable for a user. But anyway, looks like we don't have any other choice.
```
module A = struct
...
end [@@deprecated "[since ...]"]
```
=> silenced warnings from ours deprecations

src/bap_main.ml
it was broken since after we enabled absolute path loading
we were passing a full path to the load function, and now it will treat it literally
=> fixes the --list-recipes option

oasis/llvm.setup.ml.in
it turned out that after `llvm-4.0` a default linking mode is `shared`, and it's not what we want. e.g. debian package will be broken, as `bap` will be depend from `LLVM.so`.
our previous request for libraries now returns an extremly short list:
```
ubuntu@ubuntu-xenial:~$ llvm-config-4.0 --libs
-lLLVM-4.0
```
which is just shared library. So what we can do is to use a new flag for llvm-config:
```
ubuntu@ubuntu-xenial:~$ llvm-config-4.0 --link-static --libs
-lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMMIRParser ...
```
Here it is!
=> ensures static linking with llvm >= 4.0

lib/bap_llvm/llvm_loader_utils.hpp
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/890
Bap fails with a very nasty exception if the llvm backend produces an ogre document that can't be parsed due to an unexpected symbol sequence, e.g.  parsing of the
```
(symbol-entry "?<Constant "Disconnecting; %d\r\n">" 0x9258 0x14 0x4a2d8) 
```
failed just because of `;` symbol, which introduces a comment. 
Previously, we tended to quote strings only if there are some suspicious characters inside.
Starting from this PR we will quote any string in ogre document and replace any suspicious character with its code. And suspicious is everything but letters and digits:
```
(symbol-entry "\x3f\x3cConstant\x20\x22Disconnecting\x3b\x20\x25d\x5cr\x5cn\x22\x3e" 0x9258 0x14 0x4a2d8)
```
Note, these changes will not affect an ogre dump …
=> escapes strings before generating OGRE document

plugins/byteweight/byteweight_main.ml
We have lot's of issues from users (espessialy new one) who can't launch bap because
signatures are not installed. So let's just check if signatures exist before registering the byteweight rooter. It will be more friendly then 
```
bap exe 
Failed to create a project: no signatures
Backtrace:
Raised at file "src/import0.ml" (inlined), line 234, characters 22-32
Called from file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/or_error.ml", line 70, characters 17-32
Called from file "lib/bap/bap_project.ml" (inlined), line 192, characters 15-29
Called from file "lib/bap/bap_project.ml" (inlined), line 193, characters 35-41
Called from file "lib/bap/bap_project.ml", line 272, characters 19-36
Called from file "src/or_error.ml", line 62, characters 9-15
```
=> prevents bap from fail if signatures are missed

lib/bap_llvm/bap_llvm_ogre_loader.ml, lib/bap_llvm/llvm_loader_stubs.c, src/bap_cmdline_terms.ml, src/bap_main.ml
This PR changes an error message if bap is using with an empty file:
```
$ touch /tmp/foo.txt
$ bap /tmp/foo.txt
Failed to create a project: ("File format is not supported: expected executable, library or kernel module"
"Raised at file \"src/import0.ml\" (inlined), line 234, characters 22-32\
\nCalled from file \"src/error.ml\" (inlined), line 9, characters 14-30\
\nCalled from file \"src/or_error.ml\", line 70, characters 17-32\
\nCalled from file \"lib/bap/bap_project.ml\", line 264, characters 47-54\
\nCalled from file \"src/or_error.ml\", line 62, characters 9-15\
\n")
```
fix https://github.com/BinaryAnalysisPlatform/bap/issues/895
=> changes an error message in case of empty file

lib/bap_sema/bap_sema_free_vars.ml
This algorithm kicks in in the optimization-level=3 and ... breaks
everything. The bug was trivial, the kill set was computed before
the live set, hence a block was defining its own variables before it
was used.
This bug affects only 1.5 version with optimization-level=3.
Note, there is still a subtle problem with this algorithm that comes
from the "Everything Dominates Unreachable Block" lemma in the
dominators algorithm. And altough this theorem is valid wrt to the
graph theoretic definition of unreachable, which indeed implies that a
block is not reachable under no circumstances, in the binary analysis
an unreachable block is just a block that might be reachable we just
don't know by which paths. In other words, we have an
under-approximation of a control flow graph, and the …
=> fixes the free-vars-by-dominators computation algorithm

plugins/optimization/optimization_main.ml
As was noted in #905 the optimization passes sometimes misses an
opportunity to remove obvious assignments. The underlying reason
is that we compute a very conservative set of variables which are
used for interprocedural communication. And if a variable is a
member of this set then we do not delete it (under assumption, that
it could be used in other subroutines).
What was overconservative is that all versions of the same variable
were protected, while only the last definition one could be used for
interprocedural communication. The propsed change relaxes the
protected set, and removes only the last version of a variable from
the set of the dead variables.
Fixes #905
=> makes dead code elimination less conservative

lib/bap_disasm/bap_disasm_rec.ml
During the program reconstruction we rely on several sources of information, such as lifter and brancher. However, the information that we obtained from the brancher is not stored that leads to a mismatch later. This PR preserves the information provided by the brancher in the BIL code of an instruction. Ideally, the brancher should operate on the BIL level and fix the BIL itself, but we have what we have. 
We have two sources of information, `D` the set of destinations from the lifter and `D'` the set of destinations form the brancher, which are equally credible for us, but may provide conflicting information. Our task is to generate the BIL code that will have a set of destinations `R` which preserves the existing destinations (completeness) and do not introduce any false destinations …
=> preserves brancher information in the BIL code of an instruction

lib/bap_elf/elf_parse.ml, lib/bap_elf/elf_utils.ml, plugins/elf_loader/elf_loader_main.ml
This PR  makes `bap-elf` compatible with safe-string compilers
=> bap-elf compatibility with safe-strings compilers

oasis/x86, plugins/x86/x86_endbr.ml, plugins/x86/x86_lifter.ml
this PR adds a couple of x86 instructions:
1) adds `endbr` instructions
Despite that we implement these instructions as `noop`, they still are very important for cfg integrity, 
since they usually appear in the beginning of functions.
2) adds call instructions with operand override prefix.  
Previously, we were lifting `call` instructions only if no prefixes present. But `x86_disasm` does all the 
job needed for prefix comprehension (at least in  part of operand overriding).  
Few examples:
```   
$ echo "f3 0f 1e fa" | bap-mc --show-bil --show-insn
ENDBR64()
{
}
$ echo "f3 0f 1e fb" | bap-mc --show-bil --show-insn
ENDBR32()
{
}
$ echo "67 e8 00 fe ff ff" | bap-mc --show-bil --show-insn --addr=0x400500
CALL64pcrel32(-0x200)
{
RSP := RSP - 8
mem := mem with [RSP, el]:u64 <- 0x400506
jmp …
```
=> few x86 enhancements

lib/bap_primus/bap_primus_lisp.ml, plugins/x86/x86_abi.ml
The following code allows ymm registers to be cast to smaller register. This new casting operation is used to extract xmm registers from ymm registers in order to support monomorphic functions in sse. The SysV ABI is extended to receive more arguments and can now recognize functions that read and write to xmm0.
=> SSE XMM0 ABI 

plugins/print/print_main.ml
adds a hexadecimal prefix to addresses
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/842
a correspondent update in `bap-python`: https://github.com/BinaryAnalysisPlatform/bap-python/pull/10
=> fixes ADT printer

docker/debian/testing/Dockerfile, docker/trusty/testing/Dockerfile, docker/xenial/testing/Dockerfile, vagrant/jessie64/Vagrantfile, vagrant/trusty64/Vagrantfile, vagrant/xenial64/Vagrantfile
This PR updates vagrant/docker files due to new `opam` version.
Note, that `sanboxing` is disabled in docker files.
=> updates vagrant/docker files

plugins/byteweight/byteweight_main.ml, src/bap_byteweight_main.ml
This PR fixes https://github.com/BinaryAnalysisPlatform/bap/issues/902
And now signatures can be stored and loaded for a specific compiler too.
=> adds the compiler option to `byteweight` 

lib/bap_disasm/bap_disasm_rec.ml
Given that `byteweight` can emit roots that point somewhere to the middle of a real instruction, we can end up with two possible scenarios:
1) Bytes from the pointed address can't be disassembled. It leads to malformed blocks, and that's the issue we already fixed by filtering only disassembleable code.
2) Bytes can be disassembled, and it's a more interesting and tough case.
Example:
```
8dd820:       45 0f be 07             movsbl (%r15),%r8d
8dd824:       83 c3 01                add    $0x1,%ebx
```
Byteweight gives us a root at `0x8dd821`, and instruction `0f be 07` is perfectly disassembled too. And in general, we can't decide which one is correct.
Our solution is to process both of the instructions: `0x8dd820` and `0x8dd821`, and create 3 blocks here: the first one is a block that …
=> enables memory sharing between instructions

.run_travis_tests.sh, .travis_install.sh, lib/bap/bap_self.ml
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/691
`confdir` was already prefixed above as needed, but not used
=> includes plugin name into the configuration path

lib/bap_llvm/llvm_binary_38_40.hpp, lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_disasm.cpp, lib/bap_llvm/llvm_elf_loader.hpp, lib/bap_llvm/llvm_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp, lib/bap_llvm/llvm_primitives.cpp, lib/bap_llvm/llvm_primitives.hpp, plugins/x86/x86_mov_offset.ml
let's trust to `llvm` and don't constraint its version from the above.
=> removes upper constraint for llvm version

lib/bap_primus/bap_primus_linker.ml, lib/bap_primus/bap_primus_linker.mli, lib/bap_primus/bap_primus_lisp.ml
This PR adds a couple of observations that will be invoked every time an externally linked stub is called and returns.
Enables a workaround for #879.
=> adds observations for primus lisp stubs

plugins/callsites/callsites_main.ml, plugins/print/print_main.ml
Previously, the callsites plugin was inserting arguments in a such way that dual intent arguments were evaluated after the return arguments. This PR fixes the order, so that the in/our arguments are evaluated before the out arguments. It is also takes extra care and sorts the arguments before inserting, so that we do not rely too much on the order of arguments in the subroutine term.
This PR fixes the #740 in which a wrong order of evaluation led to the destruction of a def-use chain.
=> fixes the order of arguments in the callsites plugin

lib/bap/bap_log.ml
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/722
=> fixes TOCTOU bug in bap log

plugins/primus_lisp/primus_lisp_main.ml
Previously, generating primus lisp documentation could fail without any error, log messages, etc.:
```
$ bap /bin/true --primus-lisp-documentation | wc -l 
$ 0
```
The reason was in the order in which passes applied to a program. This PR fixes this bug by adding a dependency from `api`. 
```
$ bap /bin/true --primus-lisp-documentation | wc -l 
$ 488
```
=> fixes dependencies in primus lisp plugin

plugins/constant_tracker/lisp/check-null-pointers.lisp, plugins/primus_lisp/primus_lisp_main.ml
This PR fixes a couple of bugs that prevent constant-tracker from working correctly:
1) a typo in the lisp code
2) forgotten signals `loading` and `storing`
=> fixes constant-tracker

plugins/primus_taint/primus_taint_main.ml
The taint collector was always deemed as an optional feature, that at the cost of extra runtime cost, may increase the precision of the taint propagation engine. It is also not a feature, that everyone expects in a typical taint propagation engine so it might introduce unnecessary confusion. 
Note, the taint propagation garbage collector tracks the liveness of taints, and deletes (sanitizes) them as soon as they are not reachable anymore.
=> switches off primus-taint-gc by default

lib/bap_taint/bap_taint.ml
Previously, `Taint.sanitize` worked vice versa: all the taints of the requested kind were preserved, and all others were deleted. This PR fixes it.
=> fixes taint sanitation

docker/alpine/Dockerfile
This PR adds a docker file which builds the testing version of `bap` and is based on
`ocaml/opam2:alpine` image.
=> adds an apline based dockerfile

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_linker.ml, lib/bap_primus/bap_primus_lisp.ml, plugins/primus_x86/.merlin, plugins/primus_x86/primus_x86_loader.ml
For x86 and x86_64 ABI it is the responsibility of the callee to pop the return address from the stack pointer and increase the stack pointer. Since the code of external functions is not present in the binary, every time an external function is called, the stack grows without being corrected. In case if the base pointer is not used (e.g., in optimized code, or if the no-frame-pointer option was specified) this will also lead to the stack corruption as all variables will shift. This corruption results in an incorrect interpretation of a program and in case of taint analysis will introduce aliasing between neighboring stack variables.
The solution is to appropriately increase the stack pointer every time we return from a call from the Lisp Machine back to the Primus Machine. This will …
=> adds x86 stack pointer handling for external calls

lib/bap_primus/bap_primus_env.ml
Primus generates a new random value every time `Env.get` is called with an unbound variable.
This PR changes this behavior and makes Primus remember the generated
value, i.e. bind such variable at first time its value was requested.
=> preserves random values in Primus

.travis.yml, plugins/x86/x86_lifter.ml
The signed division operation was improperly encoded in BAP since long
time ago (probably since re-introduction of x86 in 0.9.x, back in
2014). As reported by @icemonster (#961), the overflow check was
incorrectly treating singed integers and any signed division by a
negative number was triggering the division error exception.
A small history research showed that in BAP 0.8 the overflow check
was commented out for signed division, with a corresponding (and
wrong) comment that it should be implemented and how it should be
implemented. It looks like later, during porting this code was
uncommented.
The new implementation implements a correct check as well as tweaks
the code so that it now produces a more compact and readable code, as
well as the lifting code is also now more readable and …
=> fixes signed division and tweak both division representations

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_generator.ml, lib/bap_primus/bap_primus_memory.ml
Primus self seeding generators weren't storing their state and were recreating themselves on every call, which basically turned them into static zero generators.
This PR fixes them, so now we should observe random values read from uninitialized memory (note that our malloc allocator initializes memory with all zeros). 
This PR fixes another issue that became apparent after the generator fix - our memory component wasn't memoizing values read from dynamic and static layers, therefore two consequent reads were generating different values. This is akin to the problem in Env fixed in #958.
=> Fixes primus self seeding generators

plugins/primus_promiscuous/primus_promiscuous_main.ml
In the promiscuous mode we fork a new machine on each new call, so that if the function doesn't return for any reason, we can continue exploration of the code located after the call. 
The stored continuation wasn't limited and was capturing the whole execution path, including the path in which the function was actually returning. That lead to quite funny false positives in our analysis. 
The continuation is now explicitly delimited with `halt`.
=>  limits the continuation at the call forkpoint in the promiscuous mode

.travis_install.sh, lib/bap_primus/bap_primus_interpreter.ml
When a call-return is filled in with the arguments we shouldn't
re-evaluate any actuals that are not `Out`, as `In` (obviously)
and `In Out` (not that obviously) argument actuals could be already
overwritten.
A deeper story. When the C language is detected and when we have a
prototype for a function, we classify arguments that are passed by
reference (i.e., those that are passed by a non-const referenced) as
`In Out`. However, when a value is passed by reference the reference
itself is passed by value.
The fun fact, or why we didn't notice it before. There are two places
where `call-return` observation is made, namely in the Primus
Interpreter and in the Primus Lisp Interpreter. The latter was always
doing the right thing - it was passing the input arguments, and
appended the output (as …
=> fixes arguments in the call-return observation

lib/bap_primus/bap_primus_interpreter.ml
Do not raise a CFI viloation, when the continuation finishes but we
didn't issue any prompts. It usually corresponds just to an execution
of an arbitrary function from a top-level.
This also opens an avenue for making our CFI violation more
informational, since the only left case will have concrete instances
in a form of two destinations - expected vs taken.
=> relaxes CFI check in the Primus Interpreter

plugins/primus_lisp/lisp/simple-memory-allocator.lisp
So far our simple-memory-allocator was always filling the allocated
memory with zeros. The proposed implementation adds two parameters
the first one, `*malloc-initialize-memory*` controls whether memory is
initialized at all, and the second one, `*malloc-initial-value*` is
the value that is used to fill in the allocated memory, when the first
parameter is set to `true`.
By default, we set `*malloc-initialize-memory*` to false, so that PR
changes the behavior of Primus. Now the heap memory is randomized, so
if it breaks your analysis the set `*malloc-initialize-memory*` to `true`.
=> parametrize Primus Lisp malloc with initialization strategy

configure
It works only in the loops. Spotted the warning with [shellcheck](https://github.com/koalaman/shellcheck).
See [SC2105](https://github.com/koalaman/shellcheck/wiki/SC2105) explanation at their wiki:
> `break` or `continue` was found outside a loop. These statements are only valid in loops. In particular, `break` is not required in `case` statements as there is no implicit fall-through.
=> `break` doesn't work in `case` for shell

lib/bap_types/bap_bitvector.ml
Previously, when a signed bitvector was converted to an OCaml integer
it was sign-extended. This behavior is now restored, e.g.,
```
val n_two : Bap.Std.Word.t = 6
- : int = -2
- : int = 6
```
Note, also that the new implementation is still not exactly the same
as the old and subsumes the old, for example, in BAP 1.x the following
will raise an error:
```
Word.to_int64_exn (Word.of_int64 0x9a693d39c794d099L);;
```
and therefore the old code was using an explicit `Word.signed` to
trigger the signed extraction, which was probably wrong. In BAP 2.x
no matter whether the value is signed or not, if it fits the target
representation it will be converted, e.g.,
```
- : int64 = -7320252400943181671
- : Bap.Std.Word.t = 0x9A693D39C794D099
- : int64 = -7320252400943181671
- : int64 = …
```
=> restores the old behavior of the Word.to_int* wrt to signed values

plugins/primus_lisp/lisp/stdlib.lisp
`atexit` was declared as a function with no return value:
```
(defun atexit (cb)
(declare (external "atexit")))
```
although it should return an integer.
And that could lead us to a type error in primus. So let's just asssume that `atexit` is always successful
and returns 0.
=> fixes lisp `atexit` declaration

lib/arm/arm_utils.ml
So far we were using it/then/else statements to represent conditional
movements in ARM, which were, in turn, translated into 3 basic blocks.
This patch will translate them into ite expressions which leads to a
much more compact representation, especially in optimized ARM code,
which uses a lot of conditional moves.
In the implementation we predicate only moves to physical registers,
and leave temporary variables as it is, since we expect that the
temporary variable won't escape the scope of the predicated
instruction.
=> represents ARM conditionals with ite-expressions

lib/bap/bap.mli, lib/bap/bap_project.ml, lib/bap_image/bap_image.ml, lib/bap_image/bap_image.mli, lib/bap_llvm/bap_llvm_ogre_coff.ml, lib/bap_llvm/bap_llvm_ogre_elf.ml, lib/bap_llvm/bap_llvm_ogre_loader.ml, lib/bap_llvm/bap_llvm_ogre_macho.ml, lib/bap_llvm/bap_llvm_ogre_samples.ml, lib/bap_llvm/bap_llvm_ogre_samples.mli, lib/bap_llvm/bap_llvm_ogre_types.ml, lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_elf_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp
The current implementation is heavily influenced by the segmented view on the memory layout of a program. For historical reasons, the ELF representation of segments stopped to represent accurately the memory layout of the program, see #973 for more details. As a result, we ended up disassembling regions of memory which are clearly data (like `.rodata`) which reside in the executable segments. 
This PR introduces a new abstraction, called `code-region` since we don't want to overload the meaning of the segment/section anymore. All supported backends are implementing this abstraction in their specific manner (some are trivial, like COFF, some are not, like ELF)
The good thing about all the file types is that each of them has a section layout where sections have flags, that makes it possible …
=> introduces a more fine-granular view on the image memory

lib/bap_sema/bap_sema_lift.ml
This PR fixes a bug introduced by #987 and finally prunes return edges for conditional calls, while the previous PR actually pruned call edges.
=> fixes return edges pruning for conditional calls

lib/bap_sema/bap_sema_lift.ml, lib/bap_types/bap_ir.ml
This PR fixed a couple of minor bugs which were the reason why
in some cases, bir attributes weren't survived in map-alike
operations.
For example, `address` attribute was lost in case of conditional calls:
```
.address 0x401492
0000eeba: ZF := 0 = #1342
0000eec5: when ~ZF goto %0000d05b
0000fef4: goto %0000087d
```
And this PR fixes it:
```
.address 0x401492
0000eeba: ZF := 0 = #1342
.address 0x401496
0000eec5: when ~ZF goto %0000d05b
0000fef4: goto %0000087d
```
=> preserves bir attributes

lib/bap_disasm/bap_disasm_insn.ml
The instructions properties are computed from the semantics tags
provided by a backend and from the BIL provided by a lifter.
There was a bug the algorithm that was analyzing the BIL code,
which, in particular, lead to a classification of a machine instruction
as a barrier, when it wasn't.
When the semantic tags were inferred from the BIL we didn't accumulate
newly inferred tags to the list of existing ones but, instead, were
overriding it. As a result, if an instruction contained more than one
jump only the last jump was taken into account. This is a rare case,
that was happening with the rep prefixed instructions (which had three)
jumps with the latter being unconditional.
Therefore such instructions were classified as barriers.
First, we accumulate tags to make sure we won't override …
=> fixes instruction properties

lib/bap_disasm/bap_disasm_calls.ml, lib/bap_disasm/bap_disasm_calls.mli, lib/bap_disasm/bap_disasm_symtab.ml, lib_test/bap_project/test_project.ml
The subroutine packing algorithm is responsible for partitioning a set
of basic blocks into a set of disjoint sets each denoting a subroutine,
such that in each set there is a designated block called entry which
dominates all other blocks in this set.
In the ideal world, this partitioning is naturally induced by the
dominators tree of a graph. However, a dominator tree is undefined for
a graph that contains unreachable nodes.
Our new subroutine packing algorithm, introduced with BAP 2.0 alpha
release, solved this problem by connecting all unconnected components
to the root node, thus promoting entries of unconnected components to
subroutine entries. This led to a correct but very unprecise result,
e.g., for x86 we have x2 to x10 more partitions than true
subroutines. Mostly due to lots of …
=> more precise subroutine packing

lib/graphlib/graphlib_graph.ml
The fixed point solver accepts an initial solution, which in turn
could be a solution for the previous attempt. Originally, it was
assumed that the solution is applied to the same graph and that
a solutions could be only refined on the same graph. Therefore, if
applied to a different graph all solution entries that didn't have
a corresponding entry in the new graph were removed from the solution.
It turns out that it is quite useful to apply the same solution to
different graphs even (and especially) when they are not
intersecting.
This PR proposes to keep all entries in the solution passed to the
fixed point computation. It will update those fields that were
changed, leaving those that weren't intact, basically guarantees that
the newly computed solution contains the superset of the old …
=> preserves the solution passed to the fixed point solver

lib/bap_future/bap_future.ml
under some circumstances it was overriding the waiters list and thus breaking the chain.
=> fixes a bug in the future's bind operator

plugins/x86/x86_lifter.ml
The old representation inherited from BAP 0.x was representing
`repz<code>` as
```
if (RCX = 0) jmp next;
<code>;
RCX := RCX - 1;
if (RCX = 0)
jmp next;
if (ZF)
jmp start;
```
where `next` and `start` were concrete addresses of the current and
the next instructions. It goes without saying that such code
has a very bloated graph representation.
A more tight representation, which could also be nicecly reified into
a graph could be produced using BIL's `while` statement, which is
reflected to the Core Theory `repeat` term. The same instruction will
now have the following representation:
```
$0 := true;
while (RCX <> 0 & $0) {
<code>;
RCX := RCX - 1;
$0 := ZF;
}
```
which is reified into the following IR:
```
entry:
#0 := 1
goto head
body:
<code>
RCX := RCX - 1
#0 := ZF
goto tail
head:
goto …
```
=> represents rep prefix with the while statement in x86

plugins/primus_x86/primus_x86_loader.ml
In BAP 2.0 we have a more conservative disassembler. And while previously, only the first instruction of a PLT entry was disassembled, now we're getting the whole entry.
Unfortunately, the more precise disassembly hits analyses based on Primus. At least on x86/x86-64 targets. Previously, we got an unresolved call exception as soon as we enter a PLT entry, while now Primus follows to the whole chain of PLT resolution mechanism, like in the next example with call to free:
```
400560: pushq  0x200aa2(%rip)     # 601008 <_GLOBAL_OFFSET_TABLE_+0x8
400566: jmpq   *0x200aa4(%rip)    # 601010 <_GLOBAL_OFFSET_TABLE_+0x10>
40056c: nopl   0x0(%rax)<free@plt>:
400570: jmpq   *0x200aa2(%rip)        # 601018 <_GLOBAL_OFFSET_TABLE_+0x18>
400576: pushq  $0x040057b: jmpq   400560 <_init+0x28>>
```
which …
=> initializes PLT GOT in Primus

lib/bap_primus/bap_primus_interpreter.ml
Before this PR we were emitting the `leave-*` events even when a term
didn't evaluate normally (but instead raised an exception). As a result
event handlers were invoked in the context where the term was partially
(if at all evaluate), while they were expecting that the evaluation was
successful. This led to a few undefined variables and other errors.
Even worse, since the `leave-*` events were posted in the exception
handler, it was possible for the event handler to raise an exception on
its own, which was escaping the original exception handler and breaking
havoc and significantly affecting performance.
=> prunes Primus leave events on abnormal evaluation

.run_travis_tests.sh, opam/opam
It turned out that we are not running all the available unit tests on Travis.
We can't launch our unit tests just by running `make test` on Travis, because we use stages and don't even have a code on the stage with unit tests. Instead, we have to install test executables on the
build stage and then manually launch them on the next stage. And for some reason, we install and run only the most important one but not all of them.
This PR fixes it and run all the tests we currently have.
=> runs ALL the unit tests on Travis

oasis/build, oasis/bundle, oasis/common, oasis/main, oasis/plugins, oasis/recipe, oasis/recipe-command
There are many new libraries after #1005. And this PR fixes some of their's
oasis files in order to install bap from `opam`
=> fixes issues in the oasis specification introduced by #1005

lib/bap_disasm/bap_disasm_driver.ml, plugins/ida/ida_main.ml
TL;DR; Warning: this PR changes the semantics of BAP 1.x branchers, they shall not reference the fall-through destination in their outputs for non-control-flow affecting instructions. Please, consider updating your custom branchers, if you have one.
In BAP 2.0 a set of destinations of an instruction is stored in its `dests` slot. This set, if known, shouldn't include the fall-through destination and only control-flow instructions shall have a non-empty
set of destinations. Since previously our branchers were including all destinations, there was an extra filtering procedure in the disassembler, which was removing the fall-through destination, in case
if it still present, to prevent issues with old BAP 1.x branchers.
We had to remove this extra step since clang is using the `jmp next` …
=> don't treat `jump next` as fall

.gitignore, Makefile, oasis/bap-std, oasis/bap-std.files.ab.in, oasis/toplevel, src/bap_frontend.ml, src/baptop.ml, tools/postinstall.ml.ab
For some yet to be discovered reasons plugins weren't evaluated during
the baptop utility startup. The were loaded, linked, but no
side-effects occured. Not sure what is going in utop internals, but
just loading the "bap.top" library works fine, and it is also
simplifies the implementation.
I've also restored the postinstall hook, that installs manpages for
bap and utilities. The utilities (such as old baptop script and
ppx-bap) are no longer installed, because they are obsolete, but the
man pages are now installed (and now in a proper place).
The postisntall hook is moved to the Makefile, since it has to be run
after plugins are installed. It is predicated with the existence, so
it won't be run on each package installation during opam installation,
only for the bap-std package which …
=> fixes a plugin initialization issue in baptop, restores postinstall

lib/arm/arm_utils.ml, lib/bap/bap.mli, lib/bap_disasm/bap_disasm_driver.ml, lib/bap_disasm/bap_disasm_rec.ml, lib/bap_disasm/bap_disasm_symbolizer.ml, lib/bap_piqi/bil_piqi.ml, lib/bap_piqi/type.piqi, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_lisp_program.ml, lib/bap_primus/bap_primus_memory.ml, lib/bap_types/bap_arch.ml, lib/bap_types/bap_arch.mli, lib/bap_types/bap_bil_adt.ml, lib/bap_types/bap_common.ml, lib/microx/microx_concretizer.ml, lib/monads/monads_monad.ml, lib_test/bap/run_tests.ml, plugins/bil/bil_lifter.ml, plugins/bil/bil_semantics.ml, plugins/bil/bil_semantics.mli, plugins/elf_loader/elf_loader_main.ml, plugins/mc/mc_main.ml, plugins/mips/mips.ml, plugins/primus_propagate_taint/primus_propagate_taint_main.ml, plugins/primus_x86/primus_x86_loader.ml, plugins/x86/x86_utils.ml
This PR introduces an `unknown` architecture to enable analysis of
programs that are not binary, such as JVM or CLR bytecodes. This
change is also in line with the LLVM which also has the unknown
architecture. Additionally, the unkwown architecture could be later
refined, since it is the minimal element of the architecture
domain. That let us develop analyses that will detect architectures,
thus making the architecture a target of analysis rather than a
constant input.
In general, in BAP 2.0 we're moving away from the Arch.t type for
encoding a wide range of arhictectual properties of computing units
which we model. Mostly because those properties are mostly structural
and could be hardly captured with jsut a nominal string (even if this
string is triple).
This PR also sweeps through code …
=> adds unknown architecture

lib/bap_byteweight/bap_byteweight.mli, lib/bap_core_theory/bap_core_theory.ml, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_manager.ml, lib/bap_core_theory/bap_core_theory_manager.mli, lib/bap_primus_machine/bap_primus_machine.mli, lib/graphlib/graphlib.mli, oasis/common, plugins/bil/bil_ir.ml, plugins/bil/bil_lifter.ml, plugins/bil/bil_main.ml
Polishes documentation as well as fixes the theory declaration
function. And finally bumps the version to 2.0.0.
Whle revising the documentation I've noticed that the interface of
theory declaration is not allowing references to other theories as it
isn't wrapped in the knowledge monad as it should be. I fixed it, but
immediately fell into the trap of a recursive instantiation. Indeed, a
theory may require itself as a base, which will lead to an infinite
recursion and runtime failure. Since it is so easy to fall into this
trap, the implementation has to be robust enough and either forbid
this, with an appropriate error message, or allow it, with an
appropriate semantics. We chose the latter, since our theories are
domains we have a sane semantics for recursive theories (well, this
is what …
=> BAP 2.0.0 release (candidate)

README.md
Forgot to add the mc command, additionally fixes the Boeing misspelling noticed by @XVilka in #1020. 
Also adds a link to the bap manpage. 
Besides, if you didn't know, you can now do `man bap` and read the manpage locally.
=> Adds a description of the mc command, fixes boeing misspelling

lib/knowledge/bap_knowledge.ml, oasis/common
The Knowlege.run was computing every possible slot of a value, to ensure that all stored computations are triggered. However, for classes that have a lot of slots it was unnecessary slow, especially when none of those slots are having any stored computations.
A simple fix, is to ignore slots without stored procedures turns out int x4 improvement of the run function for the program class. It doesn't affect the disassemble command, which wasn't using the run command, but affects `mc` and `objdump` which were using it.
=> makes Knowledge.run more efficeint, bumps version

plugins/legacy_llvm/legacy_loader_main.ml, plugins/map_terms/map_terms_main.ml, plugins/mips/mips.ml, plugins/mips/mips_arithmetic.ml, plugins/mips/mips_branch.ml, plugins/mips/mips_conditional.ml, plugins/mips/mips_divide.ml, plugins/mips/mips_load.ml, plugins/mips/mips_logic.ml, plugins/mips/mips_main.ml, plugins/mips/mips_multiply.ml, plugins/mips/mips_shift_and_rot.ml, plugins/mips/mips_store.ml, plugins/print/print_main.ml, plugins/run/run_main.ml, plugins/x86/x86_btx.ml, plugins/x86/x86_cdq.ml, plugins/x86/x86_cmpxchg.ml, plugins/x86/x86_endbr.ml, plugins/x86/x86_mov.ml, plugins/x86/x86_mov_offset.ml
A few plugins weren't respecting the requirement for no side effects
on the load time and were registering their functions even when
explicitly disabled, e.g., --no-mips, --no-x86 didn't really work.
=> compels plugins to respect the Bap_main rules

plugins/mc/mc_main.ml
Now `bap mc` and `bap objdump` will not stop on errors and continue
disassembling unless `--stop-on-error` option is passed. A new option
was added, that will print something when an invalid instruction is
met. If it not specified invalid instructions are silenced.
Fixes options `--show-size` and `--show-kinds` which weren't ouputting
anything due to the incorrect defaults.
=> adds --show-invalid, --stop-on-error to mc/objdump, fixes show-size

lib/bap_main/bap_main.ml, lib/bap_main/bap_main.mli, lib/bap_recipe/bap_recipe.ml, lib/bap_recipe/bap_recipe.mli, plugins/recipe_command/recipe_command_main.ml, src/bap_frontend.ml
After the introduction of the commands in bap, the recipe system wasn't updated and it was only possible to write recipes for the default `disassemble` command. We use recipes to pack our analysis into self-contained entities and we would like to benefit from commands, e.g., we would like to be able to implement analyses that do not require a full disassembly of the target file.
This PR adds the `command` stanza to the recipe grammar. The new command stanza didn't play well with the hack that was prepending the `disassemble` command when the first argument was a file. No worries, the command is still optional, we were just able to find a much better solution, which is not a hack. Now it is the responsibility of `Bap_main.init` to set the default command if no command was specified. So no …
=> adds `command` to recipes, removes the default command hack

lib/bap_future/bap_future.ml, lib/bap_plugins/bap_plugins.ml, lib/bap_types/bap_bitvector.ml, lib/regular/regular_data_write.ml, oasis/common.tags.in
Previously, we decided to disable the Jane Street code style checks as a fast solution, but it turned out that it is easier to adopt their style than to fight with it. To disable the checks, we used the _tags file,
but since we have a global repository the tags file affected all subprojects, even those that do not use the ppx-jane preprocessor, thus breaking packages that do not explicitly depend on ppx-jane.
Also, in #957 we accidentally introduced a dependency on a newer version of `zartith` by using the `Compare` module. We will now use plain compare et alas functions so that the old version of `zarith` could be still used with BAP.
=> enables the Jane Street code style

plugins/primus_mark_visited/primus_mark_visited_main.ml
Only defs of a visited block were marked as visited. The block itself
wasn't marked, neither anything was marked on blocks that didn't have
any definitions. In particular this was breaking Saluki, which totally
ignores unvisited blocks.
=> fixes the visited attribute attaching in primus-mark-visited

lib/bap/bap.mli
This function does nothing, but we forgot to add the deprecation warning to it during the 2.0 release.
=> dedocuments the function and adds the warning alert

lib/bap_main/bap_main.ml
When this option is set, and the `-L` or `--plugin-path` option
is not used, then plugins path will be fetched from the enviroment
variable. However, the plugins library will also look at the same
variable and add the same set of paths to the search. Since this
variable should be local to the plugins library, and in fact is a
part of its interface we should just remove this from the bap-main
command line interface.
Fixes #1044
=> prevents cmdliner from fetching plugins path from environment

lib/bap_c/bap_c_attr.ml, plugins/callsites/callsites_main.ml
When attributes are assigned to a newly created synthetic argument term
in the `callsites` plugin, we don't take into consideration attributes
from the original argument term. This PR fixes this and now all the
attributes from origin argument term are assigned to the new one.
=> fixes arguments attributes in the `callsites` plugin

lib/bap_taint/bap_taint.ml
The `finished` observation may not reach a receiver, because of unspecified order in which primus components are executed. E.g. greedy scheduler can intercept `finished` observation and kill a machine. As a result, no taint is ever finalized, which hits any analysis that depends on it. And this PR introduces taint finalization on the `halt` observation, which happens before `finished`.
=> fixes taint garbage collector

lib/bap/bap_project.ml, lib_test/bap_project/test_project.ml
The attribute was no longer set and the test case that was watching
this is no longer present (it could be that it was present only in
my imagination though). The test case is added now.
=> fixes the missing filename attribute

plugins/primus_lisp/lisp/stdio.lisp, plugins/primus_lisp/primus_lisp_io.ml, plugins/primus_lisp/primus_lisp_main.ml
In Primus Lisp, we have channel redirection which makes files from the
host system visible to the emulation layer. Underneath the hood, we
use common OCaml channels to model files (and probably we should use
Unix file descriptors), and when a file is mapped, we open both input
and output channel. However, when we open the input channel, the file
is truncated, with all the ramifications.
The quickfix is to add the `append` flag. The long-term solution would
be switching to Unix file desciptors and passing flags to the `open(2)`
function, see #1050.
=> prevents overwriting of a file in the input channel redirection

plugins/primus_mark_visited/primus_mark_visited_main.ml
When a function is stubed by a Primus Lisp function the original plt
entry is not evauluated therefore it is not marked as visited, as a
result we have incorrect statistics on visited blocks.
We now track all primus-lisp-call observations and mark the
corresponding plt entry (or whatever matches with the called address)
as visited.
=> tweaks primus-mark-visited to mark called stubs as visited

lib/bap/bap.mli, lib/bap_sema/bap_sema.ml, lib/bap_sema/bap_sema_free_vars.ml, lib/bap_sema/bap_sema_free_vars.mli, lib/bap_sema/bap_sema_ssa.ml, lib/bap_types/bap_ir.ml, lib/bap_types/bap_tid_graph.ml, lib/bap_types/bap_tid_graph.mli
1. implements liveness analysis for subroutines and provides it
as [Sub.compute_liveness] which returns a fixed point solution to
the variable liveness property.
2. uses liveness to compute free variables when a subroutime is not
in the SSA form
3. Sub.to_graph now returns a fully connected graph with two
pseudo-nodes, [start], and [exit] (we keep doing every time we need to
do some graph computation, so let's make it official). This
pseudo-nodes are constants defined in the [Graphs.Tid] interface.
Context
=======
We used to rely on the dominators tree to compute the set of free
variables when the SSA form is not available. It was an optimization,
as by that time we didn't have the fixpoint function and didn't want
to compute SSA just for getting free vars. It was also returning an …
=> provides liveness analysis and uses liveness for Sub.free_vars

lib/bap_disasm/bap_disasm_calls.ml, lib/bap_disasm/bap_disasm_driver.ml
Until this PR we were marking call destinations as subroutines at the
same time as we were building the callgraph, therefore if a caller was
visited before callee (and the callee wasn't yet marked as a function
start) we were missing a valid function start and our partitioning of
the whole program CFG into subroutines was incorrect.
The reason why we were delaying this information until it is too late
was two-fold. First, we can't mark a callee as a function start as
soon as we have discovered an instruction that targets it, as this
instruction may not be a part of a valid code chain, so we may need
later to cancel this instruction, and therefore retract this
information. Since our knowledge base doesn't allow retracting or
negating, we were postponing this information until we finish …
=> provides information about call destinations as soon as possible

plugins/disassemble/disassemble_main.ml
The disassembler state was cached and even loaded from the
cache... but never used. It is now significantly faster :)
=> caches the disassembler state

lib/bap_primus/bap_primus.ml, lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_interpreter.mli, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_lisp.mli, lib/bap_primus/bap_primus_machine.ml, lib/bap_primus/bap_primus_main.ml, lib/bap_primus/bap_primus_memory.ml, lib/bap_primus/bap_primus_observation.ml, lib/bap_primus/bap_primus_observation.mli, lib/bap_primus/bap_primus_types.ml, lib/bap_primus/bap_primus_value.ml, lib/bap_taint/bap_taint.ml, plugins/primus_limit/primus_limit_main.ml, plugins/primus_test/primus_test_main.ml
This PR brings a few small optimizations that together make Primus run 3 to 4 times faster. E.g., in the current master branch, it takes more than 150 seconds to run the memcheck analysis on /bin/true, while in this branch it terminates in 40 seconds (with the same results, coverage, and the number of states). This is 3.5 improvement in speed. YMMV of course as it depends on the analysis and appetite. Speaking of the appetite, this branch implements lazy notifications, so that if an observation is not subscribed than it is not provided. Therefore, we don't have to pay for unused notifications. As a result, the fewer observations you watch the faster your analysis will run.
Since Primus 2.0 is stall far from being ready, we decided to backport some of the ideas to the current version. In …
=> optimizes Primus observations

lib/bap/bap.mli, lib/bap_core_theory/bap_core_theory_parser.ml, lib/bap_disasm/bap_disasm_basic.ml, lib/bap_disasm/bap_disasm_basic.mli, lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_linker.mli, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_lisp.mli, lib/bap_primus/bap_primus_lisp_var.ml, lib/bap_sema/bap_sema_lift.ml, oasis/primus-lisp, plugins/bil/bil_ir.ml, plugins/bil/bil_lifter.ml, plugins/bil/bil_lifter.mli, plugins/bil/bil_main.ml, plugins/bil/bil_semantics.ml, plugins/bil/bil_semantics.mli, plugins/primus_lisp/lisp/floats.lisp, plugins/primus_lisp/lisp/init.lisp, plugins/primus_lisp/lisp/llvm-x86-64-floats.lisp, plugins/primus_lisp/lisp/types.lisp, plugins/primus_lisp/primus_lisp_ieee754.ml, plugins/primus_lisp/primus_lisp_ieee754.mli, plugins/primus_lisp/primus_lisp_primitives.ml
TL;DR; This branch adds a new feature that allows us to stub instructions in Primus Lisp, by turning certain instructions (including those for which we do not know semantics) into calls to intrinsics. This gives us two important advantages:
1. we can now easily stub/lift unknown/unsupported instructions in Primus Lisp 
2. we can prune complex (read SSE/AVX,FP) instructions (which take megabytes of BIL code) and use the host CPU for the computation. That will vastly improve code coverage and analysis speed for programs that use floating-points and SSE extensions.
The `--bil-enable-intrinsic` option specifies which instructions we would like to translate into the calls to intrinsics. A call to an intrinsic is no different from a normal call. For passing arguments we used a set of special …
=> adds intrinsics

opam/opam
This PR:
- preserves user configuration file if exists in the config test
- applies `primus-lisp-type-check` option in run test
fixes #1065
=> fixes the config and run tests

lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_lisp.ml, opam/opam, plugins/primus_limit/primus_limit_main.ml
The new clocks, as introduced in #1061, were ticking too fast (roughly 3
to 5 times faster) so we recalibrated them to be closer to the old
clocks that were using binop/unop/load/store events
Also fixes a bug in the primus-limit command line parsing function.
=> recalibrates Primus clocks

oasis/bap-std, oasis/bap-std.files.ab.in, oasis/common, oasis/common.files.ab.in
The manpage is not installed when bap is installed via opam as when
post-install happens the bap frontend is not yet installed. We will
now update and install the manpage every time a new bap package is
installed.
=> fixes man pages installation

oasis/common, tools/postinstall.ml.ab
After #1073 the installation from `opam` on a fresh switch is broken due to the
dependency on `fileutils` in the `postinstall` script. This PR implements
`postinstall` without it.
=> drops fileutils from the postinstall script

plugins/primus_print/primus_print_main.ml, plugins/primus_systems/systems/core.asd, plugins/primus_test/lisp/memcheck-malloc.lisp
This is an essential component that enables observation printing, so
we should probably have it in all our systems.
Also tweaked a bit the description of the component, the old one was
quite vague.
=> adds the observation printer to all core systems

docker/xenial/testing/Dockerfile
We need to move the quotation mark inside. Otherwise the docker image builds but then cannot be executed.
=> correct dockerfile typo

lib/bap_llvm/llvm_disasm.cpp
The LLVM disassembler is broken for aarch64 and segfaults with the NULL-pointer dereference (segmentation fault) on versions below 8.0. There is no clear mitigation (passing a non-NULL pointer for the symbolizer function results in unpredictable behavior) and given that aarch64 is not a first-tier architecture for us yet, we will just disable it for older versions of LLVM.
fixes #1081
=> disables llvm (< 8.0) disassembler for aarch64

lib/bap_core_theory/bap_core_theory_var.ml
BIL and Core Theory variable literals can contain only a specific
set of valid characters. This approach doesn't play nice with various
manglers and non-C languages as well as contradicts with our own
tradition as we generally tend to allow any character in variables,
see our Knowledge variables for example (and which are used underneath
the hood of CT and BIL variables).
One of the real-world examples where bap fails is the new C++ code
with lambdas, that uses `#` for anonymous variables.
In this proposal we allow any string (including the empty one) to be
used as a variable name. First of all, we escape any non-printable or
whitespace characters. We also escape '.' as we use it for variable
versioning. Next, if a prospective variable name starts from a digit,
is empty, or starts with …
=> allows any character in the variable name

lib/bap_c/bap_c_abi.ml, lib/bap_c/bap_c_abi.mli, plugins/arm/arm_gnueabi.ml, plugins/mips/mips_abi.ml, plugins/powerpc/powerpc_abi.ml, plugins/x86/x86_abi.ml
This adds 2 new functions to C.Abi, to be able to register a new abi processor
and then access it later.
The processors are stored in a mutable StringMap with the abi names as keys, using the function `C.Abi.register name abi`.
They can then be reached from any plugin using `C.Abi.get_processor name`.
=> exports abi processors

plugins/api/api/c/posix.h
this PR adds several functions in `posix.h` header:
```
int remove(const char *);
int rename(const char *, const char *);
int __isoc99_fscanf (FILE *__restrict __stream, const char *__restrict __format, ...)  __attribute__((warn_unused_result));
int __isoc99_scanf (const char *__restrict __format, ...)  __attribute__((warn_unused_result));
int __isoc99_sscanf (const char *__restrict __s, const char *__restrict __format, ...)  __attribute__((warn_unused_result));
int _IO_feof(FILE *stream);
int _IO_getc(FILE *stream);
int _IO_putc(int c, FILE *stream);
int _IO_puts(const char *s);
```
=> updates posix.h header

plugins/primus_lisp/lisp/llvm-x86-64-floats.lisp
x86 floating-point instructions names differ between different llvm versions.
For example, here are the results for llvm 6.0 and llvm 9.0:
```
echo 'addsd -24(%ebp), %xmm0' | llvm-mc-6.0 --arch=x86-64 --show-inst
.text
addsd	-24(%ebp), %xmm0        # <MCInst #219 ADDSDrm
```
```
echo 'addsd -24(%ebp), %xmm0' | llvm-mc --arch=x86-64 --show-inst
.section	__TEXT,__text,regular,pure_instructions
addsd	-24(%ebp), %xmm0        ## <MCInst #328 ADDSDrm_Int
```
The latter instruction has the `_Int` suffix, while the former does not.
As a result, our tests don't pass when this suffix presents.
This PR fixes this problem and stubs the suffixed names also.
=> updates floats intrinsics

oasis/optimization, plugins/optimization/optimization_data.ml, plugins/optimization/optimization_data.mli, plugins/optimization/optimization_main.ml
This PR fixes #1092 :
The optimization pass may make some code unreachable, propagating a constant value to a branch guard.
For example, some code can become unreachable due to jumps that are
never taken because of condition:
```
0000046a: when 0 goto %0000045b
```
Or due to the previous jump that is taken always:
```
00000471:
00000473: goto %00000451
00000474: goto %00000455
```
This PR fixes this problem and removes blocks that are unreachable due to infeasible jumps and these jumps as well.
Also, this PR fixes the computation of digest in the optimization pass. Previously, digest for each subroutine contained tids, that is not quite right, because a program can have different tids on each bap execution, and actually it happens quite often. And it leads to the cache explosion since …
=> prunes unreachable code in the optimization pass

lib/bap_types/bap_eval.ml
`Bil.Eval` still relies on the assumption that memory can address only values of 1-byte length. And once the stored/loaded value size differs from memory value size, we try to simplify an expression. But the simplification in its turn can leave an expression unchanged since it takes into account both memory value size and size of a stored/loaded value. And that's how we get an infinite loop: since an expression is unchanged, we try to eval it again, simplify, and so on.
This PR fixes this problem and checks both the size of the stored/loaded value and memory value size.
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/848
=> fixes Bil.eval memory operations for different sizes of values

plugins/primus_lisp/lisp/limit-malloc.lisp
This PR sets malloc parameters to limit the maximum size of the memory
that can be allocated by malloc. This feature is used frequently in analysis so it's time to move it to the main bap repository.
=> adds limit malloc

lib/bap_llvm/llvm_loader_stubs.c, plugins/x86/x86_mov_offset.ml
This PR fixes:
1) a bug with llvm version normalization in x86 lifter
2) warnings in our llvm backend
=> fixes bug with llvm version in x86 lifter 

plugins/primus_symbolic_executor/primus_symbolic_executor_main.ml
If an assertion doesn't contain a symbolic value then we were having
an empty set of constraints, which trivially were true. In other
words, `assert true` doesn't hold.
This PR fixes this by treating non-symbolic values as symbolic
constants.
=> fixes trivial assertions

oasis/common
This is a techinical PR that just bumps the version to designate the
start of developement of the new (2.2.0) version of BAP that will be
released roughly in six months.
Ok, it also removes `-j 0` to remove the stress from the CI system.
=> starts the new development version of BAP

plugins/primus_taint/lisp/sensitive-sinks.lisp, plugins/primus_test/lisp/check-value.lisp
Since now Primus Lisp operations are expressed in terms of the Primus
interpreter (in order to enable analysis of the code that is stubbed
in Primus Lisp), we have the `eval-cond` signal sent every time we
make any comparison operation in Lisp, e.g., `if`, `when`, `or`,
`and`, etc. Therefore, any method for `eval-cond` that does any
comparison operation (branching) will stall in an infinite loop.
A workaround is to use another observation that occurs only on jumps
that are situated in the binary code, but in general we shall address
it and make sure that `eval-cond` method is usable.
fixes (as a workaround) #1121
=> fixes an infinite loop in certain Primus Lisp analyses

plugins/cache/bap_cache.ml
we shall not take the whole chaching directory, but create a subfolder there.
=> handles correctly XDG_CACHE_HOME

lib/bap_disasm/bap_disasm_driver.ml
TL;DR; jumps that cross segments and section boundaries are now
treated more thoroughly so that if a jump instruction leads to an
invalid execution chain in some other segment, the we will cancel both
the chain in the other segment and the chain that led to that jump in
the current segment (before it was canceled up to the boundaries of
its own segment).
Partially fixes #1133, however since it is Thumb 2.0 binary for BAP it
is still mostly random data than something meaningful.
Problem
-------
Since 2.0 we have the incremental disassembler that supports
cross-sectional/cross-segmential jumps. As #1133 shows sometimes they
can go wrong as they were treated specially and had some preferences
that regular intersectional jumps didn't have. One of the invariants
of our disassembler is that …
=> implements better support for cross memory disassembling

.github/workflows/main.yml, opam/opam
Travis is too clunky, also it is possible to use new action template from https://discuss.ocaml.org/t/github-actions-for-ocaml-opam-now-available/4745
=> Try to use GitHub Actions

plugins/primus_lisp/lisp/stdlib.lisp
The implementation was missing the fact that envp is an array of
pointers to string, not an array of pointers.
Also, not sure if it is a bug or abi-specific, but env is not set,
then it is not null. Probably, it should be double-checked in the
loader part.
=> fixes getenv Lisp stub

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_symbolic_executor/primus_symbolic_executor_main.ml
The semantics of eval-cond and jumping observations is corrected. The conditional expression of the `eval-cond` observation now takes into account preceding guard conditions, which fixes wrong path constraints created by the symbolic executor as well as simplifies the symbolic executor code (which no longer requires the analysis of which branch is taken and which is not).
The conditional expression of the `jumping` expression, which is still always true, is now computed from all path constraints of the outcoming edges of the basic block, which simplifies taint analysis. 
Finally, we implement the `on-cond` Lisp signal in terms of the `jumping` observation. And while it sounds bad, as we broke the one-to-one correspondence between observation name and signal name, it restores the previous …
=> Tweak jumping and eval cond

plugins/primus_lisp/lisp/stdio.lisp, plugins/primus_lisp/primus_lisp_io.ml, plugins/primus_symbolic_executor/lisp/symbolic-stdio.lisp
Both shall return a value of type `int` but were returning a value of
type char. Not only it provoked type errors when the real `fgetc` was
linked to the binary, but it also was incorrect, since the actual
primitive was returning a value of type `int`.
=> fixes the `fgetc` stub and the `channel-input` primitive return type

plugins/primus_test/lisp/memcheck.lisp
It didn't prove to really have any benefits but clashes with regular heap overflow tracking. Fixes #1152.
=> removes the buffer tracking

plugins/primus_test/lisp/memcheck.lisp
Fixes a broken fix introduced with #1155 unfortunately this file is
not covered with CI, which we need to fix ASAP (see #1156, #1157).
=> removes the buffer tracking (second attempt)

tools/build_plugins.sh
on vanilla MacOS there is no `realpath` or `mktemp` that accepts
`-p`, but we can make it simpler and even nicer withour relying on
such an advanced and moder technology.
Note, a problem with github runners is that they are very far from
being clean systems, they have a lot of software preinstalled, so if
something works on them it doesn't really imply that it will work on
real systems.
Given that we need to add more docker images and test them at least
weekly.
=> makes build_plugin.sh more portable

lib/bap_disasm/bap_disasm_driver.ml
During disassembling we are processing instructions in the linear
not execution order and to detect if there is a fallthrough we were looking
at the `barrier` property of the last disassembled instruction, which,
in case of MIPS and other architectures with delay slots, wasn't even
a jump.
Instead, we should look into the disassembler state in which we have
recording for each barrier and which is even faster.
=> fixes barrier instructions with delay slots

.github/workflows/nightly-testing.yml, .github/workflows/weekly-regress.yml
We pin bap's repo to portably grab extra system dependencies needed for running the testsuite, but accidentally also reinstall bap.
=> tweaks nightly and weekly builds - do not install bap twice 

lib/bap_disasm/bap_disasm_calls.ml, lib/bap_disasm/bap_disasm_driver.ml, lib/bap_disasm/bap_disasm_driver.mli
Our control-flow graph representation is unable to handle cases when a
delay slot of some branching instruction becomes a target of a call or
a jump, because we do not allow the same instruction to belong to
several basic blocks (aka instruction sharing). When we encounter such a
case, our control-flow invariants are broken which leads to failures
downstream (e.g., we have duplicating term identifiers).
While it is possible that a delay slot might become a target of a
jump, in reality compilers are not generating such code (well, at
least we are not aware of such compilers) and the main source of calls
that target delays slots is Byteweight, which false positively
identifies them as function starts.
Since we don't have an option to represent such graphs right now, to
preserve our …
=> prevents delay slots from becoming a basic block start

lib/bap/bap.mli, lib/bap_disasm/bap_disasm.ml, lib/bap_disasm/bap_disasm.mli, lib/bap_disasm/bap_disasm_driver.ml, lib/bap_disasm/bap_disasm_driver.mli
The engine was introduced in BAP 2.0 but wasn't fully published or
documented.
Some parts of the interface were published but were lacking the
documentation, some were just missing.
We also publish the low-level interface to the disassembler engine,
which is totally new.
Last but not least we provide a precise description of the algorithm
and the interaction of the engine with the knowledge base.
=> publishes and documents the new disassembler engine

plugins/primus_symbolic_executor/primus_symbolic_executor_main.ml
When the symbolic executor tries to initialize a memory location that is not yet
mapped it fails with an error, when the location belongs to a memory
that wasn't set as symbolic (which is most likely just the default
virtual memory). Instead of failing, we shall just intialize the
memory location and let the pagefault handler of the memory randomizer
to map it for us.
=> enables unallocated memories in symbolic executor

docker/archlinux/Dockerfile
Looks like that the`llvm9` package was removed and it's the reason the build fails on `Archlinux`. This PR fixes it and installs `llvm` package that now provides the 10th version.
=> fixes build on Archlinux

oasis/objdump.setup.ml.in
By default, if no objdump was configured we should use `objdump`.
Note: was broken in #1179
=> restores the default objdump configuration as before #1179

docker/debian/testing/Dockerfile
adds the forgotten `--yes` key to `apt-get install`
=> fixes build on Debian-testing

.github/workflows/nightly-testing.yml
Our nightly tests on macOS fail with the next error while executing `opam depext -u bap` command:
```
Error: python@3.8 3.8.4 is already installed
To upgrade to 3.8.5, run `brew upgrade python@3.8`.
```
The `-u` flag in `opam depext -u bap` updates OS packages sets. In this case, `brew` becomes aware of the new available python version. Then, `opam depext` calls `brew install` with all the packages we depend on including `python`.
`macOS` on GHA comes with preinstalled `python 3.8.4` formula and the problem is that `brew install` fails if another version of the same formula is installed. The GitHub runner detects a non-zero exit code and the whole workflow is failed.
This PR fixes this problem by upgrading all the installed formulae via `brew update && brew upgrade` before calling `opam …
=> fixes nightly tests

lib/bap/bap.mli, lib/bap_image/bap_image.ml, lib/bap_image/bap_image.mli, oasis/specification, plugins/specification/specification_main.ml
The command will print the ogre specification of the file.  Also adds
the `Image.find_loader` function that enables direct access to the
image loaders.
=> adds the specification command

lib/arm/arm_mov.ml
Apparently, we did not support them so far and they are being used extensively in the PLT sequences thus preventing us from properly applying the relocations.
For the reference, see the ARM Architecture Reference Manual, ARMv7-A and ARMv7-R edition, section A4.4.1 ("Standard data-processing instructions").
=> implements support for ARM Modified Immediate Constants

oasis/radare2, opam/opam, plugins/radare2/.merlin, plugins/radare2/radare2_main.ml
The ocaml-radare2 library is suffering from a few issues and it is
easier and much more efficient to call radare2 directly.
Here the list of issues that we have with ocaml-radare2
1) leaking file descriptors (they are never closed)
2) suboptimal inter-process communication (to get a 100 bytes
ocaml-radare makes a hundred system calls)
3) lingering processes (partially fixed)
In fact, we don't really need to keep the process open as we run
radare2 once and immediately close, so it is much easier for us just
to pass the command using the `-c` command line option.
@Xvilka, I saw your fix and it is not yet working, the output channels
should be closed and exhausted for waitpid to return (or NOHANG)
should be passed. Also, without NOHANG, the code that sends signals is
actually unreachable. …
=> calls radare2 directly

plugins/radare2/radare2_main.ml
It looks like that radare2 command line interface varies a bit across
versions and we certainly shouldn't really fail if the radare2 process
has failed.
Also, sometimes, radare2 tries to take -isj as the name of the file,
instead of the file itself. So I moved it forward.
Fixes #1203
=> prevents BAP from failing when radare2 fails

.github/workflows/build-and-test.yml, .github/workflows/build-dev-repo.yml, .github/workflows/build-from-opam.yml, .github/workflows/nightly-testing.yml, .github/workflows/weekly-regress.yml
fixes https://github.com/BinaryAnalysisPlatform/bap/issues/1201
For every functional test, we create a folder in which we store log files. And in case of any fail, it will be easier to find a problem since we'll able to find a corresponded log file for the failed test.
Also, this PR fixes a minor bug in our Github Actions workflows: when we use `matrix`, we don't have multiple artifacts, depending
on matrix size. Instead, for every `upload-artifact` action we have only one artifact per workflow, i.e. artifacts are overridden.
This PR fixes this problem and names artifact according to the matrix element it is uploaded for, e.g. `log-ubuntu-4.07`
=> stores log files for functional test

docker/archlinux/Dockerfile
After we added `conf-radare2` dependency, the `bap` installation requires `radare2` to present in the system.
Unfortunately, `opam-depext.1.1.3` doesn't properly support `archlinux`,
so we have to install `radare2` manually.
=> fixes archlinux docker image

tools/bapdoc.ml
The default odig theme doesn't look as good as odoc theme, that's why we change it.
=> uses odoc theme for the documentation

lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli
Adds the `objects` function that returns a sequence of all objects in
the knowledge base.
Note, the interface is subject to change, but it looks good so far. We might also add some more low-level iterators, e.g., `Object.next : 'a obj -> 'a obj option` and `Object.first : 'a obj -> 'a obj option`, we will see if we really need them.
=> enables enumeration of objects in the knowledge base

.github/workflows/build-and-test.yml, .github/workflows/build-dev-repo.yml, .github/workflows/nightly-testing.yml, .github/workflows/weekly-regress.yml, .gitignore, .gitmodules, Makefile
The main reason is that opam recursively initializes submodules when
it installs bap from sources and given that our testsuite has a few
binaries along with the traces it sums up to 5Gb of space, which leads
to the out-of-disk-space errors when we build from docker. The easiest
solution would be to remove the testsuite from the main repo. Moreover,
having it as a submodule doesn't really help and is mostly a
nuisance.
The proposed solution is to just clone the testsuite (potentially we
can select a branch or a commit) in the test scripts. This is
basically the same as what is git doing for submodules but now it will
be under our control.
=> removes the testsuite submodule

plugins/primus_lisp/lisp/atoi.lisp, plugins/primus_lisp/lisp/posix.lisp, plugins/primus_lisp/lisp/string.lisp
Also publishes the ascii module and ato* functions, apparently, these features weren't included in the posix feature.
Thanks, @dtpeters for reporting this.
=> fixes the implementation of strncasecmp and strcmp models

.github/workflows/build-and-test.yml, configure-omake, lib/bap_llvm/OMakefile, lib/bap_llvm/llvm_elf_loader.hpp, opam/opam
Apparently, we were running our tests on LLVM 6, not LLVM 9 as we used to believe. This PR switches to LLVM 9 for running tests and fixes a bug that was not present in LLVM 6 and below (it could be that it appears before 9 though). The problem was in the emission of section symbols from the `eh_frame` section, which apparently should represent call frames, so it is not obvious to me why they are tagged as STT_SECTION that is mapped to LLVM's ST_Debug. It is unclear what those symbols encode,  but is quite obvious that llvm misinterprets them as at the end of the day we have a bunch of symbols named `.text` that hides the real symbols. This PR prevents the emission of such symbols, as well as other symbols, such as file, object, and abi-specific symbols, as we don't really know the …
=> removes section and other symbols in ELF

lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli
The previous algorithm had a very bad collision rate, especially for
small strings. The new one is much better and is tested on large
dictionaries (of English words and large password databases,
with no collisions found) and is guaranteed not to collide on small strings,
which were tested exhaustively.
Warning: the change of the hash function will break the knowledge base
format so do `bap --cache-clean` after the update.
=> switches to Fowler-Noll-Vo hash algorithm for hashing names

plugins/primus_symbolic_executor/lisp/symbolic-stdio.lisp
what is non-trivial is why this bug wasn't detected by the type
checker, which is tracked in #1223.
=> fixes a trivial typo in the symbolic fread implementation

plugins/x86/x86_disasm.ml
There's a decoding error in some Pcmp instructions, and the same type error in Pcmp & Ppackedbinop semantics (left-shift of a vector-register-sized operand by an 8-bit shift value).
=> Fixes lifting disassembler bug for Pcmp

lib/arm/arm_target.ml, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_target.ml, lib/bap_core_theory/bap_core_theory_target.mli, lib/bap_image/bap_memory.ml, lib/bap_systemz/bap_systemz_target.ml, lib/bap_systemz/bap_systemz_target.mli, lib/bap_types/bap_arch.ml, lib/bap_types/bap_ir.ml, lib/bap_types/bap_ir.mli, lib/bap_types/bap_stmt.ml, lib/bap_types/bap_stmt.mli, lib/x86_cpu/x86_target.ml, oasis/mc, oasis/systemz, plugins/bil/bil_lifter.ml, plugins/mc/mc_main.ml, plugins/systemz/.merlin, plugins/systemz/systemz_lifter.ml, plugins/systemz/systemz_lifter.mli, plugins/systemz/systemz_main.ml, src/bap_frontend.ml
In this episode, we liberate `bap mc` and `bap objdump` from the bonds
of the `Arch.t` representation. We also add the systemz lifter for
demonstration purposes. Of course, the lifter is minimal and far from
being usable, but that serves well its didactic purposes.
The interface of the `bap mc` command is preserved but is extended
with a few more command-line options that provide a great deal of
flexibility. Not only it is now possible to specify the target and
encoding, but it is now possible to pass options directly to the
backend, which is useful for disassembling targets that are not yet
known to BAP. Below is an excerpt from the bap-mc man page
(see bap mc --help)
```
SETTING ARCHITECHTURE
The target architecture is controlled by several groups of options that
can not be used …
```
=> overhauls the target/architecture abstraction (3/n)

lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_disasm.cpp
There were a few breaking changes so we have stick with if/else
macros. Mostly the the COFF loader is affected.
Note, I was using llvm-11 from the http://apt.llvm.org/bionic/ source
repository, which could be broken as it is missing libraries for
static linking, so in order to use this pre-built binaries you have to
use the dynamic linking mode, e.g.,
```
./configure-omake --with-llvm-version=11 \
--with-llvm-config=llvm-config-11
--disable-llvm-static
```
I hope this will go away with an official (ubuntu) build of llvm.
=> upgrades bap to LLVM 11

lib/bap_primus/bap_primus_memory.ml
This PR fixes a bug in the Primus.Memory.map function that was
triggered when it was called before the current memory descriptor is
properly initialized. Instead of creating a new empty state it was
just silently ignoring the `map` operation. The bug was also affecting the
`Primus.Memory.del` operation, for which such behavior (i.e.,
ignoring) is probably fine. The new implementation fixes the update
function used by both, map and del to prevent any further misuses of
this function.
=> adds a proper handling of unitialized memory in Primus.Memory.map

Makefile
Since we had to reliquish the power of true submodules in #1218 (to
prevent opam from recursively checkout all submodules, including
pre-recorded traces, on each package installation) we were no longer
able to upgrade the testsuite in a preparation for an upcomming PR
without breaking the existing tests. In other words, we need
submodules back.
This PR restores them, but instead of relying on true submodules we
just record the revision in the Makefile and take care of checking out
this revision. Most of the work (not much) is done in the testsuite
repo (i.e., checking the revision out).
The idea is that when we need to extend/change the testsuite for some
PR to the bap repository (e.g., we added a new feature that we would
like to test), we create a branch in bap-testsuite with that …
=> enables poorman submodules for the testsuite

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_machine.mli, lib/bap_primus/bap_primus_observation.ml
The names of providers and observations diverged, which resulted in a
bug. Fixes #1232.
This PR also publishes `Machine.fork` (aka `machine-fork`) and
`Machine.switch` (aka `machine-switch`) observations due to the users
requests.
Thanks @bgz25 for reporting the issue.
=> fixes Machine.Observation.watch function and publishes fork/switch

lib/monads/monads.mli, lib/monads/monads_monad.ml, lib/monads/monads_types.ml
Instead of extending the `Syntax` module of the `Monad.S` and
`Monad.S2` interface, which will break the interfaces, we add a new
module `Let` which includes binding operators for Monadic and
applicative interfaces (`let*`/`and*` and `let+`/`and+`
correspondingly).
That means that in order to be able to use the monadic operators for
the monad `Example` we need to open either `Example` or `Example.Let`
first, so we can write
```
open Example.Let
let example x y =
let* r = compute x in
let+ s = compute y in
r + s
```
instead of the old style with `fun`,
```
open Example.Syntax
let example x y =
compute x >>= fun r ->
compute y >>| fun s ->
r + s
```
Parallel binding is provided via the `(and*)` and `(and+)` operators,
so it is possible to write
```
open Example.Let
let example x y =
let* r …
```
=> adds binding operators to the monads library

plugins/print/print_main.ml
This PR fixes #1145 and makes disassembly printing more robust and
more in line with the disassembler implementation.
Background. When `-dasm` is specified we're iterating over sections
and print subroutines that belong to that sections. Since sections in
general can overlap we have duplicating outputs. This approach
followed the old implementation of the disassembler that indeed was
disassembling each section. However, at some point of time we switched
to the code-region abstraction. Code regions do no overlap and are
guaranteed to contain code. Now it is time to update the print plugin
and also iterate over code regions. We still use sections for names
but do not skip a region if there is no section (we just make up a
bogus name). That makes printing more resilent to various custom …
=> prints only code regions, use sections for names

lib/bap_c/bap_c_type.ml, lib/bap_plugins/bap_plugins.ml, lib/bitvec_binprot/bitvec_binprot.ml, lib/regular/regular_bytes.ml, lib/regular/regular_seq.ml
We missed some deprecation warnings in #1116. Most of them are dealing
with `sexp_*` types, which are easy to deal.
Another class of warnings is the deprecation of `Binprot.Of_binable`
due to introduction of uuid-identifiers witnessing the binary
representation. The idea is good and not novel to BAP, we always had
have those uuids. However, right now we're resolving this issue by
hushing the warning and we plan to address it in the nearest future,
in the next release.
=> fixes warnings introduced with #1116

plugins/primus_systems/systems/core.asd, plugins/primus_taint/primus_taint_main.ml
Fixes #1144. We add three more components for policy selection. One
that selects the policy selected by the user via the command-line and
another two per each policy that we support. The base-taint-analyzer
system is leaving the policy selection unspecified. The taint-analyzer
system selects the policy based on the command-line parameter and teh
exact-taint-analyzer is relying on the exact taint propagation.
=> initializes the default policy in primus taint analyzers

lib/bap/bap_project.ml
This PR fixes a bug reported by @jtpaash (with a nicely reproducible
demo). The bug was introduced when we switched to lazy computations so
that now symtab and program data structures computations were delayed
and could be run in a different state than the disassembly. The main
culprit was that those computations were forgetting to properly open
the current package to be able to access the objects of the currently
disassembled program (they were instead picking those objects from the
lastly disassembled program). Fortunately the fix is obvious and
simple.
=> fixes improper compartmentalization of project computations

lib/bap_build/bap_build.ml
Apparently those predicates are no longer needed and are mishandled by
ppx_bap. Probably we should also inherit some META-magic from
ppx_jane.
Note, with these predicates `type nonrec t = t [@@deriving]` no longer
works.
=> fixes bapbuild by removing no longer necessary predicates

.github/workflows/build-dev-repo.yml, .github/workflows/nightly-testing.yml
The old one was disabled by Github due to security issues.
=> sets the macOS-specific environment variable using a diffrent syntax

lib/bap_taint/bap_taint.ml
The observation was missing when the taint was introduced with
`new_direct` or `new_indirect` operators. Although known for a long time,
this behavior was considered more as a feature rather than a bug. We
finally decided to rectify it and post the observation when a new
taint is introduced to make the behavior match with the semantics
described in the low-level terms. It also makes it much easier to
debug taint-related issues.
=> makes the taint-attached observation on taint introductions

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_env.ml, lib/bap_primus/bap_primus_env.mli, lib/bap_primus/bap_primus_machine.ml, lib/bap_primus/bap_primus_types.ml
This PR adds a new interface, `Machine.Other`, that enables access to
the local state of other machines. It is possible both to pry into
others local state and even change it. So is it carefuly.
This PR is a step towards the solution of the #1076 issue. More will
come.
=> enables intermachine communication

plugins/stub_resolver/stub_resolver.ml, plugins/stub_resolver/stub_resolver.mli, plugins/stub_resolver/stub_resolver_main.ml, plugins/stub_resolver/stub_resolver_tests.ml
The stub resolver wasn't setting the Sub.stub attribute for
subroutines resolved as stubs. Now it is done as a part of the abi
pass that relinks stubs to their implementations.
=> propagates stub resolver results to program term attributes

.github/workflows/build-from-opam.yml, .github/workflows/release.yml
Since we're depending on the master version of the ppx_bap package,
which is only available in our testing repository.
Also enables on-demand build for the release action.
=> adds the testing repository to several actions

lib/bap_primus/bap_primus_memory.ml, plugins/primus_symbolic_executor/primus_symbolic_executor_main.ml
Do not fail when memory location wasn't explicitly set as symbolic but
just register it on the fly.
=> protects symbolic executor from segfaults when setting memory inputs

Makefile, tools/bapdoc.ml
re-enables back the hidden Unix module
=> updates bapdoc to the latest changes in core_kernel

lib/bap_primus/bap_primus_lisp_program.ml, plugins/primus_lisp/primus_lisp_main.ml
The call graph wasn't correctly closed and there were unreachable
components. That resulted in missing type errors as the typing
information from some nodes never reached the exit node.
Fixes #1223
=> fixes the callgraph formation procedure in Primus Lisp typechecker

.github/workflows/build-dev-repo.yml, .github/workflows/nightly-testing.yml, lib/bap_llvm/bap_llvm_loader.ml, lib/bap_llvm/llvm_coff_loader.hpp
We were missing non-executable sections in coff files. Thanks to
@TodAmon and @ReversingWithMe for noticing this.
=> fixes PE/COFF sections

lib/bap/bap.mli, lib/bap_types/bap_core_theory_bil_parser.ml, lib/bap_types/bap_core_theory_bil_parser.mli, lib/bap_types/bap_stmt.ml, lib/bap_types/bap_stmt.mli, lib/bap_types/bap_types.ml, oasis/bap-std, plugins/bil/bil_lifter.ml, plugins/bil/bil_semantics.ml, plugins/bil/bil_semantics.mli, plugins/relocatable/rel_symbolizer.ml
It is now possible to (ab)use BIL special statements to encode arbitrary semantics. The payload is still stored as a string, but it is now specially encoded and printed. Each kind of payload is represented by an attribute, e.g., `Bil.call` is used to encode calls, and `Bil.intrinsic` is used to encode intrinsics.
The Core Theory BIL parser, that enables reflection of the BIL programs into the CT terms, is moved to the library and is made available in `Bil.Theory` module. We might later extend this module with the actual BIL theory, though it is already could be instantiated via the `Theory.instance` function.
=> introduces BIL special encodings and publishes BIL CT parser

lib/arm/arm_lifter.ml, lib/bap/bap.mli, lib/bap_sema/bap_sema.ml, lib/bap_sema/bap_sema_lift.ml, lib/bap_sema/bap_sema_lift.mli, lib/bap_types/bap_ir.ml, lib/bap_types/bap_ir.mli, lib/bap_types/bap_stmt.ml, lib/bap_types/bap_stmt.mli, lib/bap_types/bap_types.ml, plugins/bil/bil_lifter.ml, plugins/x86/x86_endbr.ml, plugins/x86/x86_legacy_bil_lifter.ml, plugins/x86/x86_lifter.ml, plugins/x86/x86_tools_prefix.ml
This PR adds a few convenience functions and gives access to internals
for build BIR graph. It is now very easy to go from BIL to blk term,
sub term or even program term. Details follow.
We used BIL as a language for specifying the semantics of an
instruction, but we may also (and now can) represent the instruction
itself using BIL.
The rules of the knowledge base are adopted and split accordingly, so
that the rule that uses the old lifters to produce the BIL code is
separated from the rule that computes the semantics of the BIL code.
It is now possible to get easily an `Insn.t` value from `bil` and even
to go from bil to sub or program term.
E.g., to get the semantics of BIL just create a new program object and
set its bil code,
```ocaml
let create_insn bil  =
KB.Object.create …
```
=> introduces the BIL code slot and a few convenience functions

lib/bap_image/bap_memory.ml
The first bug was breaking the raw loader at least. It bug was
introduced in #1178 during the `Memory.view` optimization. A check was
missed that allowed for creation of invalid views. The invalid views
later were caught with an assertion check, (easily reproduced with
`bap /bin/ls --loader=raw`), e.g.,
```
("Assert_failure bap_memory.ml:72:2"
"Raised at file \"bap_memory.ml\", line 72, characters 2-31\
\nCalled from file \"bap_memory.ml\", line 196, characters 2-18\
\nCalled from file \"bap_memory.ml\", line 410, characters 26-52\
\nCalled from file \"bap_trie.ml\", line 46, characters 34-53\
\nCalled from file \"bap_trie.ml\", line 62, characters 4-130\
\nCalled from file \"bap_byteweight.ml\", line 78, characters 12-39\
\nCalled from file \"bap_byteweight.ml\", line 129, characters …
```
=> fixes two bugs in the Memory module

oasis/read-symbols, plugins/read_symbols/read_symbols_main.ml
The new implementation uses directly the knowledge base and is able
to provide information from several files and different information
to different units.
The input format is now more permissive, it is possible to specify
only function starts or function with names or use the old blocks
format where each entry denotes a basic block. See `bap
--read-symbols-help` and `bap --help` for the input format and flags
descriptions.
=> rewrites the read-symbols plugin

lib/bap/bap_project.ml, plugins/disassemble/disassemble_main.ml
The target command-line parameter specializes (refines) the target
architecture of the disassembled binary, in order to specify abi,
fabi, and other target-specific parameters.
If the specified target is less specific than the binarie's target
then it will be ignored, if it is incompatible then an error will
occur.
Example, `arm-linux-gnueabi-echo` binary from `testsuite/bin` is a
binary built for bap:armv5+le, so we can refine it by adding an
application profile and floating-points (see `bap list targets` for
the full list of targets),
```
$ bap bin/arm-linux-gnueabi-echo --target=armv7-a+fp+le
```
At the same time if we will try to specify `amd64` or even an arm
but that is not derived from `armv5+le`, we will get an error, e.g.,
```
$ bap bin/arm-linux-gnueabi-echo …
```
=> adds the `--target` parameter to disassemble and compare commands

lib/bap_core_theory/bap_core_theory_target.ml, lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_lisp.mli, lib/bap_primus/bap_primus_lisp_attribute.ml, lib/bap_primus/bap_primus_lisp_attribute.mli, lib/bap_primus/bap_primus_lisp_attributes.ml, lib/bap_primus/bap_primus_lisp_attributes.mli, lib/bap_primus/bap_primus_lisp_context.ml, lib/bap_primus/bap_primus_lisp_context.mli, lib/bap_primus/bap_primus_lisp_parse.ml, lib/bap_primus/bap_primus_lisp_program.ml, lib/bap_primus/bap_primus_lisp_program.mli, lib/bap_primus/bap_primus_lisp_resolve.ml, lib/bap_primus/bap_primus_lisp_semantics.ml, lib/bap_primus/bap_primus_lisp_semantics.mli, oasis/primus, oasis/primus-lisp, plugins/bil/bil_semantics.ml, plugins/primus_lisp/lisp/init.lisp, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.mli, plugins/primus_lisp/primus_lisp_show.ml
Introduction
============
It is now possible to specify program semantics, including
semantics of instructions (aka lifters) and even semantics of the
whole programs in Primus Lisp.
Essentially Primus Lisp programs could be compiled into program
values, i.e., core theory terms. The main motivation for this work was
writing lifters and stubs in Primus Lisp, which significantly reduces
the effort wrt writing a lifter directly in OCaml. For example, it
took me less than a day to write a RISCV lifter in Primus Lisp (the PR
is upcoming).
The feature is seamlessly integrated with the knowledge base that
makes it available not only for the new architectures but for
extending the lifters for existing architectures. Whenever a semantics
of a basic instruction is requested, a corresponding Lisp …
=> enables writing program semantics (lifting) in Primus Lisp

plugins/bil/bil_lifter.ml
This is a quick fix that prevents the BIL lifter from interpreting an
absence of BIL as an absence of effects. The root of the problem is
that we chose `[]` as the empty value for the BIL domain, which is
easy to confuse with an absence of effects (or representable in BIL
effects).
We can't change the domain, as it will break the interface, but a
better solution might be changing the domain of the Bil.code slot that
was introduced recently and is not yet in the stable API. Meantime,
the current solution will be the hotfix.
=> hushes the BIL lifter when there is no BIL

lib/bap_main/bap_main.ml, plugins/recipe_command/recipe_command_main.ml
Includes the system-wide share prefix in the search path so that now it is searched in three locations (in that order): the current working directory, user-specific share folder (commonly ~/.local/share/bap) and system-specific (usually `$(opam config var prefix)/share/bap`).
=> fixes recipes search paths

lib/bap/bap.mli
Added a newline so that the auto-documentation will correctly format the `var entry_point` entry correctly.
=> Update bap.mli for auto-documentation

oasis/x86
=> fixes a missing `str` dependency in the x86 plugin

Makefile, lib/bap_riscv/bap_riscv_target.ml, lib/bap_riscv/bap_riscv_target.mli, oasis/riscv, plugins/primus_lisp/site-lisp/libc-init.lisp, plugins/riscv/.merlin, plugins/riscv/riscv_main.ml, plugins/riscv/semantics/riscv.lisp
This PR implements the RISC-V (both 32 and 64) lifter. An amusing part is that the lifter is fully written in Primus Lisp and is so short that I can copy-paste it here. Partially it because RISC-V is so RISC partially thanks to the power of Primus Lisp :) And to be honest the lifter is not 100% complete but may be easily extended later. 
```lisp
(declare (context (target riscv)))
(defpackage riscv (:use core target program))
(defpackage llvm-riscv64 (:use riscv riscv64))
(defpackage llvm-riscv32 (:use riscv riscv32))
(in-package riscv)
;;; Core Arithmetic
(defun ADDI (dst src off)
(set$ dst (+ src off)))
(defun C_ADDI (dst src off)
(set$ dst (+ src off)))
(defun add3 (dst src off)
(declare (visibility :private))
(set$ dst (cast-signed
(word-width)
(cast-low (/ (word-width) 2)
(+ src …
```
=> adds riscv32 and riscv64 support

plugins/mc/mc_main.ml
It looks like that #1281 rendered bap useless for unlifted
instructions. Both mc and objdump commads are now outputing
empty objects even without asm or opcodes, which makes it
really hard to write a new lifter.
This PR fixes it on mc and objdump level. I am not sure if we also
need this in the disassembler driver (as in any case the output of
this driver will be incorrect without having full semantics).
=> restores output for non-empty instructions

lib/bap_plugins/bap_plugins.ml
The check was rejecting benign and passing through malign plugins
by checking the provides fields and loading main+requires fields.
Fortunately, the misbehaving plugins were later failing on the loading
procedure, but as well bening plugins (were also sometimes hit, e.g.,
when all three fields, name, main, and provides, are the same).
=> fixes the unit tracking mechanism

lib/bap_c/bap_c_abi.ml, lib/bap_c/bap_c_abi.mli, lib/bap_c/bap_c_data.ml, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_target.ml, lib/bap_core_theory/bap_core_theory_target.mli, oasis/c, plugins/riscv/riscv_main.ml
This PR introduces a powerful but convenient way of describing complex argument passing semantics. Describing even simple facets of argument passing mechanics
it tedious as it requires taking into consideration a lot of factors, such as the availability of registers, their width, the types of the passed data, its alignment requirements and so on. It is extremely hard to write a generic algorithm that will be able to accommodate the large variety of options and be at the same time useful and easy to use. Instead, we decided to pick a parser combinator approach as naturally we want to describe how to parse (or recognize) data that is passed to us by the caller. The proposed DSL is a choice monad (i.e., it has [choice] and [reject] operators that enable backtracking) so that we can try …
=> implements ABI description eDSL

Makefile, lib/arm/arm_target.ml, lib/bap/bap_project.ml, lib/bap_c/bap_c_abi.ml, lib/bap_c/bap_c_abi.mli, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_target.ml, lib/bap_core_theory/bap_core_theory_target.mli, lib/bap_mips/bap_mips_target.ml, lib/bap_primus/bap_primus_lisp_semantics.ml, lib/knowledge/bap_knowledge.ml, oasis/arm, plugins/arm/arm_gnueabi.ml, plugins/arm/semantics/aarch64.lisp, plugins/bil/bil_ir.ml, plugins/bil/bil_semantics.ml, plugins/mc/mc_main.ml, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/primus_lisp/semantics/bits.lisp
The [lifter][1] is written in [Primus Lisp][2] and is complete enough to lift and correctly execute our test binaries. The number of lifted instructions is about 50 but it is easy to add new ones (do not forget to contribute them back to us). I am planning on writing a guide on writing lifters in Primus Lisp but before that (and after that as well) I am always ready to help in our Gitter channel (or in Git Discussions).
During the development of the lifter, I have discovered a few shortcomings which were overcome so the pull request includes some other modifications, including qualify of life changes, bug fixes, and other improvements. They are described in detail below.
It is much easier to write lifters with them. Essentially, I am just doing
```shell
bap objdump ./exe …
```
=> adds armv8 (aarch64) lifter

lib/bap_c/bap_c_abi.ml
All arrays are implicitly converted to pointers when passed to a
function, therefore when we see `elt p[]`, `elt p[X]`, or
`elt (*p)[X]` in the prototype we shall convert them to `elt *`.
The conversion is applied in the C ABI processor application function
as it is a feature of the language not of an individual ABI. This will
enable this feature in all C ABI implementations (processors) as they
will not see arrays anymore.
=> implements the array to pointer conversion in C ABI processor

lib/bap/bap.mli, lib/bap_image/bap_image.ml, lib/bap_image/bap_image.mli, lib/bap_llvm/bap_llvm_loader.ml, lib/bap_llvm/llvm_coff_loader.hpp, lib/bap_llvm/llvm_loader.hpp, lib/bap_llvm/llvm_macho_loader.hpp, oasis/dependencies, oasis/specification, plugins/dependencies/dependencies_main.ml, plugins/specification/specification_main.ml
The command outputs program dependencies such as libraries and symbols. The information is collected recursively with various output options, including dependency graph, YAML, JSON, and SEXP.
The information includes the list of imported libraries as well as sets of imported and exported symbols. The information could be collected recursively when the `--recursive` option is specified. In a recursive mode, the list of paths where to search for libraries could be specified with the `--library-path` option that accepts a list of paths. It is also possible to use the host ldconfig cache (or specify custom library config) via the `ldconfig` parameter. Information about each individual dependency is cached, so consecutive calls to bap will reuse the available information and terminate quickly. …
=> introduces `bap dependencies` command

lib/ogre/ogre.ml, lib/ogre/ogre.mli, plugins/specification/specification_main.ml
Motivation: YAML is both human-readable and machine-readbale and together with yq it is possible to easily construct various queries or translate it to json and other formats.
Also adds a corresponding `Ogre.Doc.pp_yaml` function.
=> adds YAML as an alternative output of the specification command

oasis/thumb, plugins/thumb/thumb_bits.ml, plugins/thumb/thumb_branch.ml, plugins/thumb/thumb_branch.mli, plugins/thumb/thumb_main.ml, plugins/thumb/thumb_opcodes.ml
We could use Primus Lisp for that but apparently we already have them
implemented but just forgot to update the code and to use it.
=> adds the missing ux*, sx*, s?bz instructions

lib/arm/arm_target.ml, plugins/arm/semantics/aarch64.lisp, plugins/arm/semantics/arm-bits.lisp, plugins/arm/semantics/thumb.lisp, plugins/thumb/thumb_bits.mli, plugins/thumb/thumb_main.ml, plugins/thumb/thumb_mov.ml, plugins/thumb/thumb_mov.mli
The instructions are (mostly) implemented in Primus Lisp. We also add
an arm-bits.lisp file, which contains arm-specific operation that can
be shared across all members of the arm architecture.
=> adds more thumb-specific instructions

plugins/arm/semantics/thumb.lisp
We shall do 1-complement negation instead of 2-complement negation.
Thanks @ccasin, @philzook58 for pointing out that the implementation
was incorrect!
=> fixes Thumb's SBC semantics

lib/bap_primus/bap_primus_lisp_semantics.ml, plugins/mc/mc_main.ml
This option will dump the final state of the knowledge base. Mostly
useful for debugging and writing lifters.
=> adds the --show-knowledge option to bap mc

lib/arm/arm_target.ml, lib/bap_disasm/bap_disasm_basic.ml, plugins/arm/semantics/thumb.lisp
Ensures that the instruction encoding matches with the name of encoding that is used to decode it. Before this fix, the encoding name was sometimes taken from the triple, which enforced us to have the names of encoding that match with the triple. We can now safely peek any encoding name.
=> preserves the encoding name of the instruction

lib/bap/bap_project.ml, lib/bap_core_theory/bap_core_theory_IEEE754.ml, lib/bap_core_theory/bap_core_theory_definition.ml, lib/bap_core_theory/bap_core_theory_effect.ml, lib/bap_core_theory/bap_core_theory_empty.ml, lib/bap_core_theory/bap_core_theory_manager.ml, lib/bap_core_theory/bap_core_theory_program.ml, lib/bap_core_theory/bap_core_theory_value.ml, lib/bap_core_theory/bap_core_theory_var.ml, plugins/systemz/systemz_lifter.ml
The `theory` part is excessive and only makes it harder to read the
knowledge base. The new name will also make more sense when we will
add more theories.
=> renames the `core-theory` package to just `core`

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_lisp.mli, lib/bap_primus/bap_primus_lisp_parse.ml, lib/bap_primus/bap_primus_lisp_program.ml, lib/bap_primus/bap_primus_lisp_program.mli, lib/bap_primus/bap_primus_lisp_semantics.ml, lib/bap_primus/bap_primus_lisp_semantics.mli, lib/knowledge/bap_knowledge.ml, oasis/primus-lisp, plugins/primus_lisp/primus_lisp_documentation.ml, plugins/primus_lisp/primus_lisp_documentation.mli, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_loader/primus_loader_basic.ml
Much like the old `bap --primus-lisp-documentation` this command
prints the Primus Lisp documentation in the .org format. But it
doesn't require a file as it is possible to specify the target using
the `--target` command line option.
Since `primus-lisp-documentation` is a separate command, it is not
necessary to specify a bogus file name and there are more options to
control the output. First of all, it is now possible to specify the
system (using `--system`), so that now it is possible to get the
documentation for symbolic primtives and functions. It is also
possible to set the package name (using `--package`) and request the
documentation for the Primus Lisp Semantics subsystem (with
`--semantics`).
Therefore, to get the documentation for thumb semantics (functions and
primitives), use …
=> adds `bap primus-lisp-documentation`

lib/bap_c/bap_c_size.ml, lib/bap_c/bap_c_size.mli
For some reason the code assumes that `x mod m` is multitude of
`m` and raises an exception when it doesn't happen (quite often in
fact).
The code is called when a structure size is computed. The main caveat
here is that
1) this method has incorrect type as it constrains the padding size to
be in the set of `8,16,32,64,128,256` but real padding may have any
number of bits (it is their sum that should in this range).
2) this method shouldn't exist at all as the padding is fully defined
by the alignment of the field and there is no need to override it.
Therefore, the solution is to deprecated this method and compute
padding using the alignment information only. The method is no longer
used and any code that overrode it will get a warning.
=> fixes a bug in the method that computes C padding.

lib/arm/arm_target.ml, lib/bap_llvm/llvm_disasm.cpp, oasis/arm, plugins/arm/arm_main.ml, plugins/arm/semantics/arm-bits.lisp, plugins/arm/semantics/thumb.lisp, plugins/mc/mc_main.ml
The big endian thumb and arm targets are [not supported by LLVM][1]
and while [the fix][2] is available for many years it is still not
reviewed. I tried to [raise the attention][3] to it but with no
success. Since it looks like that they are not going to fix it we need
to fix it on our side. The solution is a little bit hacky but we can
keep it until we switch to Ghidra for disassembling/lifting.
Examples,
```
$ bap mc --arch=thumb --show-insn=asm --show-bil -- 1a 42
tst r2, r3
{
#1 := R2 & R3
ZF := #1 = 0
NF := extract:31:31[#1]
}
$ bap mc --arch=thumb --order=big --show-insn=asm --show-bil -- 42 1a
tst r2, r3
{
#1 := R2 & R3
ZF := #1 = 0
NF := extract:31:31[#1]
}
$ file echo
echo: ELF 32-bit MSB executable, ARM, version 1 (ARM), dynamically
linked, interpreter /lib/ld-uClibc.so.0, for …
```
=> adds support for big-endian arm and thumb architectures

lib/bap_c/bap_c_size.ml, lib/bap_c/bap_c_type.ml, oasis/frontc-parser, opam/opam, plugins/frontc_parser/frontc_parser_main.ml
Since FrontC.4.x supports new types from C99+ we had to update BAP as
well, both its representation of the C types as well as the parsing
procedure.
We also added an option (disabled by default) to apply
preprocessing (with an ability to specify the path to it) since
FrontC.4.1+ is much more robust and is capable of chewing linux system
headers.
Note, this PR could not be merged until [FrontC.4.1 is merged][1] and
even after a care should be taken to properly reconstraint our
dependencies on FrontC. We might even consider merging this PR after the BAP.2.3.0 release.
[1]: https://github.com/ocaml/opam-repository/pull/18736
=> switches to FrontC.4.x adds the preprocessing option

.github/workflows/nightly-testing.yml, tools/release.sh
The old script was following the old share folder layout and, as a
result, bap is not working from debian as it is missing the neccessary
lisp files.
=> fixes the shared folder in deb packages

tools/release.sh
It is not guaranteed that sudo is present and is not really
necessary as those actions are anyway run by a super user.
Fixes #1317
=> removes sudo from postinst and postrm actions in the deb packages

.github/workflows/publish-docker-image.yml
The docker images are no longer pushed to dockerhubn after #1312.
First of all, because the secret names were accidentally changed,
and secondly, because the `push` parameter defaults to `false` in
the `v2` version of the action.
=> enables push flag in the publish-docker-image action

opam/opam
This file is assuming the presence of the testing snapshot opam
repository, which is not always available. It is also not required to
get ppx_bap from it as it is already for a long time in the upstream
repository.
=> fixes the ppx_bap version in the dev-repo opam file

opam/opam, plugins/arm/arm_gnueabi.ml
We reuse the existing arm and thumb abi but make sure that the correct
architecture is passed to the memory-related operations.
fixes #1324
=> adds armeb abi

lib/bap_c/bap_c_abi.ml, lib/bap_c/bap_c_abi.mli
The `popn` was always poping from the first register and `align_even`
was also doing `popn` instead of aligning.
=> fixes C.ABI.Args `popn` and `align_even` operators

plugins/primus_loader/primus_loader_basic.ml
It should be using the address size everywhere (instead it was using
the number of bits in the architecture, which is 8 for AVR8).
=> fixes frame layout calculation in the Primus loader

lib/bap_llvm/llvm_loader.hpp
The `getBytesInAddress` virutal member-function for ELF files is
implemented incorrectly in LLVM,
```
template <class ELFT>
uint8_t ELFObjectFile<ELFT>::getBytesInAddress() const {
return ELFT::Is64Bits ? 8 : 4;
}
```
It is actually a static file that returns 32 for ELF32 and 64 for
ELF64, which has nothing to do with the actual bitness of the target
architecture address.
The if is using the information obtained from the target (triple) and
falls back to `getBytesInAddress` only if the target is not 16, 32, or
64 bit (the target interface is also strange as it doesn't allow any
other values).
=> fixes the address size computation in the llvm backend

oasis/flatten, plugins/flatten/.merlin, plugins/flatten/flatten_main.ml
The flatten pass will turn the BIR code into the three-address code turning each non-flat operand of an expression into the flat form (and adding more definitions). An expression is flat if it is either a variable, a constant, or an unknown expression. All other operand expressions are recursively flattened (reduced). 
To enable the pass use the `--passes` option (or short version `-p`), e.g., `--pass=flatten` or `-pflatten`.
=> adds the flatten pass

lib/bap_core_theory/bap_core_theory.mli, plugins/bil/bil_ir.ml
For the context, since the Ghidra PR the semantics of the [blk]
operation in Core Theory was refined and corresponding theories were
updated. Before #1326 all theories were just ignoring the labels
passed to the [blk] operator. The reason for that was that the [blk]
operation serves two purposes. It enables concatenation of data and
control flow effects. And it attaches a label to that sequence so that
it could be referenced elsewhere. Before #1326 it was only used for
the first purpose, i.e., to merge data and control effects into the
single effect. But for Ghidra we needed an ability to create
labels (as ghidra is relying on Branch/Cbranch) instructions
everywhere, even to express the intra-instruction logic, not real
control flow.
Now, the theories have to take into account the label …
=> fixes and improves label handling in the IR theory

oasis/glibc-runtime, plugins/abi/abi_main.ml, plugins/glibc_runtime/glibc_runtime_main.ml
The problem was not in heuristic per se, but in the cyclic dependency between the abi pass that discovers __libc_start_main, main, abi passes, and api passes. Ideally, we should reimplement our ABI/API infrastructure using the Knowledge Base, which was originally designed to handle such dependencies, but it will take much more time than we currently have.
Therefore, right now we discover `__libc_start_main` in the ABI pass, to be sure that we have types applied to it (which we need as we will use them later to get the storage for the first argument). And we delay the `main` function discovery after the api pass. After we find `main` we also want types to be applied. Unfortunately, we can't can call the api pass again (which is responsible for that), but we know the prototype of `main`, so …
=> improves the `main` function discovery heuristics

plugins/api/api/c/posix.h, plugins/primus_lisp/primus_lisp_io.ml, plugins/primus_lisp/site-lisp/getopt.lisp, plugins/primus_lisp/site-lisp/libintl.lisp, plugins/primus_lisp/site-lisp/locale.lisp, plugins/primus_lisp/site-lisp/posix.lisp, plugins/primus_lisp/site-lisp/setjmp.lisp, plugins/primus_lisp/site-lisp/stdio.lisp, plugins/primus_lisp/site-lisp/stdlib.lisp, plugins/primus_lisp/site-lisp/unistd.lisp
Adds some stubs from locale.h, libintl.h, unistd.h, setjmp.h, and getopt.h. These are the stubs that are commonly used by coreutils so that we can now even run `/bin/echo`, e.g., `bap /bin/echo --run --run-argv=echo,hello` and it will output `hello` successfully passing through the locale and i17n mumbo-jumbo. 
Also fixed a few stubs, like `fopen` that was returning `-1` on error instead of NULL. Also tried to fix `getopt` but it is most likely broken. 
See the diff for more details on changes.
=> adds more primus lisp stubs and fixes some existing

plugins/primus_lisp/primus_lisp_semantic_primitives.ml
This theory is used for debugging and introspection purposes. The bug
was in the denotation of `branch` and `repeat` operations, which were
denoted as empty denotations if any of its effects are empty. It is
now corrected.
=> fixes core:eff theory

lib/graphlib/graphlib.mli, lib/graphlib/graphlib_regular.ml
This operation doesn't make sense for graphs with unlabeled nodes and
shall return the graph unchanged. A corresponding clarification
comment is added. Also, cleans up the documentation a little bit.
fixes #1339
=> fixes the Node.update for graphs with unlabeled nodes

lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli
Context variables are regular state variables and are introduced to enable stateful analyses. They are not stored in the knowledge base nor they are persistent. They are also not involved in the fixed point computation. At the same time, the data type of a stateful variable is not required to have the domain structure or even be ordered. Anything could be stored in the state.
Many analyses require a regular, non-monotonic and unordered, state. A good example, is an optimization analysis or a variable desugaring analysis that will come in one of the next pull requests. We may also find it useful and much more efficient to store some state of the analysis, like the current target or theory, in the context, rather than in the knowledge base or in the temporal promise.
Previously, if we …
=> adds context variables to the knowledge base

lib/bap/bap_project.ml, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_manager.ml, lib/bap_core_theory/bap_core_theory_manager.mli, lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli
This PR turns the current theory into an implicit parameter of all functions that depend on a theory but don't really know which theory to pick. For example, a lifter is not supposed to pick the theory structure but instead shall receive the theory from the calling party. The lifters are, however, called via the promises, which doesn't provide any explicit interfaces for passing the theory instance. The newly introduced context variables offer the proper mechanism for passing theory as an implicit parameter.
The idea is that a generic algorithm uses the `Theory.current` (which is a shortcut for `Theory.(instance >=> require)`) to obtain the theory structure. Then the caller of that algorithm may either rely on the implicit theory or override it using `Theory.with_current` function. The …
=> uses context variables to store the current theory

lib/arm/arm_target.ml, lib/bap_core_theory/bap_core_theory.ml, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_manager.ml, lib/bap_core_theory/bap_core_theory_pass.ml, lib/bap_core_theory/bap_core_theory_pass.mli, lib/bap_core_theory/bap_core_theory_target.ml, lib/bap_core_theory/bap_core_theory_target.mli, lib/bap_primus/bap_primus_lisp_semantics.ml, oasis/core-theory, plugins/arm/semantics/aarch64.lisp, plugins/bil/bil_ir.ml, plugins/bil/bil_lifter.ml, plugins/bil/bil_semantics.ml, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/primus_lisp/semantics/bits.lisp
For the whole history of BAP it was the responsibility of a lifter to resolve all registers aliases and special registers and use some predefined and arbitrary selected set of registers as the base registers.
However, recent additions of new lifters, e.g., Ghidra, and architectures that use various names for the same registers to denote different semantics (aarch64, avr), showed us the current approach doesn't scale well and that we're missing an abstraction that is widely used in the domain that we are modeling.
This PR introduces to the Core Theory register aliases and defines their semantics. It is now possible to set and access pseudo registers and the core theory machinery will automatically resolve it to the corresponding extracts, concatenations, and updates, e.g., `set w1 wzr` …
=> adds register aliases to the Core Theory

Makefile, tools/bapdoc.ml
Despite that https://github.com/ocaml/odoc/issues/539 is fixed long
time ago it never landed into the 1.x branch of odoc, which is the
stable and the released version. All beta versions do not have the
stack overflow bug on core_kernel, but render unreadable documentation
(tried 2.0.0-beta till the latest master). Therefore, we had to
fallback to the `--no-pkg-deps` workaround, so that we can get at
least the BAP documentation. Note, this workaround means that the
links to core kernel and other external libraries will be broken, only
links across bap universe will work.
=> fixes bapdoc

.github/workflows/nightly-testing.yml
which is presumabely fixed but is only available in the master and is
not released.
We will start with the master branch and if it will break stick to the
last working sha.
=> nightly tests are failing due to a bug upstream

plugins/run/run_main.ml
The run plugin was resetting the state of the toplevel knowledge base
to the initial and effectively discarding the knowledge that was
accumulated when the Program.t and Symtab.t were constructed as well
discarding any information that might be added to the knowledge base
in project passes.
The run pass was capturing the state at the time when the Project.t is
not fully ready, and at then end was using `Toplevel.set` to reset any
accumulated knowledge.
Effectively, this bug is a race condition, which we could prevent if
the toplevel interface provided safe functions. This will be addressed
in the next couple of pull requests (they will be more aggresive and
change the semantics of several constructs so I decided to split them
for this hotfix).
Big thanks to @anwarmamat for providing a …
=> fixes a knowledge base race condition in the run plugin

plugins/raw/raw_main.ml
Without it the target could be derived incorrectly, e.g., for arm we
were deriving a bidirectional target, which is not what we want.
=> fixes endianness in the raw loader

.github/workflows/build-dev-repo.yml, lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_pass.ml, lib/bap_primus/bap_primus_lisp_semantics.ml, lib/graphlib/graphlib.mli, plugins/primus_lisp/primus_lisp_main.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.ml
The variable rewriter was incorrectly setting the mask when a register
was modified through its alias. Instead of preserving the bits that
are not set it was erasing them.
There were also a couple of issues in handling registers and variables
in the Primus Lisp lifter. First of all, let bindings were breaching
the type system by binding variables to values that have different
type. The set function was sometimes mistyping the
registers (reminiscent of times when there were no pseudo-registers).
=> fixes variable rewriter and some Primus Lisp symbolic functions

Makefile, lib/arm/arm_target.ml, plugins/arm/semantics/aarch64.lisp, plugins/arm/semantics/arm-bits.lisp, plugins/primus_lisp/primus_lisp_main.ml
1) adds proper aarch64 language ids for the ghidra backend
2) adds about 20 more instructions
3) dealiases R31 and ZR, WZR, and XZR
4) adds the full set of tests (that use symbolic executor)
5) fixes instructions with 32-bit operands, the new `setw` macro
now correctly zeros the uppert 32 bits.
Also some number of quality of life changes:
1) `--primus-lisp-semantics` now fails with a clear message when the
passed argument doesn't name a folder (previously it was silently
ignoring it).
2) moves arm-wide operations to `arm-bits`
3) allows to repeat of the `--primus-lisp-load` parameter, to make it
easier to use it in scripts and recipes.
=> fixes and improves aarch64 lifter

plugins/primus_lisp/site-lisp/simple-memory-allocator.lisp, plugins/primus_lisp/site-lisp/stdlib.lisp
1) brk was returning the brk address instead of setting it;
2) getenv was missing the first entry in the envop array.
=> fixes several Primus Lisp stubs

lib/bap_primus/bap_primus_lisp_semantics.ml, lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli, plugins/bil/bil_lifter.ml, plugins/primus_lisp/primus_lisp_main.ml, plugins/radare2/radare2_main.ml, plugins/x86/x86_legacy_bil_lifter.ml
This is a quality of life PR (an extract from another PR that I am currently working on) that adds a few useful primitives to the knowledge base monad interface.
The most important addition is the new operator `require` that works like `collect` but raises the empty value conflict if the returned value is empty. This function is inteded to be used in the context of promises and proposals that now catch this exception and evaluate the whole scoped expression to the empty value of the computed domain. This vastly simplify the implementation logic of promises for domains that do not use `None` as the empty value.
To make things work even more smoothly we extend the KB.Syntax module with a few new operators. First of all, we include the `Monad.Let` directly into the `KB.Syntax` so that you …
=> extends the knowledge monad interface

lib/bap_core_theory/bap_core_theory_manager.ml, lib/bap_primus/bap_primus_machine.ml, lib/knowledge/bap_knowledge.ml, lib/monads/monads.mli, lib/monads/monads_monad.mli, opam/opam
This PR rewrites from scratch both Knowledge and Primus monads to improve performance and to tame the stack appetites of BAP, in particular it resolves #1269. The performance improvement is quite substantial, ranging from 10% to nearly 50% (i.e., twice as fast) depending on benchmark and compiler options. The use-cases that use Primus Analysis benefit the most (as both monads are used).
Both monads were using the monad transformer library (Monads) for mixing-in the necessary behaviors. Knowledge was using state and error monad, and Primus was using MultiState, Continuation, Error, and was a transformer itself, so it was mixing an extra monad. The generated code was inefficient as the value was passed through multiple bindings, per each mix in. It was especially annoying since all these …
=> rewrites knowledge and primus monads

Makefile, lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_lisp.mli, lib/bap_primus/bap_primus_lisp_parse.ml, lib/bap_primus/bap_primus_lisp_program.ml, lib/bap_primus/bap_primus_lisp_resolve.ml, lib/bap_primus/bap_primus_lisp_semantics.ml, lib/bap_primus/bap_primus_lisp_semantics.mli, lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli, plugins/primus_lisp/primus_lisp_semantic_primitives.ml
This pull request enables forward-chaining rules in the knowledge base and uses them to implement Primus Lisp methods. In addition, it adds a few goodies that makes it easier to write Primus Lisp semantics primitives. It also tweaks a little bit the Primus Lisp parser to enable proper handling of keywords.
So far, the knowledge base was only supporting backward-chaining via the `promise` operation, i.e., promises were called lazily only when a property was collected, which triggered the chain of property computations. Now it is possible to push knowledge forward using the dual of `promise`, the `observe` operation. The `observe` operation registers a `push` action for a property `p`, and the knowledge base calls `push x v` when the value of property `p` of an object `x` is changed …
=> adds forward-chaining rules and Primus Lisp methods

plugins/arm/semantics/arm-bits.lisp, plugins/arm/semantics/thumb.lisp, plugins/thumb/thumb_bits.ml, plugins/thumb/thumb_bits.mli, plugins/thumb/thumb_branch.ml, plugins/thumb/thumb_core.ml, plugins/thumb/thumb_core.mli, plugins/thumb/thumb_main.ml, plugins/thumb/thumb_mem.ml, plugins/thumb/thumb_mem.mli, plugins/thumb/thumb_mov.ml, plugins/thumb/thumb_mov.mli
When an unconditional thumb instruction belong to an IT block, it has to be turned into conditional but it must not set the flags if it is 16 bit and is not CMP, CMN, or TST (A8.8.55). This PR updates all handled t1 instructions to properly handle this constraint.
=> handles conditional instructions inside IT blocks in thumb

plugins/thumb/thumb_mov.ml
also moves arm-specific patterns actions to the arm directory and
constrains their context (so that they do not trigger for non-arm
targets and do not fail when arm is disabled and `arm-set-encoding`
is not available).
Thanks @bmourad01 for timely catch of this bug!
=> fixes a bug in the `cmp` semantics

Makefile, lib/bap_primus/bap_primus_lisp_resolve.ml, plugins/arm/semantics/thumb-patterns.lisp, plugins/patterns/semantics/pattern-actions.lisp
This change affects both dynamic and static interpreters, so read carefully. Before this commit we used basically the same resolution procedure for all Primus Lisp definitions, with the only exception, in the end, we allow more than one method definition for the same name.
The caveat is that when more than one method of the same class is applicable, the most specific methods were chosen and the least specific, i.e., the super methods, were removed from the resolution. On one hand, this enables refinement of a method, on the other we don't have any notation to call the super method, so the refinement is more like a redefinition. This approach is suitable with normal function definitions that are required to be unique (and when we need refinement we can always factor out the common part …
=> tweaks the method resolution to keep super methods

lib/arm/arm_lifter.ml, lib/arm/arm_mov.ml, lib/arm/arm_mov.mli
We use the old ARM lifter to handle T32 instructions but, unlike in ARM, LLVM does decode modified immediate constants in T32 mode so we don't need to decode them twice. This change uses the encoding of the instruction for deciding whether the immediate is in the shifted form or is already decoded.
Thanks @ccasin for detecting the problem.
=> fixes handling modified immediate constants in ARM T32 encoding

lib/arm/arm_lifter.ml, lib/bap_disasm/bap_disasm_driver.ml, lib/bap_disasm/bap_disasm_target_factory.ml, plugins/bil/bil_lifter.ml, plugins/radare2/radare2_main.ml, plugins/thumb/thumb_main.ml, plugins/thumb/thumb_opcodes.ml, plugins/x86/x86_lifter.ml, plugins/x86/x86_utils.ml
Sorry for a little bit dirty pull request featuring several independent changes, but it is really tedious to split it into several PRs.
The most important and controversial change is that we now capture conflicts when disassemble. The conflict is reported, the instruction is marked as invalid and the whole chain instructions that led to it, is rejected. The previous behavior was terminating the program with an error message, which to my taste is more correct, but is unsatisfying from the user-perspective. We might return the old behavior after the release, in the development version of bap, as most of the conflicts are programmers' errors. The motivation for capturing conflicts was introducing pattern-based instruction encoding identification, which naturally can have false positives …
=> error handling and performance tweaks

lib/bap_core_theory/bap_core_theory_var.ml, lib/bap_core_theory/bap_core_theory_var.mli, lib/bap_types/bap_var.ml
This PR is a cherry pick from a big effort on reducing the number of calls to `Toplevel.exec`, with the end goal to forbid any nesting calls. The amount of work turned to be much greater than expected as we still rely very much on the old abstractions (spoiler: the main issue is with how we encode CPU exceptions). The problem with nested calls, is that they have inconsistent views on the knowledge base and that the outer calls undo the knowledge of the inner calls. The real impact is not that tragic but there are some number of annoying artifacts with which we would like to deal.
In this PR we will deal with the way how fresh variables are generated. So far they were using the knowledge base to store the number of generated variables and since `Bap.Std.Var.create` is having non-monadic …
=> fixes fresh variable generation

plugins/bil/bil_ir.ml
The `seq` function was incorrectly dropping blocks because the is_empty predicate was not updated in #1326 when subinstructions were introduced and the null label started to be used everywhere.
=> fixes the IR theory implementation

plugins/bil/bil_ir.ml
It looks like that the IR theory could be more clever and reify
`seq (call <fun>) <rest>` into
```
call <fun> return @next
...
next:
<rest>
```
=> improves reification of calls in the IR theory

plugins/thumb/thumb_core.ml, plugins/thumb/thumb_mov.ml
1) removes double assignments in moves
2) removes doubled gotos in pop, push, stm, and ldm
=> improves semantics of some ITT instructions

lib/bap/bap_project.ml, lib/bap_disasm/bap_disasm_driver.ml, lib/bap_disasm/bap_disasm_driver.mli
In #1375 instead of terminating the program on a knowledge base conflict during instruction lifting, we decided to treat such instruction as invalid and retract it and the whole path that led to it from the set of valid instructions. It turned out that the retraction mechanism wasn't quite complete and there were certain cases when an invalid instruction was still reachable, which triggered conflicts downstream, e.g., during the CFG reconstruction.
The problem mostly arises in the interworked code, where we have to guess whether an instruction is in A32 or T32 mode using heuristics such as byte patterns, which inevitably leads to conflicts. So the first place where we have to enfore agreement is in the encoding detection. Before this change, the information provided by the knowledge base …
=> makes the disassembler more strict

lib/arm/arm_target.ml
Since several patterns may match the same byte sequence, we will accept only the first match and ignore the rest.
=> allows arm-set-encoding to provide conflicting information

lib/bap/bap.mli, lib/bap_image/bap_image.ml, plugins/disassemble/disassemble_main.ml
The feature is implemented directly in the `Image.create` function so
that it can be used programmatically. The `backend` parameter can now
accept an explicit file path instead of the loader name. The
documentation of the `loader` command-line parameter is accordingly
updated.
To prevent clashes between existing loaders and filenames, only
existing filenames with explicit paths are treated as OGRE
specifications, i.e., the path must start with `./`, `../`, or `/` in
Unix.
Example of usage,
```
$ bap testsuite/bin/arm-linux-gnueabi-echo -dogre:echo.ogre -dbir | grep print_endline
000007da: sub print_endline(print_endline_result)
00000804: print_endline_result :: out u32 = R0
0000031e: call @print_endline with return %00000320
$ sed 's/print_endline/printl/g' echo.ogre > echo.mangled.ogre
$ …
```
=> adds an option to directly use ogre files as a loader

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_info.mli, lib/bap_primus/bap_primus_lisp.ml, lib/bap_primus/bap_primus_lisp.mli, plugins/primus_lisp/primus_lisp_documentation.ml, plugins/primus_lisp/primus_lisp_documentation.mli, plugins/primus_lisp/primus_lisp_main.ml, tools/bapdoc.ml
The new generator will produce documenation for all available packages, not only for the `user` package as it was before. In addition, it will print the location and the source code for each definition, if it is available.
The generated documentation is huge (over 300 pages) but it is still possible to generate documentation for a single package, using the `--package` option of the `primus-lisp-documentation` command.
The `bapdoc` generator is also updated to produce documentation for both dynamic and static interpreters.
Here's the demo of [generated Primus Lisp documentation][1].
[1]: https://binaryanalysisplatform.github.io/bap/api/semantics/
=> improves the Primus Lisp documentation generator

lib/bap_plugins/bap_plugins.ml
We use URI instead of file paths to reference plugins, however when we search for the plugins in the library folders we use `Filename.concat` to create paths before turning them into URI. `Filename.concat` is clever enough to use `\\` as the directory separator on Windows. The problem, however, is that `Uri.of_string` is not trying to support Windows paths at all and expects a correctly encoded URI with the path section, which has to use `/` as the separator.
Since Windows should work fine with forward slashes as the directory separator, it is easier just to use them everywhere.
=> fixes the path plugin loader path handling

lib/bap_llvm/llvm_disasm.cpp
Fixes LLVM 13 and LLVM 14 compatibility as of the current master branch.
* LLVM 13 -- llvm::MCContext now requires the TargetTriple ; https://reviews.llvm.org/D101462
* LLVM 13 -- FPImm has been split into two functions, DFPImm retains original semantics ; https://reviews.llvm.org/D77384
* LLVM 14 -- Support/TargetRegistry.h has been moved to MC/TargetRegistry.h ; https://reviews.llvm.org/D111454
LLVM split FPImm functions into DFPImm and SFPImm. getDFPImm still returns FPImmVal, but they are now both of type uint64_t, not double. Likewise, SFPImm functions, and getSFPImmVal's returned SFPImmVal, are a uint32_t, not a float. It looks like other changes may be needed in different parts of BAP's code, or if not, perhaps something like adding the following would be enough:
```
if …
```
=> Fixes for LLVM 13/14 compatibility

.github/workflows/build-dev-repo.yml
The culprit was an update of the C++ toolchain on macOS to the C++20 standard that includes the `version` file. Unfortunately, OCaml is installing the `VERSION` file that's picked up on the search path instead of the correct file (the macOS file system is case-insensitive). The problem is fixed in the upstream (https://github.com/ocaml/ocaml/pull/9895) but there are no backports, so right now the workaround is to remove this file manually, e.g., 
```
rm $(opam var lib)/ocaml/VERSION
```
=> fixes the macOS CI build

.github/workflows/build-and-test.yml, .github/workflows/build-dev-repo.yml, .github/workflows/build-from-opam.yml, .github/workflows/nightly-testing.yml, .github/workflows/release.yml
The unencrypted git protocol is [no longer supported][1] by GitHub.
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> updates the url of the testing repo to use the encrypted version

lib/bap_disasm/bap_disasm_insn.ml, lib/bap_image/bap_memory.ml
This PR fixes a bug that was a feature for a long time, it removes `#undefined` from the output of the disassembly so that even if we don't have full semantics for it. We do this by providing the assembly string as a promise.
The PR also adds the rule specification for the recently added `insn-code` property promise.
=> provides the assembly string as a promise (removes #undefined)

lib/bap_disasm/bap_disasm_insn.ml
Computes all instruction properties at once and uses set to collect them. This change is not very noticable on regular binaries, but gives some performance benefits when floating-points and vector instructions are involved.
=> improves the computation of the instruction properties

plugins/patterns/patterns_main.ml
By precomputing all positions and storing them in arrays.
This is the first PR in a series of optimizations PRs. Once all are merged
bap will be faster by 40%
=> improves the peformance of the byte patterns matcher (1/3)

lib/bap_types/bap_bitvector.ml, lib/bitvec/bitvec.ml, lib/bitvec/bitvec.mli
The comparison function was very heavyweight and was allocating objects on each call. The new version will allocate only when comparing unsigned bitvectors.
In addition, this removes superflous renormalizations of bitvectors and adds the bigint_unsafe function to bitvec, so that we can create bitvec from bap_bitvectors without forcing a renormalization.
This PR changes the semantics of ordering. The default ordering now allows bitvectors with different sizes (though I was assuming that this was the behavior and this is what was written in the documentation, so that this change could be seen as a bug fix).
=> improves the performance of bitvectors (2/3)

lib/bap_mips/bap_mips_target.ml
The target name for MSB Mips is misp63el in LLVM, which we didn't aniticipate.
closes #1407
=> adds support for mips64el target

plugins/disassemble/disassemble_main.ml
This is a quality of life feature intended for the lifter writers. Here is the sample output,
```
$ bap powerpc32-linux-gnu-echo --print-missing
0x10000c64: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c68: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c6c: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c70: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c74: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c78: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c7c: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c20: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c24: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c28: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c2c: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c30: 60 00 00 00 ; nop ; (llvm-powerpc32:NOP)
0x10000c34: 60 00 …
```
=> adds the `--print-missing` option to print unlifed instructions

lib/bap_disasm/bap_disasm_insn.ml, oasis/powerpc, oasis/x86, plugins/arm/semantics/aarch64.lisp, plugins/powerpc/semantics/powerpc.lisp, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/riscv/semantics/riscv.lisp, plugins/x86/semantics/x86-32.lisp, plugins/x86/semantics/x86-64.lisp, plugins/x86/semantics/x86-common.lisp
This PR adds three new primitives that could be used in definition instruction semantics:
- invoke-subroutine, especially useful for intrinsic calls
- empty, which denotes empty semantics, useful for nops
- special to denote special semantics, like `hlt`
It also implements semantics for several missing semantics (detected with `--print-missing`), mostly nops, but there's one significant finding - the `popa` (POPA32 in llvm parlance) instruction from x86, which was surprisingly missing.
=> adds several new Primus Lisp primitives and new instructions

lib/knowledge/bap_knowledge.ml, plugins/bil/bil_lifter.ml
Improves the performance by not storing the empty objects (objects without values) in the knowledge base. When an object is created, we just increase the id of the last created object instead of storing it in the heap of objects. This improves performance and memory footprint and creating a new object doesn't require any more memory in the knowledge base. As a side effect, the object identifiers are never reused, therefore there's no possibility for unwanted aliasing. It will also make it much easier to implement a KB garbage collector or tree shaker if we will even need them. The optimization gets about 10% improvement in both memory and time consumption, and overall performance improvement since 2.4.0 is about 50%.
Another minor optimization is that the branched is no longer creating a …
=> [optimization] do not store empty objects in the knowledge base

.github/workflows/build-and-test.yml, OMakefile, configure-omake, lib/bap/bap_init_toplevel.ml, oasis/elf-loader, opam/opam, plugins/mips/mips.ml
This is a small technical PR that removes warnings produced by the latest OCaml. We also switch to bitstrings.4.x since this version is available for OCaml 4.08 and above so it covers all available versions. (the opam-repository will be correspondingly updated).
=> updates bap to latest OCaml, switches to newer bitstrings

lib/knowledge/.merlin, lib/knowledge/bap_knowledge.ml
The patricia tree delivers faster inserts (since there's no need for rebalancing) and even lookups. The fast merges are not really used yet, but having patrica trees opens nice opportunties for parallelization in the future. The overall improvement is something about 15% and there's also some improvement in the memory footprint. This change also removes KB operations from the critical path, so further optimization of the KB representation deems unnecessary at this time.
We use patricia trees (from Fast Mergeable Integer Maps (1998), [1]) for all finite mappings from objects. The values themselves are still represented with the custom AVL tree.
We use big-endian trees with specially encoded keys, so that the top 6 bits are used to encode the branching bit (its number) and the lower 57 bits …
=> switches to patricia trees in the KB implementation

plugins/thumb/thumb_main.ml, plugins/thumb/thumb_mem.ml
For reference: https://developer.arm.com/documentation/ddi0487/latest
on page 4252:
> When executing a T32 instruction, PC reads as the address of the current instruction plus 4.
then later on page 4743 in the pseudocode for "LDR (literal)":
> `base = Align(PC,4);`
Here are some concrete examples while debugging on real hardware. Notice especially which value from the `thumb_data` array has been loaded into `r0` after executing the `ldr` instructions. The `;-- pc:` flag shows the "typical" notion of a program counter, not pc+4 or so.
=> Fix pc value in pc-relative thumb ldr

lib/bap_disasm/bap_disasm_basic.ml
It was creating an incorrect encoding for instructions, namely `bap:llvm-armv7-` (notice the dangling dash in the end).
Also affects the `Disasm_expert.Basic.with_disasm` function.
=> fixes the low-level Disasm_expert.Basic.create function

plugins/core_theory/core_theory_main.ml, plugins/disassemble/disassemble_main.ml
This fix will ensure that if anything is changed in the core theory configuration, then it will be reflected in the output of disassembly.
Semantic tags describe the set of features that are provided by a plugin. The caching subsystem relies on them to properly identify the program context and capture it in the context digest that is used to store and retrieve caches. Before this fix, there were no intersection between the tags that describe the disassembler requires (uses) and the set of tags that the core-theory plugin provides.
=> fixes the core-theory plugin semantics tags

lib/bap/bap.mli, lib/bap_types/bap_helpers.ml
We are not changing the typing rules of BIL or Core Theory, but providing a well-defined behavior for application of binary operations on bitvectors with unequal lengths. Before that, the behavior was undefined and the precondition of the function was clearly specifying that the inputs should be of equal lengths.
The new behavior is to promote words to the equal length, (much like in C, which implicitly coerces the narrow type to the wider type).
The motivation is simple. It is hard to ensure this precondition in general. Yes, our lifters produce well-typed code, so there are no issues when we interpret code from the lifters. But we also have a lot of different interpreters, extensible via primitives. And those interpreters sometimes don't have any means (or at least efficient means) to …
=> relaxes interpreters to allow ill-typed operations

lib/arm/arm_utils.ml
Predicated instructions that update flags themselves were lifted incorrectly, e.g.,
```
$ bap mc --arch=armv7 --show-bil --show-insn=asm  -- 01 20 52 22
subshs r2, r2, #1
{
#12582910 := R2
R2 := if CF then R2 - 1 else R2
CF := if CF then 1 <= #12582910 else CF
VF := if CF then high:1[(#12582910 ^ 1) & (#12582910 ^ R2)] else VF
NF := if CF then high:1[R2] else NF
ZF := if CF then R2 = 0 else ZF
}
```
In this example, the assignment to CF kills the real value of CF it was true. And easy solution would be just to keep the condition in a temporary variable, e.g.,
```
bap mc --arch=armv7 --show-bil --show-insn=asm  -- 01 20 52 22
subshs r2, r2, #1
{
#12582908 := CF
#12582910 := R2
R2 := if #12582908 then R2 - 1 else R2
CF := if #12582908 then 1 <= #12582910 else CF
VF := if #12582908 then …
```
=> fixes arm predication

lib/arm/arm_mov.ml, lib/bap_traces/bap_trace_events.ml
Previously, we added MIC decoding very conservatively, only to places where we have seen them. Further experiments with qemu tracing showed that we have to apply them in all places where immediates occur.
=> applies ARM modified immediate (MIC) decoding in more places

lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli
These operations, e.g., `guard`, `unless`, `on`, and `reject`, greatly improve legibility of promises by straightening their control flow structure.
=> adds the monad choice interface to the knowledge base

lib/bap_core_theory/bap_core_theory.mli, lib/bap_core_theory/bap_core_theory_program.mli, lib/bap_core_theory/bap_core_theory_target.ml, lib/bap_core_theory/bap_core_theory_target.mli
The `Theory.Target.matches` function now takes the nicknames of the ancestors into account. And a new `Theory.Target.matching` function returns the actual target that matched with the name.
=> refines the `Theory.Target.matches` and adds the `matching` function

lib/bap_mips/bap_mips_target.ml, lib/bap_powerpc/bap_powerpc_target.ml, lib/x86_cpu/x86_target.ml
1. adds a few nicknames for various targets
2. rectifies target hierarachies
3. fixes bitness for the x86 parent
=> refines and extends target definitions

lib/bap_byteweight/bap_byteweight.ml, lib/bap_byteweight/bap_byteweight.mli, lib/bap_byteweight/bap_byteweight_signatures.ml, lib/bap_byteweight/bap_byteweight_signatures.mli, oasis/byteweight, plugins/byteweight/.merlin, plugins/byteweight/byteweight_main.ml, src/.merlin, src/bap_byteweight_main.ml
This change re-enables Byteweight, which was effectively disabled since after we have started to install signatures in a different place. Next it revamps the byteweight plugin and bap-byteweight-signatures library to work with modern bap infrastructure that uses Theory.Target instead of the old Bap.Std.Arch.
The plugin itself was also rewritten and uses only modern interfaces. It stores roots in the knowledge base (no streams anymore) and uses targets and compiler properties from the knowledge base.
The `bap-byteweight` tool, which is used for training, is still not updated so it can't be used to train signatures for targets that are not part of Bap.Std.arch. It will be updated in the future.
=> partially upgrades byteweight to work with the modern bap

lib/arm/arm_lifter.ml
apparently this instruction existed for a long time but was never produced by llvm up until 11+ (confirmed on 13 and 14, not sure about 11 and 12)
=> adds arm unpredicated BL instruction

oasis/llvm.setup.ml.in
Up until now, we were linking all available LLVM components that resulted in the bloated binary image and linking errors due to improperly packaged libraries on various distributions, e.g., missing Polly library, various problems with libterm, and so on, all these problems arose from components that we do not actually use. Moreover, the problem were never solved and issues remain open for decades.
The new approach is to link only the selected components. Since the list of available components is quite extensive (around 200) and there is no documentation available about their dependencies and intention, it is quite hard to identify the subset that we really need. The current default set works fine on llvm-14 but we can refine it later, once we will discover any problems. The components …
=> selects specific llvm components for linking

lib/bap_primus/bap_primus_system.ml
This is a minor bug fix, that enables proper reading of unqualified system names in Primus, so that `Primus.System.Repository.get ~package:"bap" "foo:xxxx` gets `foo:xxx` not `bap:foo\:xxx`.
=> reads correctly unqualified system names

lib/knowledge/bap_knowledge.ml, lib/knowledge/bap_knowledge.mli
The bug was a typo in the merge function that was manifested with the `Failure "types are not equal"` exception.
The new functions are:
- `proceed ~until` as a dual to `guard`;
- `Value.is_empty` that returns `true` if a value is empty
- `Value.has` that checks if the specific property of the value is empty
The change also ensures that empty properties are not stored in values (which also makes the `Value.is_empty` implementation trivial).
=> fixes a bug in the KB update function, adds new functions

lib/knowledge/bap_knowledge.ml, plugins/bil/bil_lifter.ml, plugins/mips/mips.ml, plugins/mips/mips_main.ml, plugins/relocatable/rel_symbolizer.ml, plugins/thumb/thumb_main.ml
The proposals (promises with options) now can use the choice monad interface as well as the other promises could do. Also adds a few guards to the existing code to make it more readable and improve performance.
=> wraps proposals into with_empty and adds more guards

plugins/bil/bil_ir.ml, plugins/ghidra/semantics/pcode.lisp
The code produced by ghidra lifter produces several basic blocks per instruction. This simple optimization contracts (collapses into single block) basic blocks that originate from different subinstructions of the same instruction (when it preserves semantics, of course). The optimization doesn't affect IR that is produced by other lifters.
=> adds subinstruction contraction to improve the ghidra lifter output

plugins/primus_systems/systems/core.asd
The component is responsible for properly restoring the stack frame after a call to the Primus Lisp stub. 
This PR re-closes #879
=> adds the x86/amd64 plt corrector component to the Primus base system

lib/bap/bap.mli, lib/bap_sema/bap_sema_free_vars.ml
The `Sub.compute_liveness` function was accidentally published in #1051 without consideration that it works only for the non-SSA form. This PR fixes this by updating the algorithm to handle the SSA form as well.
The semantics of phi nodes modulo liveness is the following. For a phi-node at block `b0`, `x0 := phi([b1,x1; b2,x2;...;bN,xN])`, the defined variable `x0` is considered to be at the entry of `b0`, i.e., `x0` is live-in of `b0`, and the variable `xi` is live-out of basic block `bi`, for `i > 0`.
Informally, a phi-node defines the values on the corresponding edges of the predecessors.
=> updates the `Sub.compute_liveness` function to handle SSA form

.merlin, lib/arm/arm_target.ml, lib/bap_traces/bap_trace_event_types.ml, lib/bap_traces/bap_trace_events.ml, lib/bap_traces/bap_trace_events.mli, lib/bap_traces/bap_traces.ml, lib/bap_traces/bap_traces.mli, oasis/arm, oasis/traces
A mode event expresses a switch of some processor mode affecting the
execution of all following instructions. The possible values and their
meanings depend on the target. At the moment, the only one that uses
modes is arm, where the mode indicates whether or not thumb mode is
used.
In order to make use of it, it can be provided in `Mode.slot` of
`Theory.program`, such that the computation `Theory.Label.encoding`
can access it, if available.
=> adds mode events to traces

lib/arm/arm_target.ml, plugins/arm/.merlin
A quick followup on #1433, which introduced a dependency on the internal module `Bap_trace_event_types`. The build passed on the PR testing as it wasn't building from opam, but all in the same tree, which can't notice such accesses.
=> fixes an accidental dependency on the bap-traces internal module

plugins/thumb/thumb_mem.ml
Not really a bug but an ugly code generated for the unconditional pop
instruction that involves the PC register,
```
bap mc --arch=thumb --show-bil --show-insn=asm --show-mem --addr=0x1c04 -- f0 bd
1c04: f0 bd
pop {r4, r5, r6, r7, pc}
{
if (1) {
R4 := mem[SP, el]:u32
R5 := mem[SP + 4, el]:u32
R6 := mem[SP + 8, el]:u32
R7 := mem[SP + 0xC, el]:u32
SP := SP + 0x10
jmp (mem[SP, el]:u32)
}
}
```
This change removes this bogus `if(1)`.
=> fixes unconditional pop with return in thumb

plugins/mips/mips.ml, plugins/powerpc/powerpc.ml, plugins/x86/x86_backend.ml, plugins/x86/x86_targets.ml
The BIL lifters are no longer alone but they still spam the logs every time there is an instruction that they can't live. This is especially annoying with the Ghidra backend. This PR removes the noise.
=> hushes bil lifters

plugins/bil/bil_ir.ml
The IR theory will no longer add fall-throughs from a block that has an unconditional jump.
=> removes falls-through from unconditional branches in IR reification

lib/bap_primus/bap_primus_lisp_attribute.ml, plugins/bil/bil_ir.ml, plugins/ghidra/semantics/pcode.lisp, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/x86/semantics/pcode-cpuid.lisp
Adds an `intrinsic` and `symbol-concat` primitives to Primus Lisp and uses them to implement all floating-point operators in pcode and cpuid routines for pcode-x86.
Also rewrites the subinstruction contraction procedure, which was broken. The new version is more aggressive and contracts all contractable subinstructions. 
Another minor fix: fixes the pretty-printing for the attributes parsing error. 
Below is the demonstration how intrinsic are reified into BIR code with the `ucomisd` instruction as an example, 
```
$ bap mc --show-insn=asm --show-bir --x86-backend=ghidra -- 66 0f 2e 05 e6 02 00 00 
UCOMISD XMM0, qword ptr [0x2ee]
0000007d:
0000006c: intrinsic:x0 := extract:63:0[YMM0]
0000006e: call @intrinsic:is_fnan_ieee754_binary with return %00000070
00000070:
00000071: u98944 := …
```
=> implements pcode floating-point and special operators

plugins/arm/semantics/arm-bits.lisp
This macro assigns the lower 32 bits of the register. To prevent the desugaring pass from preserving the upper bits the destination register is first zeroed. This also requires let-bound the right-hand side for the case when it references the left-hand side. Altogether it resulted in ugly and inefficient code, albeit semantically correct.
A much more simple and direct approach is to assign directly to the base register and let Primus Lisp coerce (by zero-padding) the right-hand side.
=> improves the setw function used by the aarch64 lifter

plugins/arm/semantics/arm-bits.lisp, plugins/ghidra/semantics/pcode.lisp, plugins/primus_lisp/semantics/bits.lisp
In p-code the lower parts of registers are referenced as variables with the same name as the base register but with the size equal to the size of the referenced part, e.g., YMM0:64 refers to the lower 64 bits of the YMM0 register. The semantics of assignemnt assumes that the upper parts are preserved.
This commit implements the proper semantics of the `set#` operator, i.e., it extends the right-hand side to the size of the base register, and properly ORs it with the left-hand side.
Note, the fix also touches the `setw` macro from #1454. It was still correct, since all uses of setw was properly typed (unlike p-code), but the new version is more consistent and more general as it now allows the right-hand side to have a different type.
=> fixes register assignments in p-code semantics

lib/arm/arm_target.ml
This enables disassembling the instructions that are available only in these revisions.
=> enables v8.{1,2,3,4,5,6}a revisions for the aarch64 target

plugins/primus_lisp/primus_lisp_semantic_primitives.ml
It was shifting by an incorrect number of bits so that the sign bit wasn't correctly replicated.
=> fixes the `cast-signed` Primus Lisp primitive

plugins/primus_lisp/primus_lisp_semantic_primitives.ml
The Primus Lisp semantic primitives were hardcoding 64-bit arithmetic, which was obviously incorrect. In addition, the shifting operations were coercing the operands to the same size, like in arithmetic operations, which contradicts the established semantics of shifts both in Core Theory and in BIL. Now, the shifting operators will produce values of the same sort as the sort of the first operand.
=> fixes the arithmetic modulus in Primus Lisp primitives

plugins/arm/semantics/arm.lisp, plugins/primus_lisp/semantics/bits.lisp
The pure Primus Lisp implementation supports both statically known and unknown inputs of any lengths. For statically unknown inputs, the generated code will not have any loops and will be proportional in size to the size of inputs in bits divided by 64. The popcount implementation is also branchless.
This PR also hides specialized functions such as `clzN` and `popcountN` functions in favor of the generic `clz` and `popcount` functions.
Not, to properly function on statically known values, this PR needs #1463.
=> adds arbitrary-precision loopless clz and popcount to Primus Lisp

plugins/cache/bap_cache_gc.ml
The cache GC randomly selects files for deletion and there's a sligth chance (1/total-size-of-cache) that it will fail with the following error:
```
Internal error: "Option.value_exn None"
Backtrace:
Raised at file "src/error.ml" (inlined), line 8, characters 14-30
Called from file "src/option.ml", line 136, characters 4-21
Called from file "bap_cache_gc.ml", line 120, characters 8-59
Called from file "bap_cache_gc.ml", line 125, characters 2-33
Called from file "bap_cache_gc.ml", line 151, characters 19-61
Called from file "bap_cache_main.ml", line 138, characters 2-27
Called from file "bap_main.ml", line 841, characters 37-46
Called from file "bap_main.ml", line 1013, characters 25-28
```
This happens when we use a random number to pick a file base on the cumulative distribution …
=> fixes a sporadic internal error in the cache garbage collector

lib/bap_types/bap_core_theory_bil_parser.ml, plugins/relocatable/rel_symbolizer.ml
The relocation symbolizer was treating intrinsic and special calls as relocations and improperly named functions that have such calls.
This problem is especially damaging when the Intel Control-flow Enforcement Technology (CET) is present in the binary. In that case, the `_start` function is renamed to `endbr` and is loaded as a self-calling function.
This commit also ensure that the `intrinsic:` prefix is preserved during lifting.
=> fixes the relocation symbolizer incorrect handling of intrinsics

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_symtab.ml, lib/bap_disasm/bap_disasm_symtab.mli, plugins/print/print_main.ml
This is a simple quality of life update that should be done many years ago. This change adds printing the jump destination address and name, if present, in the assembly output, much like objdump does, e.g.,
```
c203: e8 70 7c ff ff            callq -0x8390 # 3e78 <malloc>
```
This commit also publishes the `Symtab.callee` function that gives this information.
=> prints the jump destination address and name in the assembly output

lib/bap/bap.mli, lib/bap_disasm/bap_disasm_rec.ml, lib/bap_disasm/bap_disasm_symtab.ml
Uses the same initial starting points when building whole program CFG and symbol table. This improves performance and prevents discrepancies between the set of instructions discovered during the disassembly and the set of instructions that are discovered when we build various graph representations. In certain cases, e.g., in the interworked binaries, such discrepancies could result in an abnormal termiantion of a program.
=> uses function starts as the entires when building the symtab

lib/bap_disasm/bap_disasm_basic.ml, lib/bap_disasm/bap_disasm_calls.ml, lib/bap_disasm/bap_disasm_calls.mli, lib/bap_disasm/bap_disasm_symtab.ml, lib/bap_disasm/disasm.cpp, lib/bap_types/bap_bitvector.ml
Several performance modifications that greatly improves BAP performance on interworked binaries, i.e., the binaries that use more than one encoding. It turned out that switching a disassembler wasn't quite cheap as we had to reset the state and initialize data structures. This is now optimized and we try not to do what is not needed. In addition the symbol table is now built using a single pass over the binary, instead of two passes. Overall, for interworked binaries the performance improvment is close to 50%, i.e., bap disassembles them nearly twice as fast.
=> improves disassembler performance

lib/arm/arm_target.ml, lib/arm/arm_target.mli, plugins/arm/arm_main.ml
The lowest version of LLVM that we still support is 6.0 and it doesn't support ARMv8.4a and above and spurs a warning, when we try to enable it. Therefore, we reduce the upper bound to 3 and, to compensate it, introduce a new command-line option to control the set of attributes passed to the backend disassembler. It is now possible to enable/disable features with `--arm-features=+FEATURE,-FEATURE`. The `+` is optional, so `FEATURE` defaults to enabling the `FEATURE`. For example, to enable newer versions of ARMv8 use the following command-line, `--arm-features=v8.4a,v8.5a,v8.6a`. It is also possible to enable it permanently using a configuration file. For that create a file in the `~/.config/bap/` folder (name doesn't matter) with the following content,
```
arm-features=v8.4a,v8.5a,v8.6a …
```
=> adds `--arm-features` and downgrades the maximum ARM v8.Xa version to 3

lib/bap_types/bap_ir.ml
It turned out that empty subroutines and non-empty subroutines could have had different names.
=> unifies name generation for IR subroutines

lib/bap_types/bap_ir.ml
Extends #1475 and adds special naming scheme for interrupts. Before that the interrupts didn't have any special treatment wrt the names so the corresponding interrupt service routines just got random tids as the name. That was hampering both readability and analysis.
=> implements the naming scheme for interrupts

lib/bap_sema/bap_sema_lift.ml, lib/bap_types/bap_ir.ml, plugins/arm/semantics/aarch64-atomic.lisp, plugins/arm/semantics/aarch64-special.lisp, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/relocatable/rel_symbolizer.ml, plugins/x86/semantics/x86-common.lisp
This primitive is now fully subsumed by the `intrinsic` primitive so there's no need to have two names for the same thing. To update the existing code that uses special, substitute every occurence of `(special :foo)` with `(intrinsic 'foo)`
=> removes the special Primus Lisp primitive

lib/bap_disasm/bap_disasm_driver.ml, lib/bap_disasm/bap_disasm_driver.mli, lib/bap_disasm/bap_disasm_symtab.ml, lib/bap_disasm/bap_disasm_symtab.mli, lib/bap_sema/bap_sema_lift.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.ml
Turns program objects that are external to the program, e.g., intrinsics, interrupt service routines, externally linked subroutines, into IR. The intrinsic calls in particular, are also called to Primus Lifter, the rest of externals will soon follow.
This PR, essentially, enables the lifters to have subroutines so that a heavy operation could now be turned into an intrinsic subroutine that itself reified into a concrete IR and shared among several instructions. We plan to use this feature to concretely lift all basic floating-point operations, and later employ it for handling heavy vector and crypto operations.
=> reifies external subroutines and intrinsics into IR

lib/bap_primus/bap_primus_pos.ml
So far, the Primus Lisp interpreter was requiring that all subroutines had to pass the control to the caller with an explicit jmp term. This was a fair requirement for the disassembled subroutines but is a nuisance for intrinsic subroutines. To make writing intrinsics easier, this requirement is lifted.
=> enables BIR subroutines without an explicit return

plugins/patterns/patterns_main.ml, plugins/patterns/semantics/pattern-actions.lisp
Just passing `--no-patterns` didn't work since the plugin was defining the `promise-function-start` function therefore the `patterns-action` Primus Lisp feature was issuing a missing function type error.
To prevent this, we define a  context class that is instantiated if the plugin is enabled. An alternative solution would be to define the primitive even if the plugin is disabled.
=> enables disabling the patterns plugin

lib/bap_core_theory/bap_core_theory.mli, plugins/bil/bil_float.ml, plugins/bil/bil_float.mli, plugins/bil/bil_main.ml, plugins/bil/bil_semantics.ml, plugins/primus_lisp/primus_lisp_semantic_primitives.ml, plugins/primus_lisp/semantics/ieee754.lisp, plugins/primus_lisp/site-lisp/posix.lisp, plugins/x86/semantics/x86-64-sse-intrinsics.lisp
This PR uses Primus Lisp to specify semantics of the floating-point intrinsic subroutines. To be able to reify floating-point primitives into BIR, we rely
on the floating-point emulator that translates basic operations into corresponding bitvector operations. Since now we each floating-point instruction will be translated only once (as an intrinsic function), we are now able to enable the emulator by default. Before that, enabling the emulator was exploding binaries that have a lot of floating-point operations. The dynamic emulation is now disabled (and we will probably remove it in the future, as the static one works perfectly fine).
The reification of floating-point operations into bitvector operations works only with the BIL theory so other theories will not be affected. To make it …
=> implements floating-point intrinsic subroutines

plugins/byteweight/byteweight_main.ml
The motivation is that byteweight is an aggressive function discovery algorithm that shouldn't be used by default. Analogous algorithms in IDA and Ghidra are also disabled by default. It should be used as the last resort, when other options do not work.
To enable byteweight back use `--byteweight-enable`. To make this persistent, add a file `enable-byteweight.conf` to the `~/.config/bap` folder with the following content,
```
byteweight-enabled = true
```
=> disables byteweight by default

lib/bap_types/bap_helpers.ml
In #1422 the preconditions of Bil.Apply.binop were relaxed to allow operands of different types. This introduced a subtle bug wrt the shifting operations, in particular when the shift right-hand side operand was larger then the left-hand one, the latter was extended and the resulting type and value was incorrect.
=> fixes type unification on binary operation application

lib/bap_mips/bap_mips_target.ml, plugins/mc/mc_main.ml
Re-closes #1407 as #1408 wasn't sufficient to support little-endian MIPS targets. Also fixes an incorrect encodings property of 32 bit MIPS instructions.
=> fixes little-endian MIPS disassembling

lib/bap_core_theory/bap_core_theory_var.ml, lib/bap_disasm/bap_disasm_driver.ml, lib/bap_types/bap_bitvector.ml, lib/knowledge/bap_knowledge.ml, lib/monads/monads_monad.ml, lib/regular/regular_data_write.ml, plugins/disassemble/disassemble_main.ml, plugins/patterns/patterns_main.ml
This PR contains a series of optimizations and tweaks to reduce the memory footprint of BAP. Overall, it gives about 40 to 50 percent improvement. For example, disassembling, lifting, and printing the x86-64 libc.so binary now takes 5GB of RAM, where previously it was nearly 10GB. This is achieved by rewriting the internal representation of the knowledge base (several maps were collapsed into one), improvements in the IO subsystem (to prevent creation of intermediate data structures), and by tweaking the GC parameters. The parameters make GC more aggressive (disassembling /bin/ls now leaves only 130 MB of live data, instead of 221Mb with the default settings, and 400M before the optimizations).
All these improvements are not a compromise between space and time, in fact the timing …
=> reduces memory footprint

Makefile, lib/bap_core_theory/bap_core_theory_pass.ml, lib/bap_types/bap_exp.ml, plugins/bil/bil_semantics.ml
This PR improves legibility of the lifted code by using extract/cast/concat combinations instead of bit masking for assigning aliased subregisters. In addition, it changes the default pretty-printing syntax of BIL by making the `extract` keyword optional in the extract operator, i.e., `extract:56:32[RAX]` will be now printed as just `56:32[RAX]`. Finally, the PR adds several optimization rules for extract/cast/concat combinations so that in the end, the following,
```
00000881: intrinsic:x0 := extract:63:0[extract:127:0[YMM0]]
00000884: intrinsic:x1 := mem[RBP - 0x18, el]:u64
00000887: call @intrinsic:fadd_rne_ieee754_binary with return %00000889
00000889:
0000088a: YMM0 := YMM0 &
0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000
| pad:256[intrinsic:y0]
```
is lifted as, …
=> makes bit-twiddling operations easier to read and analyze

plugins/ghidra/semantics/pcode.lisp, plugins/x86/semantics/x86-64-sse-intrinsics.lisp
The calls to intrinsic operators could not be nested. Ideally, we should either devise an intrinsic ABI that will allow nesting or, at least, capture nested calls and report errors.
=> fixes the encoding of the comparison operators

plugins/x86/semantics/x86-64.lisp
Care should be taken to properly lift the `popq rsp` instruction, therefore, the proposed semantics is, 
```lisp
(defun POP64rmm (ptr _ _ _ _)
(+= RSP 8)
(store-word ptr (load-word (- RSP 8))))
```
which generates,
```
$ bap mc --show-{insn=asm,bil} -- 8f 04 24
popq (%rsp)
{
RSP := RSP + 8
mem := mem with [RSP, el]:u64 <- mem[RSP - 8, el]:u64
}
```
Thanks to @sjcappella for helping with this and see also https://github.com/NationalSecurityAgency/ghidra/issues/4282
=> adds semantics for the x86-64 `popq` instruction

plugins/x86/semantics/x86-64.lisp
I forgot to push the last commit to the branch so the merged semantics is incorrect. Again, great thanks to
@sjcappella for being vigilant!
=> corrects `popq rsp` semantics

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_interpreter.ml, lib/bap_primus/bap_primus_interpreter.mli, lib/bap_primus/bap_primus_lisp.ml, plugins/primus_lisp/primus_lisp_primitives.ml
And uses it to specify various argument passing mechanics. An expression is an lvalue if it is a register, a load (which is a generalization of a pointer), an ite of two lvalues, or a cast (including the extraction) of an lvalue. Or, more formally,
```
lvalue ::= Var _
| Load (_,_,_,_)
| Ite (_,<lvalue>,<lvalue>)
| Cast (_,_,<lvalue>)
| Extract (_,_,<lvalue>)
| Concat (_,_,<lvalue>)
```
The new `Interpreter.assign` primitive is now used to pass and return arguments to and from Primus Lisp interpreter, so now we can pass and return structures and other non-trivial objects.
=> adds the extended lvalue assignment to Primus Interpreter

lib/bap_types/bap_common.ml, lib/bap_types/bap_exp.ml, lib/bap_types/bap_exp.mli, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli, plugins/bil/bil_semantics.ml
Up until now there was no smartness in the BIL smart constructors so that `Bil.(x + y)` was just `BinOp(PLUS,x,y)`. This PR adds some intelligence to smart constructors and teaches them a few identities, e.g., `Bil.(x - x)` will evaluate to `0`. In addition, all constants will be immediately evaluated. The optimization are as lightweight as possible (not to be confused with the BIL simplifications routines that will optimize code recursively).
The code was mostly moved from the BIL semantics implementation that was before that in the bil plugin with a small change to allow ill-formed BIL expressions. In case of the ill-formed expression we will just keep the expression untouched.
=> makes BIL smart constructors smart

lib/bap_c/bap_c_size.ml, lib/bap_c/bap_c_size.mli
Though it is abi-specific in general, apparently most if not all ABI require the structure size to be a multitude of its alignment, so I decided to make it the default.
In addition, adds comprehensive documentation to each method and publishes `padding` and `next_multitude_of` functions to leverage custom alignment/padding implementations.
=> makes all C data type sizes a multitude of their alignment

lib/bap/bap.mli, lib/bap_types/bap_bitvector.ml, lib/bap_types/bap_bitvector.mli
After #1405 the bitvector order function started to take into account, in some cases, the length of the vector so that 0:8 < 0:32, which is not what we want or ever had.
This PR fixes this as well as provides two submodules to the bitvector module, `Unsigned` and `Literal` that provides alternative ordering. The former compares bitvectors unsigned and the latter treat them literally, i.e., compares them including their sizes, signedness, and values.
=> fixes the bitvector order function

Makefile, lib/bap_c/bap_c_abi.ml
Now the type of the argument and the type of its right-hand side agree and the argument type is derived from the C type, not C datum.
=> makes argument passing well-typed

plugins/arm/semantics/thumb-patterns.lisp
Like #1481 but makes it work for the thumb binaries as well. Long story, the thumb plugin is also using a signal that is provided by the patterns plugin so when `--no-patterns` is specified for a thumb binary the disassembly is failing.
Thanks to @bmourad01 for reporting!
=> enables disabling patterns plugin for the thumb binaries as well

lib/bap/bap.mli, lib/bap_primus/bap_primus_value.ml, lib/bap_types/bap_bitvector.ml, lib/bap_types/bap_bitvector.mli
Restores the old default order for bitvectors that was broken in #1502. Despite what it is said in #1502, the default order of bitvectors was always taking the size into account and ordered `0:0` before `0:1`. It is even clearly stated in the documentation. Therefore, this commit restores the default order (and makes sure that the hash functions are consitent with the order).
Also adds a new order, `Signed_value_order` and renames the newly introduced orders with longer names that are more descriptive and has less chances to clash with the existing module names (as the Bitvector module is commonly locally-opened).
Finally, changes the default order for `Primus.Value`, which is now `Signed_value_order`. Note that the change of `Primus.Value` order doesn't really affect any Primus or Primus …
=> restores the old bitvector order, changes the Primus Value order

lib/monads/monads.mli
Hi,
I forgot about issue #1354 which I opened last year, but now I finally wanted to finish it.
I tried implementing it with a higher-order functor that includes the T1 & Make modules, but I do not think that this will work.
```
module MakeMakeT (TYPE_F: functor(T: T1) -> sig ??? end) (F: (M: Monad.S) -> sig ??? end) (M: Monad.S) : Monad.S = struct
include TYPE_F(M)
include F(M)
end
(* in module Option/List/... *)
MakeT(M) = MakeMakeT(T1)(Make)(M)
```
For `TYPE_F` the resulting signature is mostly the same for different monads (i.e. one that includes types `t`, `m` & `e`) but for `F` the signatures are of course very different between monads since they have different functions. And iiuc you cannot pass a signature itself to a functor. So I think this approach does not work.
Therefore I …
=> adds an example on how to create a monad transformer stack (#1354)

plugins/arm/semantics/arm-bits.lisp, plugins/arm/semantics/thumb.lisp, plugins/thumb/thumb_bits.ml, plugins/thumb/thumb_bits.mli, plugins/thumb/thumb_main.ml
Thanks to `--print-missing` I was able to fill these in.
This also adds the `i-shift`  helper to the `arm-bits` file, which will make it easier to deal with register-shifted operands.
=> Adds more missing Thumb instructions

plugins/x86/x86_disasm.ml
Adds disassembly to packed binop for padd{b,w,d,q}.
=> x86_disasm: support padd instructions

lib/bap_c/bap_c_abi.ml
It looks like a default promotion rule in most if not all ABI.
=> uses signed casts for promoting arguments

lib/x86_cpu/x86_target.ml, lib/x86_cpu/x86_target.mli
Leverages `Theory.Target.register` and `Arg.Language` to clean up the
target registration and calling convention specification of x86 ABIs.
=> reimplements x86 targets using the new infrastructure

lib/arm/arm_target.ml, lib/arm/arm_target.mli, plugins/arm/arm_gnueabi.ml, plugins/arm/semantics/aarch64-arithmetic.lisp, plugins/arm/semantics/aarch64-atomic.lisp, plugins/arm/semantics/aarch64-branch.lisp, plugins/arm/semantics/aarch64-data-movement.lisp, plugins/arm/semantics/aarch64-helper.lisp, plugins/arm/semantics/aarch64-logical.lisp, plugins/arm/semantics/aarch64-pstate.lisp, plugins/arm/semantics/aarch64-special.lisp, plugins/arm/semantics/aarch64.lisp, plugins/arm/semantics/arm-bits.lisp, plugins/arm/semantics/arm.lisp, plugins/arm/semantics/thumb-patterns.lisp, plugins/arm/semantics/thumb.lisp, plugins/primus_lisp/site-lisp/libc-init.lisp, plugins/primus_lisp/site-lisp/types.lisp
This PR rewrites the ABI specifications for ARM32 and ARM64. We also leverage the new target registration facility and tweak the target hierarchy of the ARM architectures. The naming scheme is now much closer to what is used in GNU and therefore are much more intuitive. For example, it is now possible just to specify `--target=arm` or `--target=aarch64` or even `--target=arm-linux-gnueabi`. As usual, use `bap list targets` for the full list. The name `arm` is now the catchall architecture for ARM32 (aka Aarch32), and `aarch64` is the catchall for all armv8. A slightly breaking change is that the new name for the arm parent target is `arm-family` not `arm` as it was before. The abi names were also slightly changed to match the names used by GCC and Debian. However, since the target …
=> reimplements ARM ABI and target specification

lib/bap_c/bap_c_abi.ml, lib/bap_c/bap_c_abi.mli, lib/bap_c/bap_c_data.ml, lib/bap_c/bap_c_data.mli, lib/bap_c/bap_c_term_attributes.ml, lib/bap_c/bap_c_term_attributes.mli
The layout fully describes a representation (memory layout) of C objects. This PR adds the layouts as well as a function to compute them. In addition, the ABI pass will compute layouts for all arguments (you can view the result using the following command-line arguments`-d --print-bir-attr=c.layout`).
The below interaction demonstrates how layouts work.
```ocaml
let cici = C.Type.(structure "cici" [
"v1", basic `char;
"v2", basic `sint;
"v3", basic `char;
"v4", basic `sint
]);;
val cici : C.Type.t =
struct cici {
char v1;
signed v2;
char v3;
signed v4;
};
- : C.Data.layout =
{
[<v1 : [char : 8]> : 8],
[<undef> : 24],
[<v2 : [signed : 32]> : 32],
[<v3 : [char : 8]> : 8],
[<undef> : 24],
[<v4 : [signed : 32]> : 32]
}
"v1", basic `char;
"v2", basic `sint;
"v3", basic `char;
"v4", basic `sint …
```
=> adds C data type layout

lib/bap_c/bap_c_abi.ml, lib/bap_c/bap_c_abi.mli
The existing `reference` method is used only to pass hidden references (like this, or a structure to be returned). However, some ABI, like powerpc, are passing structures by references.
=> adds the pass by reference argument passing method

.merlin, lib/bap_powerpc/bap_powerpc_target.ml, oasis/powerpc, plugins/powerpc/powerpc_abi.ml, plugins/primus_lisp/site-lisp/libc-init.lisp, plugins/primus_lisp/site-lisp/types.lisp
The target names are now in line with the conventional naming schemes and the calling convention supports arbitrary arguments. The CPU model is also refined with more registers assigned their roles.
=> restructures powerpc targets and reimplements ppc32 eabi

plugins/x86/x86_endbr.ml
They could be enabled with the `--x86-cet-enabled` command-line option, but by default there's no need to have them as calls everywhere.
=> turns x86 endbr instructions into nops by default

lib/bap_types/bap_ir.ml
This change prevents knowledge base conflicts that happen when we apply name mangling on subroutines.
=> prevents knowledge conflicts on mangled names

plugins/thumb/thumb_branch.ml
It was checking `rn <> 0` when it needs to check `rn = 0`.
=> Fixes lifting of Thumb `cbz` instruction

lib/bap_taint/bap_taint.ml, lib/bap_taint/bap_taint.mli
It may be useful to interrogate some property of the `Taint.Rel.t` datatype, most obvious being the `relation_kind`.
=> adds `Taint.Rel.{equal,compare}`

lib/bap_plugins/bap_plugins_units.ml
This commit fixes the `bap.top` library and the `baptop` executable so that they can now be used. Before that, they were failing with
```
Exception:
(Invalid_argument
"The dynlink.cma library cannot be used inside the OCaml toplevel")
```
The problem was that we were trying to use the dynlink facilities to track the missing units (before that we were using findlib for that so it was working). However, for toplevel we don't need to do this, as the toplevel loader will keep track of the loaded dependencies for us.
=> fixes bap.top and baptop

plugins/bil/bil_ir.ml
Contraction / normalize conditions changed in 2.5.0 which causes IR
normalization to drop the "when RCX <> 0 ... goto ..." for the instruction
"rep cmpsb" (\xf3\xa6).
This patch adds an extra keep/weak check to can_contract that keeps the
when-cnd-goto made when reifying the rep while loop.
=> prevents IR block contraction on unconditional edges

plugins/primus_x86/primus_x86_loader.ml
After a call to the RSP target we have to restore the RSP value. The component that is responsible for that was doing the correction via the `Env` inteface directly so that the correction wasn't observable that was preventing tracking the change in the RSP value.
=> makes RSP correction for x86 targets observable

lib/bap_build/bap_build.ml
This is a hotfix that prevents double-loading of certain bap core libraries (e.g., bap-knowledge, bap-core-theory, bap-main, etc) when using the baptop executable or bap.top library. It is not 100% bulletproof against all double-loads but the problem only affects the toplevel environment and builds that use opam-repository and oasis, which we will eventually sunset after a full move to the dune build system.
Problem Description
-------------------
The BAP plugin system is designed to be self-contained so that all dependencies could be loaded directly from the plugins. This let us deploy BAP in a standalone form, i.e., on systems that lack OCaml installation. This feature, of course, leads to bloated plugins. To partially alleviate this issue, we defined a set of compilation units that are …
=> prevents double-loading of the bap packages in the toplevel

lib/regular/regular_data_write.ml
Some definitions of the write type class were generating incorrect code due to a missing parameter.
=> fixes copy and blitting implementations in regular

lib/bap_primus/bap_primus_lisp_parse.ml
In Primus Lisp, we can use the `defstubst` keyword to define the following:
```
(defsubst my-string :ascii "i am a string\000")
```
The Primus Lisp parser is meant to see the `:ascii` token and then desugar the string into a list of hex bytes. However, the parser currently does not drop this first token and subsequently fails to desugar the string. Furthermore, the string must be unquoted before it can be processed.
This also affects the use of the `:hex` keyword for a similar reason.
=> Fixes parsing of `defsubst` when a syntax is specified

plugins/arm/semantics/aarch64-logical.lisp
Previously, the BFM macro did not account for register widths while extracting and concatenating and also did not concatenate some parts of the old destination register.
First, we'll show the old behaviour.
```asm
bfm w3, w17, #3, #5
R3 := 31:29[R3].5:3[R17]
```
Here, r = 3 and s = 5 for the s >= r case. This should take bits from the middle of R17 and places them at the lower bits of R3. Slice of R17 is correct but slice of R3 is only 3 bits wide when it should be 29 bits wide.
```asm
bfm w3, w17, #6, #4
R3 := low:5[31:0[R17]].low:6[31:0[R3]]
```
Now, r = 6 and s = 4 for the s < r case. This should take the lower bits of R17 and inserts them into R3. Again, slice of R17 is correct but the slice of R3 is too small. This is also missing a concat with R3's upper bits which were not filled …
=> Fix BFM in ARM Primus Lisp semantics.

plugins/primus_loader/primus_loader_basic.ml
A typo made it so that we didn't allocate enough space for the `environ` table.
=> Fix alloc size when passing `--run-env`

plugins/primus_dictionary/primus_dictionary_main.ml
Corrected dict-length to map to Length module instead of First module.
=> Corrected primus_dictionary_main.ml

Makefile, lib/bap_sema/bap_sema_lift.ml
We mangle names in `bap_sema_lift.ml` when there are conflicting subroutine names. However, it creates a new subroutine term (to be KB friendly), and we were forgetting to preserve the old attributes dictionary in this new subroutine.
=> Fix not propagating term attrs in `mangle_names` during lifting

lib/bap/bap.mli, lib/bap_types/bap_helpers.ml, lib/bap_types/bap_helpers.mli
For convenience, we can convert a BIL type to a Core Theory sort.
=> Expose `Bap_var.sort_of_typ`

oasis/stub-resolver, plugins/stub_resolver/stub_resolver.ml, plugins/stub_resolver/stub_resolver_tests.ml
The tests didn't reflect the new behavior of the stub resolver from #1547. The idea is that now we can have multiple stubs link to the same implementation, as is common when linking more than one shared library.
The algorithm is also cleaned up to use ~~`Bap_relation`~~ `Graphlib`, which ends up being simpler and produces better results.
=> Fixes the stub resolver tests

lib/bap_primus/bap_primus.mli, lib/bap_primus/bap_primus_memory.ml, lib/bap_primus/bap_primus_memory.mli, plugins/primus_loader/primus_loader_basic.ml
When we perform relocations on object files, we do the linker work not the loader, therefore we do not need to check if the memory is writable or even loadable. The easiest option is to extend the Primus memory interface with primitives that perform writing without any checks.
=> allows bypassing checks when storing memory, uses it for relocations

.github/workflows/opam.yml, oasis/plugins
When bap installed from the testing repository it fails on frontends due to a missing dependency
```
Bap_plugins_loader_backend referenced from
/home/runner/work/bap/bap/_opam/lib/bap-plugins/bap_plugins.cmxa(Bap_common)
```
Also improves the opam workflow and adds functional checks.
=> fixes installation from opam

lib/bap/dune
This will break too much downstream code, as well as our own tooling like bapbuild
=> allows to use bap instead of bap-std

oasis/plugins
It's unclear how it was passing the tests but there is still a missing module the bap-plugins OASIS specification that breaks downstream builds.
=> adds a missing module to the OASIS specification of bap-plugins

lib/bap_disasm/bap_disasm_driver.ml
In binaries with interworking, it is expected that the destinations of some control flow instructions will have a different encoding than said instructions (e.g. `blx` on ARM/Thumb). However, the rules in the disassembler were too restrictive, as they assumed that the destination encoding would have a join with the source encoding.
This PR relaxes the restriction by assuming at first the `Theory.Language.unknown` encoding. If no encoding can be found then we can then assume that the source encoding is to be used.
=> fixes a bug in instruction encoding propagation

plugins/primus_lisp/semantics/ieee754.lisp
They were using `cast-sfloat/cast-float` instead of `cast-sint/cast-int`.
=> Fixes a typo in the Primus Lisp IEEE754 semantics

plugins/arm/semantics/thumb.lisp
The helper `set-nzcv-from-registers` calls additional helpers `overflow` and `carry`, which compute their results from the addition of two integers. However, the `cmp` instruction computes the subtraction of two integers, and this wasn't reflected in the usage of this helper function.
Also, the `t2ADDrs` semantics had a typo in it.
=> Fixes a few bugs in the Thumb semantics

plugins/primus_lisp/lisp/pointers.lisp
Corrects the array-set macro for Primus Lisp by adding the type to the call to ptr+.
=> Corrects array-set macro for Primus Lisp.

bap-llvm.opam, bap-llvm.opam.template, lib/bap_llvm/config/llvm_configurator.ml, lib/bap_llvm/llvm_disasm.cpp, lib/bap_llvm/llvm_pdb_loader.hpp, oasis/llvm, vagrant/trusty64/Vagrantfile, vagrant/xenial64/Vagrantfile
It seems that with LLVM 15 a few fixes are needed to get BAP to compile, including linking against `libzstd`.
=> Adds compatibility with LLVM 15

plugins/riscv/semantics/riscv.lisp
Added semantics for the following instructions:
- BGE 
- C_BGE
- C_SW
Changed semantics for the following instructions:
- C_LUI
=> Add (C_)BGE and C_SW and correct C_LUI RISC-V Semantics

bap-llvm.opam.template, lib/bap_llvm/config/llvm_configurator.ml, lib/bap_llvm/llvm_disasm.cpp
This must be manually enabled by setting the variable `llvm-shared` to a true value in the current opam switch, similar to the existing `llvm-config` variable used by conf-bap-llvm.
* bap_llvm/config/llvm_configurator.ml: use `llvm-config --shared-mode` to get the appropriate linking mode
* bap_llvm/llvm_disasm.cpp: add missing include for Optional.h
=> Support linking with LLVM shared libraries

lib/bap_llvm/llvm_disasm.cpp, lib/bap_llvm/llvm_loader_utils.hpp, lib/bap_llvm/llvm_primitives.cpp
This also covers #1595.
There was a really tricky segfault to track down in the call to `MCInstrDesc::mayAffectControlFlow`, see my comment as well as [here](https://github.com/llvm/llvm-project/blob/release/17.x/llvm/include/llvm/MC/MCInstrDesc.h#L200). This comment is also present in [LLVM 16](https://github.com/llvm/llvm-project/blob/release/16.x/llvm/include/llvm/MC/MCInstrDesc.h#L200).
=> Fixes for LLVM 17 (and 16)

plugins/primus_test/primus_test_main.ml
Simple refactoring to prevent getting an incomplete trace and fail earlier. Saves hours of debugging.
=> better code and fixes potential debugging headache

bap-byteweight.opam, dune-project, lib/bap_byteweight/bap_byteweight_signatures.ml
Addresses #1607, taking the suggestion by @xavierleroy
=> Fix use of camlzip in byteweight

bap-byteweight.opam, dune-project, lib/bap_byteweight/bap_byteweight_signatures.ml
As noted by @xavierleroy in #1609, we can ensure compatibility with earlier versions of camlzip in light of the recent changes w.r.t. the `extra` field being removed in 1.12.
=> Ensure compatibility with `camlzip` versions before 1.12

.github/workflows/alpine.yml, .github/workflows/archlinux.yml, .github/workflows/debian-testing.yml, .github/workflows/fedora.yml, .github/workflows/full.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/oasis.yml, .github/workflows/opam.yml, .github/workflows/publish-docker-image-release.yml, .github/workflows/publish-docker-image.yml, .github/workflows/release.yml, .github/workflows/ubuntu-bionic.yml, .github/workflows/weekly-regress.yml, plugins/x86/x86_operands.ml
Occasionally, llvm refines their instruction definitions and change the number of operands, for example this [commit][1] added an extra destination register operand. For the old lifters we used a pretty strict rules for operands deconstructing and for the bts, btc, and btr instructions we were expecting two operands (now there are three of them).
I decided to relax the deconstructor instead of changing the definition of instructions, first to preserve backward compatibility with the older versions of llvm and second because many other instructions could be affected by the same changes from the llvm side, and I don't see any harm if we will accept instructions with one more argument, knowing that destinations are always prepended.
[1]: …
=> relaxes x86 operands deconstructor to address llvm changes

.github/workflows/nightly.yml, .github/workflows/opam.yml, .github/workflows/release.yml, .github/workflows/weekly-regress.yml
- checkouts in a separate folder to prevent overwritting the switch;
- updates OCaml versions to the latest 4.x branch.
=> fixes nightly and weekly regression tests, updates OCaml versions

.github/workflows/full.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/oasis.yml, .github/workflows/opam.yml, .github/workflows/release.yml, bap-llvm.opam, bap-primus-symbolic-executor.opam, dune-project, tools/install-ghidra.sh
- also drops the upper bound on the z3 package, as the old versions do not work on newer distributions.
=> upgrades to ubuntu-latest and adds ghidra installation script

README.md, plugins/primus_lisp/lisp/init.lisp, plugins/x86/semantics/test.t, plugins/x86/semantics/x86-64-sse-intrinsics.lisp, plugins/x86/semantics/x86-64.lisp, plugins/x86/x86_disasm.ml
These instructions apply bitwise operations on the packed data, in total 16 instructions. Suprisingly, out of this family we already handled the packed xor variant, but the semantics was very ineffcient as it wasn't using the fact that all bitwise operations are distributive over concatenation.
=> adds semantics for `[v]{and[n],or,xor}p{d,s}` instructions

plugins/x86/semantics/test.t, plugins/x86/semantics/x86-64.lisp
Previously, we only supported SSE and SSE2 variants of pmuldq and didn't support any of pmuludq (unsigned packed multiplication).
=> adds semantics for pmuludq and extends AVX/AVX2 pmuldq

docker/ubuntu/bionic/Dockerfile
It looks like that the newest version of z3 doesn't build on the older ubuntu distributions. We can try constraining them to the latest version that was providing the static version.
=> fixes docker publish workflow
