BinaryAnalysisPlatform/bap

python/bap.py

This patch will solve the problem, when qira outruns the amount of free
TCP ports on the system. The proposed solution is to use a single pool
of connections, upper bounded by a number less then the amount of free
ports on typical linux system (28k on my box).

Serialize HTTP requests to one pool.

---

.gitignore
src/readbin/ida.ml
src/readbin/ida.mli
src/readbin/readbin.ml
src/readbin/symbols.ml

Fixed few issues (that weren't actually mac specific).
Also, added demangling for IDA symbols.

Add IDA support on Mac OS X

---

lib/bap_disasm/bap_disasm_rec.ml

This fixes two real and one potential bug.
real1 - a fallthrough was added automatically, when we reach the end of
block without the destination, when the next address starts another
block. Now it is added only if the end of block is implicit, i.e. it
wasn't previously recognized as end.
real2 - some instructions, (c.f., #117) are not recognized correctly by the lifter,
but still pretty understandable to our backend, e.g., `is_return` evaluates to true. 
To get rid of excessive fall-throughs I've added an explicit check.
possible - if a list of destinations, extracted from instruction
contains explicit fallthrough (that is currently impossible), then
we will recognized it as a jump. Just in case, if someone will change
the behavior of `dests_of_bil` or `dests_of_basic`, I've made check …

Fixes several issues in CFG reconstruction.

---

lib/bap_disasm/bap_disasm_rec.ml
lib_test/bap_disasm/test_disasm.ml

This PR fixes the issue that with a small input (e.g., "\xc3")
`disassemble` function didn't return any block at all. This PR
also fixes some other related potential bugs, like passing a
memory region, containing only N moves, will now return a basic
block.

Fixes CFG reconstruction on micro examples.

---

python/bil.py
src/server/adt.ml

Fixes some typos concerning the python bindings.

python ADT fixes

---

_oasis
lib/bap/bap.ml
lib/bap_disasm/bap_disasm_block.ml
lib/bap_disasm/bap_disasm_block.mli
lib/bap_disasm/bap_disasm_rec.ml
lib/bap_sema/bap_lnf.ml
lib/bap_sema/bap_lnf.mli
lib/bap_sema/bap_sema.ml
lib/bap_sema/bap_sema_std.ml
lib_test/.merlin
lib_test/bap_image/test_memmap.ml

This PR will add support for imperative CFG, and fix a nasty bug in CFG recontruction algorithm

Extend cfg and fix bug

---

src/readbin/ida.ml
src/readbin/readbin.ml

Now IDA-32 is used by default notwithstanding the platform.
Also this PR fixed issues with IDA integration.

Switched to IDA-32

---

lib/bap_image/bap_memmap.ml
lib/bap_image/bap_memmap.mli
lib/bap_image/bap_table.mli

The implementation is modeled after map, mapi, and so on.

This PR implements iter, iteri, fold for Memmap.

---

src/readbin/cmdline.ml
src/readbin/options.ml
src/readbin/readbin.ml

This will be needed, after we will merge with #163.

Add  `--loader` option to `bap-objdump`

---

python/bap.py

Actually there is some bug in an upstream, that breaks all chunked GET
requests. I've switched to POST method in all requests, even if it is
actually a get.
But there was still a funny bug, due to which all requests were GET.
Also, fixed an issue with checking connection to bap server.

Resolve #173

---

CHANGES.md
README.md
_oasis
lib/bap/bap_plugins.ml
opam
src/readbin/readbin.ml

Also, fixed project application, added `CHANGES.md`, updated
`README.md` and bumped version in `_oasis`.

Plugins can now be loaded with findlib.

---

lib/bap_image/llvm_binary_stubs.hpp

Now, it's available to get entry point address from 64-bit PE executables

fixed PE-64 entry point address

---

lib/bap/bap.mli

Changes are only for the "Overview" section (not API, etc).

General spelling and grammar touch-ups

---

lib_test/bap_image/test_image.ml

Fix test_image for a 32-bit OS in i686.

Test image is fixed for a 32-bit OS.

---

src/readbin/cmdline.ml
src/readbin/find_starts.ml
src/readbin/fsi_benchmark_main.ml

Clean the code by Maverick's suggestion.

Followup for adding --dump-symbols pull request (PR #220)

---

lib/bap/bap.mli
lib/bap/bap_project.ml
lib/bap/bap_project.mli
lib/bap_sema/bap_ir.ml
lib/bap_types/bap_vector.ml

Added the forgotten function. Also small fixes:
- Vector now ignores non-positive capacities;
- Slightly better? pretty-printing for phi-nodes.

Added `Project.with_program`.

---

lib/bap_image/bap_table.ml

It wasn't really useful, and implemented incorrectly.

Remove caching from Table data structure.

---

_oasis
lib/bap/bap.mli
lib/bap_disasm/bap_disasm_arm_abi.ml
lib/bap_disasm/bap_disasm_arm_abi.mli
lib/bap_image/bap_memory.ml
lib/bap_sema/bap_sema.ml
lib/bap_sema/bap_sema_abi.ml
lib/bap_sema/bap_sema_abi.mli
lib/bap_sema/bap_sema_free_vars.ml
lib/bap_sema/bap_sema_free_vars.mli
lib/bap_sema/bap_sema_lift.ml
lib/bap_sema/bap_sema_ssa.ml
lib/bap_sema/bap_sema_ssa.mli
lib/bap_types/bap_exp.ml
lib/bap_types/bap_exp.mli
lib/bap_types/bap_graph.ml
lib/bap_types/bap_helpers.ml
lib/bap_types/bap_helpers.mli
lib/bap_types/bap_ir.ml
lib/bap_types/bap_ir.mli
lib/bap_types/bap_ir_graph.ml
lib/bap_types/bap_ir_graph.mli
lib_test/bap_sema/test_ir.ml
lib_test/bap_types/test_graph.ml

1. Moved ssa transformation into the library (Sub.ssa)
2. Reimplemented function parameters reconstruction
(currently works only for ARM, but it is not ARM-specific,
just need some bookeeping to enumerate other calling-conventions)
3. Added few useful algorithms, like free_vars, substitute, etc
See, Exp, Stmt, Def, Phi, Jmp, Blk and Sub modules.
4. Made Tid parseble from string, also added support for symbolic tids
5. Fixed a bug in a memory printer (introduces by a #235 fix).
6. Fixed expression simplification algorithm.
7. Fixed IR lifter, now it is a little bit more robust. But still much
can be done.

Added SSA, argument reconstruction, an much more.

---

_oasis
bapdoc.ml
lib/bap/bap.mli
lib/bap_sema/bap_sema.ml
lib/bap_types/bap_graph_regular.ml
lib/bap_types/bap_graph_regular.mli
lib/bap_types/bap_graph_regular_intf.ml
lib/bap_types/bap_ir_callgraph.ml
lib/bap_types/bap_ir_callgraph.mli
lib/bap_types/bap_ir_graph.ml
lib/bap_types/bap_ir_graph.mli
lib/bap_types/graphlib.ml

See `Program.to_graph` and `Graphlib.Callgraph`.

Added a callgraph.

---

CHANGES.md
README.md
_oasis
bapdoc.ml
lib/bap/bap.mli
lib/bap_sema/bap_sema_abi.ml
lib/bap_types/bap_ir.ml
src/bap_mc/bap_mc.ml

final touches before the release:
- updated release files and documentation
- bap-mc will not fail if lifting failed (addresses #270)
- added support for System V AMD64 ABI
- fixed free_vars in SSA form.

releasing 0.9.9

---

Dockerfile

Adds a Dockerfile which will build a dev container.

Add docker container build

---

_oasis
bapbuild.ml
lib/bap/bap.mli
lib/bap_disasm/bap_insn_aliasing.ml
lib/bap_sema/bap_sema_abi.ml
lib/bap_types/bap_biri.ml
lib_test/bap_disasm/test_disasm.ml
opam
src/readbin/bap_main.ml
src/readbin/ida.ml
src/readbin/text_tags.ml

This is a technical update fixing several bugs:
1. fixed term evaluation order in biri
2. added forgotten index functions to vector
3. some housekeeping.

biri fixes, vector functions.

---

lib/bap_sema/bap_sema_lift.ml

Several corner cases (that are likely occur only when we're lifting some
junk from data) are handled.
The cpuexn instruction lifting is completely rewritten, as previously it
was incorrect. The return label will target to a trampoline block, that
will either a terminal block, if no code follows the cpuexn, or will
redirect to a fall-through block. This actually raises a question,
whether we should make a return label optional in the interrupt term.
Added check that a call is not conditional, to handle conditional
calls. The check relies on a BIL representation, rather on a backend
kind mechanism, to ensure that there is no controversy between the
recursive descent disassembler and IR lifter.

Fixed IR lifting procedure

---

oasis/bap-std
oasis/byteweight-frontend
oasis/cache
oasis/common
oasis/traces
plugins/byteweight/byteweight_main.ml
plugins/llvm/llvm_disasm.cpp
setup.ml.in
src/bap_cmdline_terms.ml
src/bap_fmt_spec.ml

This PR includes a set of fixes, that were revealed during opam release
preparation.
it also fixes #352.

Preparing the opam release

---

oasis/api
plugins/api/.merlin
plugins/api/api/posix
plugins/api/api_main.ml
tools/build_plugins.sh

The new name for the header is api. The pass utilizes
the new `autoload` feature, and applies known APIs on
the program. APIs are bundled with the plugin itself.
New API's can be added by providing a C header file.

Imported header plugin from bap-plugins

---

lib/bap/bap.mli
lib/bap_sema/bap_sema.ml
lib/bap_sema/bap_sema_taint.ml
lib/bap_sema/bap_sema_taint.mli
oasis/bap-std

This is a useful abstraction, that can be used by many analysis, so
it would be a good idea to standardize it.

Add Taint module to Bap.Std

---

lib/bap_types/bap_biri.ml

The new strategy is more clean and easy to reason about. And it looks
like that the previous contained bugs, since the semantics of execution
has changed. So this can be also considered as a bug fix.

Fixed evaluation biri strategy

---

lib/microx/microx_concretizer.ml
lib/microx/microx_concretizer.mli
oasis/propagate-taint
plugins/propagate_taint/propagate_taint_main.ml
plugins/propagate_taint/propagator.ml
plugins/propagate_taint/propagator.mli

This PR adds caching to the taint propagation pass.

cache taint propagation

---

plugins/api/api/posix
plugins/api/api_main.ml

This PR adds more attributes to the posix API, mostly for
`string.h` and `unistd.h`, the latter being most important,
as it contains lots of security critical functions.
It also fixes parsing function for `nonnull` attribute.

add more gnu attributes

---

oasis/objdump.setup.ml.in
plugins/objdump/objdump_config.ml.ab
plugins/objdump/objdump_main.ml

since on macports objdump is called gobjdump.

add objdump-path configuration option

---

plugins/warn_unused/warn_unused_main.ml

Define passes as arguments, so that cmdliner will not raise exceptions
or otherwise prevent us from calling passes

Fix warn-ununsed argument parsing

---

plugins/cache/cache_main.ml

Use int64 for cache size

---

lib/bap_ida/bap_ida.ml

Now it is possible to debug IDA with `BAP_IDA_DEBUG` environmental
variable. If it is greater than `1`, then an autonomous mode will be
disabled, and in case of error an error dialogue will pop up. If it
is greater than `2`, then the library will not clean after itself,
leaving databases,scripts and all the intermediate stuff.

better IDA debugging

---

plugins/api/api_main.ml
plugins/byteweight/byteweight_main.ml
plugins/demangle/demangle_main.ml
plugins/llvm/llvm_main.ml
plugins/map_terms/map_terms_main.ml
plugins/phoenix/phoenix_main.ml
plugins/print/print_main.ml
plugins/x86/x86_main.ml

This PR updates the remaining plugins to use the `Config` interface.

Config plugins v2

---

plugins/warn_unused/warn_unused_main.ml

fix method overloading in warn-unused marker class

---

lib/bap/bap.mli
lib/bap_types/bap_ir.ml
lib/bap_types/bap_ir.mli

use (!!) instead of (!) to fix the clash

---

CHANGES.md
lib/bap/bap.mli
lib/bap_image/bap_table.mli

fix https://github.com/BinaryAnalysisPlatform/bap/issues/576
- added comments for some functions in Memory.Table module ;
- added `existsi` and `for_alli` functions that were hidden before

added documentation to Memory.Table module

---

README.md

updated links to docs for 1.1.0

updated links to docs

---

lib/bap_disasm/bap_disasm_source_factory.ml
lib/regular/regular.mli
lib/regular/regular_bytes.ml
lib/regular/regular_bytes.mli

fixed https://github.com/BinaryAnalysisPlatform/bap/issues/605
solved `bap` compilation problems with compiler version 4.04.0

bap is compilable with 4.04.0 compiler now

---

lib/bap_disasm/disasm.hpp
lib/bap_llvm/llvm_disasm.cpp

fixed few minor warnings in c++ code

fixed few compilation warnings

---

lib/bap/bap.mli
lib/bap/bap_project.ml
lib/bap/bap_project.mli

fix https://github.com/BinaryAnalysisPlatform/bap/issues/612
added a function to delete attribute from project

delete attribute function in `Project` module

---

CHANGES.md
README.md
oasis/common
tools/binary-release.sh
tools/deb-build.sh
tools/opam-release.sh

* bumped version
* updated changes
* updated README
* added release tools:
- binary-release will prepare deb and rpm packages
- opam-relese will release to opam

prepares to 1.2.0 release

---

oasis/beagle
tools/binary-release.sh

also adds an automatic generation of tgz binaries.

add lost beagle file

---

README.md

This is to tell people how to use llvm3.8.

Added documentation abotu llvm3.8

---

lib/bap_image/bap_memory.ml

As a continuation of #680, this PR will reduce the memory footprint of
the memory representation in bap, the `mem` type. As an optimization, we
were precomputing a memory accessors during the construction of a memory
object. Although, it might save some time it didn't at all, as the
memory access operations are rarely used if used at all. Thus, this PR
removes the precomputed getters from the memory, and moves all the check
to the time of an accessor invocation.
As a result, this reduces the size of memory representation by 10
words (80 bytes on amd64). In total with the #680, this will reduce
memory representation from 21 words to only 7.

reduces the memory representation RAM consumption

---

docker/Dockerfile
vagrant/jessie64/Vagrantfile

removed installation of `conf-llvm` package

removed conf-llvm install

---

plugins/x86/x86_lifter.ml

There are few instructions where we do need to sign-extend operand, e.g.
`sub r64 imm32` instruction, where the `imm32` value should be sign-extended to 64 bits. Also affects `or`, `push`, `sbb` and `test` instructions.
A code looks a bit repetitive, but it was done for a reason of readability.
E.g. if I write just a single function like `extend_small_imm` it will look as  
the following:
```
| Push(t, o) ->
let o = extend_small_imm o  t in
....
```
so one could think that any `push` operand is immediate and need to be sign-extended.

small imm sign-extending 

---

lib/monads/monads.mli

P.S. The Monads library is very neat. Thank you!

Fix grammar inside a comment

---

lib/bap_elf/elf_parse.ml
oasis/elf

Changes deps from bitstring<3.0.0 -> bitstring>=3.0.0

switch to bitstring.ppx

---

lib/bap_types/bap_helpers.ml

1) fixed bug for XOR simplification
2) added/edited branches for extract and cast simplification

few minor changes in Bap_helpers

---

lib/bap/bap_project.ml
src/bap_main.ml

rewritten merge-sources function. We don't need to wait for all sources to produce a result anymore.

Merge sources

---

opam/opam

update adds mips-related tests

synchronizes testsuite with bap-testsuite repo

---

lib/bap/bap.mli
lib/bap_disasm/bap_disasm_linear_sweep.ml
lib/bap_disasm/bap_disasm_linear_sweep.mli

fix https://github.com/BinaryAnalysisPlatform/bap/issues/709

adds optional arg to linear sweep disassembler interface

---

lib/graphlib/graphlib.mli
lib/graphlib/graphlib_graph.mli

fixes https://github.com/BinaryAnalysisPlatform/bap/issues/714

adds type equality between equiv and Equiv.t

---

oasis/common
oasis/primus-test
oasis/primus-test.setup.ml.in
oasis/taint
oasis/taint.setup.ml.in

Renamed oasis files and env variables for bap-taint and bap-primus-test libraries.
Also edited bap version.

fixes oasis environment

---

lib/bap/bap.mli
lib/bap_types/bap_helpers.ml

As it was observed and reported by @ethan42 the normalization procedure may duplicate and rearrange expressions that have observable effects (i.e., expressions that are non-generative in our parlance), that may change semantics of normalized expressions. The root of the problem is the presence of expressions, that have side effects, such as load and store expressions. This PR resolves this issues by restricting the First BIL Normal Form (BNF1) from having non-generative expressions in certain positions, exactly those that would be duplicated during the BNF2 normalization. The absence of non-generative expressions in the duplication points is ensured by hoisting them into separate statements, while preserving the order and the number of operations. Since, this transformation produces BIL …

fixes BIL normalization procedure

---

.run_travis_tests.sh
.travis.yml
.travis_install.sh
Makefile

This PR updates our travis environment by adding one more job with `bil` verification.

Bil test integration

---

lib/bap_primus/bap_primus_interpreter.ml
lib/bap_primus/bap_primus_lisp.ml
lib/bap_taint/bap_taint.ml
lib/bap_taint/bap_taint.mli
plugins/primus_lisp/lisp/init.lisp
plugins/primus_promiscuous/primus_promiscuous_main.ml
plugins/run/run_main.ml

This is a bunch of small fixes that I've discovered while working on Primus based analysis. Most of them are pretty small. The main breakthrough is the fix of the promiscuous mode, that was killing taints in the promiscuous branches.

a few fixes to primus et al

---

lib/bap_disasm/bap_disasm_reconstructor.ml

This PR fixes a BUG in reconstructor, where we actually ignore lots of calls

fixes bug in reconstructor

---

lib_test/powerpc/.merlin
lib_test/powerpc/powerpc_add_tests.ml
lib_test/powerpc/powerpc_arith_tests.ml
lib_test/powerpc/powerpc_branch_tests.ml
lib_test/powerpc/powerpc_compare_tests.ml
lib_test/powerpc/powerpc_cr_tests.ml
lib_test/powerpc/powerpc_load_tests.ml
lib_test/powerpc/powerpc_logical_tests.ml
lib_test/powerpc/powerpc_move_tests.ml
lib_test/powerpc/powerpc_rotate_tests.ml
lib_test/powerpc/powerpc_shift_tests.ml
lib_test/powerpc/powerpc_store_tests.ml
lib_test/powerpc/powerpc_tests_helpers.ml
lib_test/powerpc/powerpc_tests_helpers.mli
lib_test/powerpc/run_powerpc_tests.ml
oasis/powerpc

This PR adds tests for `powerpc` architecture

adds powerpc tests

---

CHANGES.md
lib/bap_llvm/llvm_binary_38_40.hpp
lib/bap_llvm/llvm_coff_loader.hpp
lib/bap_llvm/llvm_disasm.cpp
lib/bap_llvm/llvm_elf_loader.hpp
lib/bap_llvm/llvm_loader.hpp
lib/bap_llvm/llvm_macho_loader.hpp
lib/bap_llvm/llvm_primitives.cpp
lib/bap_llvm/llvm_primitives.hpp
plugins/x86/x86_mov_offset.ml

adds `llvm 7.0` support` support

adds `llvm 7.0` support

---

README.md

edited links to documentation and deb packages

updates README file

---

plugins/ida/bap_ida_info.ml
plugins/ida/bap_ida_service.ml

the i64 import error

---

CHANGES.md
oasis/common

updates bap version before release and fixes copyrights too

updates bap version

---

README.md
lib/bap/bap.mli
lib/regular/regular.mli

this PR fixes bap version in README file and also fixes bugs in the documentation: unclosed stop comment and a couple of forgotten deprecations

fixed bap version in README and fixes documentation

---

README.md

this PR adds a link to odoc documentation to our `README` file

adds a link to odoc documentation

---

lib/bap_sema/bap_sema_lift.ml

Context
=======
Since a subroutine is a set of blocks dominated by its entry point it
is possible to encounter blocks that fall to other subroutines. The
block terminator could a simple move instruction, a (conditional)
jump, or a call to another subroutine.
Let me sprinkle the description with a few example, to make it more
concrete.
Example 1.
Original code:
```
42: mov rax, rbx
44: mov rdi, rsi
```
Suppose that byteweight false positive marked address `44` as a
function start, so we need to lift this code as:
```
rbx := rax
call @sub_44 with noreturn
sub_44:
rsi := rdi
```
This was a simple case, which was working before the PR. Here is a
more convoluted example:
Example 2.
Original code:
```
42: mov rax, rbx
44  call printf
4a: mov rdi, rsi
```
and assume that byteweight introduced a …

fixes insertion of calls for fallthroughs in the IR lifter

---

lib/bap_sema/bap_sema_lift.ml

Two cases were missed in #975, both about conditional calls, an extra
jump for the non-taken branch should be added if the call is conditional.

fixes falls after conditional calls

---

lib/bap_sema/bap_sema_lift.ml

A predicated invocation of a procedure which is expected to return, must perform two actions under the same predicate - store the return address and actually do the control flow transfer.
E.g., assume the `bleq foo` instruction
```
if (ZF) {
LR := 4;
call foo
}
```
That will have the following IR
```
when ZF goto @take_call
goto @next
take_call:
LR :=   4
call @foo return @next
next:
```
When we see an interprocedural control flow which is predicated, then we can safely assume that there weren't any data effects under the same predicate, therefore this call is not expected to return.
Of course, it is possible to craft IR which will violate this property, e.g.,
```
LR := 4
when ZF call @foo return @next
call @bar return @next
next:
```
which corresponds to the following pseudocode `if (a = …

prunes return edges for conditional calls

---

lib/bap_disasm/bap_disasm_driver.ml

The disassembler was occasionally missing a start of a basic block
which was a destination of some jump due to an improper (and as always
premature) optimization. Now this is fixed.
While searching I've found yet another (smaller) bug in which we were
cancelling the tasks and afterwards still adding it to the work
list. It didn't ever manifest, I believe.

fixes a missing block start which led to duplicating code

---

lib/bap_sema/bap_sema_lift.ml

After #998, string instructions with the rep prefix are represented
with the `Bil.while` statement and have the semantics of a pure data effect
(and therefore do not break a basic block). However, when we reify while into
IR we still have jump terms. And this wasn't anticipated by the sema lifter,
which was glueing IR constituting one basic block, assuming that there
will not be any complex control flow.
This PR fixes this issue (which is not only specific to #998, this PR just
triggered it, in general, there could be other cases, when pure data effects are
reified into non-simple control structures, cf. conditional moves).
Instead of just appending blocks, ensure that they are connected by an explicit jump.

fixes IR graph for instructions with `Bil.while`

---

plugins/run/run_main.ml

When `run-entry-points` is set to `all-subroutines`, we launch all the subroutines in the topological order. The problem is that if a real callgraph doesn't have a common entry from which all subroutines
are reachable, but instead is represented as a few spanning trees, then the reverse postorder traverse of a graph will produce an ordering that is far from the topological. We address this issue by connecting roots of all trees to an artificial entry point before sorting.
A bonus feature is a new command line option to the run plugin that when set (on by default) will not revisit a subroutine if it was already visited. This is only applicable when a set of entry points
(or all entry points) were specified to the run plugin, and it investigates each in separate.
The justification for this …

fixes the subroutine ordering in the run plugin

---

plugins/cache/cache_main.ml

This PR resolves a couple of long-standing issues with the cache plugin
and provides a more efficient procedure for finding the cache index
(see #966) and prevents the leakage of entries in the case when the same
entry is added twice (see #967).

fixes the cache plugin

---

Makefile

this PR fixes an error in Makefile that breaks bap installation from opam

fixes an error in Makefile

---

CHANGES.md

This is a very quick summary, but still a lot. I also dropped the pre
1.x versions from the changes. It is BAP 2.0 it's time to get rid of
them.

summarizes the changes

---

lib/bap_types/bap_tid_graph.ml

In #1051 we begun inserting `start` and `exit` pseudonodes and
introduced a small bug, when the graph is singleton and has a node
with both indegree and outdegree equal to zero. For that graphs,
instead of
```
digraph {
start -> n -> exit
}
```
we got
```
digraph {
start -> n;
start -> exit;
}
```
since we didn't insert an edge from `n` to `exit`.

fixes start and exit insertion for singleton graphs

---

plugins/primus_lisp/lisp/simple-memory-allocator.lisp

this PR fixes unresolved variables in the realloc stub

fixes a bug in the primus realloc stub

---

lib/bap_llvm/bap_llvm_ogre_elf.ml

Usually, when an ELF binary contains both segments and sections,
we use the latter to determine code regions. Also, sections are
used to print disassembled output via bap <file> -dasm.
And if there are no sections in a binary, we can do nothing with
such file.
This PR resolves this issue and provide all the necessary
information from segments and allow us to process such kind of files.

allows to disassemble elf files without sections

---

lib/bap_llvm/llvm_binary_38_40.hpp
lib/bap_llvm/llvm_coff_loader.hpp
lib/bap_llvm/llvm_disasm.cpp
lib/bap_llvm/llvm_elf_loader.hpp
lib/bap_llvm/llvm_macho_loader.hpp
lib/bap_llvm/llvm_primitives.cpp
lib/bap_llvm/llvm_primitives.hpp
oasis/llvm.setup.ml.in

this PR adds `llvm 10` support

 adds llvm 10 support

---

oasis/stub-resolver
plugins/stub_resolver/run_stub_resolver_tests.ml

This PR makes it possible to build stub resolver with both oasis backends

fixes stub resolver build

---

CHANGES.md
README.md
oasis/common
opam/opam

- refreshes our README, adds more links and highlights new features
- bumps versions of BAP and OCaml
- updates the change log
- updates the links to documentation (all pointing to master docs)
- updates build instructions (deb packages are not yet uploaded)

prepares the 2.1.0 release

---

plugins/radare2/radare2_main.ml

1) the names weren't properly demangled therefore all calls to plt
functions were looking as `imp.X` instead of `X`
2) all entries from the symbol table were interpreted as functions,
including data objects, references to data, and relocations, as a
result we had a few false function starts and bogus functions such as
$a, $b, etc
3) radare2 is providing names even if the name is not known to it,
suggesting bogus `func.X` names. This will prevent other symbolizers
from providing their own names and induce radare2 default function
naming on us, which we don't really want (we prefer to stick with
sub_XXXX for subroutines with unknown name).
Unfortunately, our testing infrastructure were unable to detect this
issues because all tests are using pre-recorded symbolic information,
thus …

fixes several bugs introduced with the radare2 backend

---

plugins/primus_symbolic_executor/primus_symbolic_executor_main.ml

Apparently, timeouts in z3 are specified in milliseconds, so the default timeout of 16 milliseconds is not enough for very slow macOS VMs used in our CI. We bump the default to 1 second and also add a command-line parameter to enable future refinements.

adds the command-line timeout parameter to z3 and bumps the default

---

plugins/radare2/radare2_main.ml

Forgot previously to subtract bias when roots are provided, so when `--llvm-base` was used, radare2 was providing roots at wrong locations.
----
#

makes radare2 respect the bias

---

.github/workflows/release.yml

fixes the (just broken) release workflow

---

plugins/stub_resolver/stub_resolver_main.ml

So far we were assuming that there is only one section for stubs,
but in gcc FCF protection scheme they use `.plt.sec` in _addition_
to `.plt` to represent secured stubs. Therefore we need to keep track
of both, so we upgraded the representation from a simple interval to
an interval tree.
In addition, we added `.plt.sec` to the known names of stubs.

enables multiple stub regions in the stub resolver

---

plugins/bil/bil_lifter.ml

So far it was using the future interface that didn't work properly
when several files were lifted in a row.
This PR is instead #1253, which I didn't find satisfiable.
Fixes #1216.

uses KB to access the specification in the BIL lifter

---

.github/workflows/build-dev-repo.yml
.github/workflows/nightly-testing.yml
.github/workflows/release.yml
.github/workflows/weekly-regress.yml
LICENSE
oasis/common
oasis/common.omake
tools/opam-release.sh

updates versions in the configuration tools, bumps up copyright
dates (also normalizes the MIT license to make it recognizable for
github), and updates the release.sh script for the release automation.

starts 2.3.0 release cycle

---

plugins/raw/raw_main.ml

Adds the new bits option and turns the arch parameter into a string to
enable specifying arbitrary architectures.

updates the raw loader to enable better support for targets

---

plugins/arm/arm_gnueabi.ml

As the initial approaximation we can use the existing EABI
implementation. On the first glance it looks like it generates correct
argument passing procedure.

uses ARM EABI for Thumb binaries

---

plugins/primus_lisp/primus_lisp_main.ml

The `--primus-lisp-semantics` option now only takes folders (no files)
and the current working directory is excluded from the default
path (though it could be added with `--primus-lisp-semantics=.`
if necessary). Also improves the option documentation.

streamlines the --primus-lisp-semantics option

---

plugins/primus_lisp/primus_lisp_semantic_primitives.ml

Arithmetic and bitwise operators in Primus Lisp accept bitvectors of
arbitrary lengths and performs implicit coercion of the operands to
the greatest sort.
However, the first argument was accidentally removed from the
coercion, which is now fixed. In addition, the coercion procedure was
missing an opportunity to perform the coercion statically, which is
done in the new implementation.

fixes implicit coercion in Primus Lisp monoid operators

---

.github/workflows/build-and-test.yml
.github/workflows/build-dev-repo.yml
.github/workflows/build-from-opam.yml
.github/workflows/check-the-style.yml
.github/workflows/nightly-testing.yml
.github/workflows/release.yml
.github/workflows/weekly-regress.yml

The new version might give us much better performance, see the
[discussion][1] for further details.
[1]: https://discuss.ocaml.org/t/ann-set-up-ocaml-2-0-0-alpha/7895

switches workflows to ocaml/setup-ocaml.v2

---

.github/workflows/nightly-testing.yml
.github/workflows/release.yml
.github/workflows/weekly-regress.yml
oasis/common
oasis/common.omake

- bumps versions
- also changes the nightly build prefix to debug ocaml/setup-ocaml#90

starts the 2.4.0 release cycle

---

docker/ubuntu/bionic/Dockerfile

will skip the CI, it will be kicked in later, after the PR.

fixes a typo in the ubuntu dockerfiles

---

lib/bap_primus/bap_primus_lisp_semantics.ml

The Primus Lisp interpreter uses some state and was previously
implemented as the knowledge monad transformed into the state
monad. The new implementation just uses the newly introduces context
variables, which is much easier and a little bit more performant. It
also enables us to persist the interpreter state between the calls so
that we can generate more efficient code (propagate consts between
instructions), especially for the ghidra backend.

uses the context variables to store the Primus Lisp state

---

lib/bap_main/bap_main.ml

Now, if a plugin reports an error (by returning `Error e` or raising an exception) we are not evaluating the commands and terminate the program. Before this change, the command was still evaluated even if some plugins failed their evaluation.

short-circuits evaluation of terms in Bap_main.init

---

lib/bap_llvm/llvm_disasm.cpp
lib/bap_llvm/llvm_elf_loader.hpp

I'm using Void Linux on my personal computer, but they are not maintaining older versions of the `llvm` package (current version is at `12.0.1`).
This may also work with later versions than 12, but I did not test them.

Update LLVM backend to work with version 12

---

plugins/patterns/patterns_main.ml

This is the location where the signatures are installed by the
bap-signatures package.

searches signatures at system-wise bap shared folder

---

plugins/glibc_runtime/glibc_runtime_main.ml

This is a small optimization that makes bap faster if you're not using
Program.t

turns glibc-runtime main discovery into a lazy pass

---

CHANGES.md
README.md
lib/bap_c/bap_c_abi.mli
oasis/common
oasis/common.omake

BAP 2.4.0 is now officially released!

bumps up the version and updates the change log

---

.github/workflows/release.yml
.github/workflows/weekly-regress.yml
oasis/common
oasis/common.omake

2.4.0 is nearly out so it is time to start 2.5.0 :)

starts the 2.5.0 release cycle

---

lib/x86_cpu/x86_target.ml

This PR adds register aliasing information for the x86 target. `AX` is the lower half of `EAX`, which is the lower half of `RAX`, `XMM0` is the lower half of `YMM0`, etc.

Add aliasing information for x86

---

lib/knowledge/bap_knowledge.ml

Implements a symmectric and deeply inlined merge procedure. This reduces memory consumption by about 5 percent.

improves the KB.Value merge operation

---

lib/knowledge/bap_knowledge.ml

Updates the version number to v2 to fix the cache broken in #1411 and adds a couple more small optimizations that give some extra performance boost (about 2%, but still).
Thanks @bmourad01 for the rapid report!

updates the KB version number and adds a few more microoptimizations

---

lib/knowledge/bap_knowledge.ml

thanks @bmourad01 for showing it!

uses the builtin clz function from base, instead of the custom one

---

lib/bap/bap_project.ml

The Project.create function were creating a separate unit in order to compute a target from the available image specification. It was also using Toplevel.eval for that, which computes all properties of an object. As a result, we had all expensive unit-based computations triggered twice per each project.
An ideal solution would be to get rid of this call, but, as an immediate remediation, we can just use the same compilation unit as for the main program and compute only the target slot.

removes unnecessary units from the knowledge base

---

docker/alpine/Dockerfile
docker/archlinux/Dockerfile
docker/fedora/Dockerfile
docker/ubuntu/bionic/Dockerfile
docker/ubuntu/xenial/Dockerfile

the old git:// method is no longer supported

updates to the git+https in the dockerfiles

---

configure
configure-omake

Silences the alert proposed in ocaml/ocaml#11198, but this PR can be merged regardless.

Correct linking of Unix library in configure

---

opam/opam

I hope it was the last unfixed url :)

fixes the opam/opam dev-repo protocol which broke the release action

---

.github/workflows/publish-docker-image-release.yml
docker/2.4.0/Dockerfile

adds an automation to build a docker image for the latest release

---

lib/bap_c/bap_c_type.mli

It is now much easier to construct and deconstruct C types, e.g.,
```
C.Type.basic `char
```
We also added a bunch of predicates and deconstructors. See the PR for more information.

adds smart constructors and destructors to the C types library

---

lib/bap_c/bap_c_abi.ml
lib/bap_c/bap_c_abi.mli

1) the arenas now can hold arbitrary places (specified via
expressions)
2) adds the new `split` operator to split a datum across two arenas
3) publishes `size` and `require` operators
4) adds an `discard` operator for discarding arena places

extends the C.Abi library

---

lib/x86_cpu/x86_target.ml

There's no need to compute the encoding per each address as it is shared (on x86) by all addresses that belong to the same unit.

optimizes encoding computation for x86

---

opam/opam

See also BinaryAnalysisPlatform/opam-repository#67

adds the mmap dependency

---

oasis/x86
plugins/x86/patterns/cet.xml
plugins/x86/patterns/patternconstraints.xml

Not an exhaustive list but it will be easy to add more, once they are discovered.

adds patterns to recognize certain x86 endbr as function starts

---

.github/workflows/release.yml
.github/workflows/weekly-regress.yml
CHANGES.md
oasis/common
oasis/common.omake
tools/opam-release.sh

also fixes the get-last-tag function in the release tools

starts the 2.6.0 release cycle

---

.github/workflows/publish-docker-image-release.yml
docker/2.5.0/Dockerfile

We need to find a better way to automize it, I am very open to suggestions.

adds the release action for the 2.5.0 docker image

---

plugins/primus_loader/primus_loader_basic.ml

Previously, the loader would link every term in the program by name to an address in the Primus environment if such an address existed for it. However, this should only be allowed for blocks and subroutines. This can give a significant speedup in loading time for large programs.

Speeds up `program-loader` by ignoring terms that arent blks or subs

---

lib/bap_plugins/bap_plugins.ml

Removes duplicating packages, provided that they have the same implementation.
When dune executes a binary (either via `dune exec` or `dune test`) it sets an internal `DUNE_DIR_LOCATIONS` environment variable, which affects the selection of plugins in bap, even if bap is installed from an indepenent repository. I am still not sure if this is a bug or a feature of dune, but to prevent double-loading we have to deduplicate plugins. We silently remove duplicating names only if all implementations that match the name are the same. We compare implementation using the sum of md5 sums of files that comprise the plugin folder. The choice of md5 sum as the implementation witness instead of parsing the META files allows us to preserve the abstraction of dune plugins, as the contents of the folder …

deduplicates dune plugins and ignores empty plugins

---

.github/workflows/nightly.yml
.github/workflows/weekly-regress.yml

as per a workaround suggested in https://github.com/ocaml/setup-ocaml/issues/678

attempts to fix the nightly and weekly tests

---

.github/actions/install-ghidra/action.yml
.github/workflows/full.yml
.github/workflows/nightly.yml
.github/workflows/opam.yml
.github/workflows/release.yml
tools/install-ghidra.sh

also moves ghidra into a separate action as it turned out to be more complex (with caching, so I stopped copy-pasting them).

fixes nightly tests and ghidra caching
